In [1]:
import pandas as pd
import time
import datetime
from time import strptime

pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

# Mainan

In [2]:
mainan_dkt_1 = pd.read_excel(r'C:\Users\afriz\Documents\Pekerjaan\YENS\Monthly Project\Monthly Project\mainan dan barber\MAINAN\mainan_dkt_4.xlsx')
mainan_dkt_2 = pd.read_excel(r'C:\Users\afriz\Documents\Pekerjaan\YENS\Monthly Project\Monthly Project\mainan dan barber\MAINAN\mainan_dkt_5.xlsx')
mainan_dkt_3 = pd.read_excel(r'C:\Users\afriz\Documents\Pekerjaan\YENS\Monthly Project\Monthly Project\mainan dan barber\MAINAN\mainan_dkt_6.xlsx')

mainan_lbg_1 = pd.read_excel(r'C:\Users\afriz\Documents\Pekerjaan\YENS\Monthly Project\Monthly Project\mainan dan barber\MAINAN\mainan_lbg_4.xlsx')
mainan_lbg_2 = pd.read_excel(r'C:\Users\afriz\Documents\Pekerjaan\YENS\Monthly Project\Monthly Project\mainan dan barber\MAINAN\mainan_lbg_5.xlsx')
mainan_lbg_3 = pd.read_excel(r'C:\Users\afriz\Documents\Pekerjaan\YENS\Monthly Project\Monthly Project\mainan dan barber\MAINAN\mainan_lbg_6.xlsx')

mainan_stb_1 = pd.read_excel(r'C:\Users\afriz\Documents\Pekerjaan\YENS\Monthly Project\Monthly Project\mainan dan barber\MAINAN\mainan_stb_4.xlsx')
mainan_stb_2 = pd.read_excel(r'C:\Users\afriz\Documents\Pekerjaan\YENS\Monthly Project\Monthly Project\mainan dan barber\MAINAN\mainan_stb_5.xlsx')
mainan_stb_3 = pd.read_excel(r'C:\Users\afriz\Documents\Pekerjaan\YENS\Monthly Project\Monthly Project\mainan dan barber\MAINAN\mainan_stb_6.xlsx')

mainan_tki_1 = pd.read_excel(r'C:\Users\afriz\Documents\Pekerjaan\YENS\Monthly Project\Monthly Project\mainan dan barber\MAINAN\mainan_tki_4.xlsx')
mainan_tki_2 = pd.read_excel(r'C:\Users\afriz\Documents\Pekerjaan\YENS\Monthly Project\Monthly Project\mainan dan barber\MAINAN\mainan_tki_5.xlsx')
mainan_tki_3 = pd.read_excel(r'C:\Users\afriz\Documents\Pekerjaan\YENS\Monthly Project\Monthly Project\mainan dan barber\MAINAN\mainan_tki_6.xlsx')

In [3]:
mainan_dkt_1.columns = mainan_dkt_1.iloc[4]
mainan_dkt_2.columns = mainan_dkt_2.iloc[4]
mainan_dkt_3.columns = mainan_dkt_3.iloc[4]

mainan_lbg_1.columns = mainan_lbg_1.iloc[4]
mainan_lbg_2.columns = mainan_lbg_2.iloc[4]
mainan_lbg_3.columns = mainan_lbg_3.iloc[4]

mainan_stb_1.columns = mainan_stb_1.iloc[4]
mainan_stb_2.columns = mainan_stb_2.iloc[4]
mainan_stb_3.columns = mainan_stb_3.iloc[4]

mainan_tki_1.columns = mainan_tki_1.iloc[4]
mainan_tki_2.columns = mainan_tki_2.iloc[4]
mainan_tki_3.columns = mainan_tki_3.iloc[4]

In [4]:
mainan_dkt_1 = mainan_dkt_1.drop(mainan_dkt_1.index[0:5])
mainan_dkt_2 = mainan_dkt_2.drop(mainan_dkt_2.index[0:5])
mainan_dkt_3 = mainan_dkt_3.drop(mainan_dkt_3.index[0:5])

mainan_lbg_1 = mainan_lbg_1.drop(mainan_lbg_1.index[0:5])
mainan_lbg_2 = mainan_lbg_2.drop(mainan_lbg_2.index[0:5])
mainan_lbg_3 = mainan_lbg_3.drop(mainan_lbg_3.index[0:5])

mainan_stb_1 = mainan_stb_1.drop(mainan_stb_1.index[0:5])
mainan_stb_2 = mainan_stb_2.drop(mainan_stb_2.index[0:5])
mainan_stb_3 = mainan_stb_3.drop(mainan_stb_3.index[0:5])

mainan_tki_1 = mainan_tki_1.drop(mainan_tki_1.index[0:5])
mainan_tki_2 = mainan_tki_2.drop(mainan_tki_2.index[0:5])
mainan_tki_3 = mainan_tki_3.drop(mainan_tki_3.index[0:5])

In [5]:
mainan_dkt_1 = mainan_dkt_1[:-1]
mainan_dkt_2 = mainan_dkt_2[:-1]
mainan_dkt_3 = mainan_dkt_3[:-1]

mainan_lbg_1 = mainan_lbg_1[:-1]
mainan_lbg_2 = mainan_lbg_2[:-1]
mainan_lbg_3 = mainan_lbg_3[:-1]

mainan_stb_1 = mainan_stb_1[:-1]
mainan_stb_2 = mainan_stb_2[:-1]
mainan_stb_3 = mainan_stb_3[:-1]

mainan_tki_1 = mainan_tki_1[:-1]
mainan_tki_2 = mainan_tki_2[:-1]
mainan_tki_3 = mainan_tki_3[:-1]

In [6]:
mainan_dkt_1['cabang'] = 'dkt'
mainan_dkt_2['cabang'] = 'dkt'
mainan_dkt_3['cabang'] = 'dkt'

mainan_lbg_1['cabang'] = 'lbg'
mainan_lbg_2['cabang'] = 'lbg'
mainan_lbg_3['cabang'] = 'lbg'

mainan_stb_1['cabang'] = 'stb'
mainan_stb_2['cabang'] = 'stb'
mainan_stb_3['cabang'] = 'stb'

mainan_tki_1['cabang'] = 'tki'
mainan_tki_2['cabang'] = 'tki'
mainan_tki_3['cabang'] = 'tki'

In [7]:
mainan_dkt_1['bulan'] = '4'
mainan_dkt_2['bulan'] = '5'
mainan_dkt_3['bulan'] = '6'

mainan_lbg_1['bulan'] = '4'
mainan_lbg_2['bulan'] = '5'
mainan_lbg_3['bulan'] = '6'

mainan_stb_1['bulan'] = '4'
mainan_stb_2['bulan'] = '5'
mainan_stb_3['bulan'] = '6'

mainan_tki_1['bulan'] = '4'
mainan_tki_2['bulan'] = '5'
mainan_tki_3['bulan'] = '6'

In [8]:
mn_bulan_1 = pd.concat([mainan_dkt_1,mainan_lbg_1,mainan_stb_1,mainan_tki_1], ignore_index=True)
mn_bulan_2 = pd.concat([mainan_dkt_2,mainan_lbg_2,mainan_stb_2,mainan_tki_2], ignore_index=True)
mn_bulan_3 = pd.concat([mainan_dkt_3,mainan_lbg_3,mainan_stb_3,mainan_tki_3], ignore_index=True)

In [9]:
#create Df bulan 2
mn_merge_1 = pd.merge(mn_bulan_1,mn_bulan_2, how='outer' ,on=['Kode Barang'], indicator=True, suffixes=("_x", ""),)
mn_merge_1["_merge"].replace({"right_only": "right_only_first"}, inplace=True)
mn_merge_1_right = mn_merge_1.loc[mn_merge_1['_merge'] == 'right_only_first']
mn_merge_1_right = mn_merge_1_right.dropna(axis='columns')
mn_merge_concat_1 = pd.concat([mn_bulan_2,mn_merge_1_right])
mn_merge_concat_1['_merge'] = mn_merge_concat_1[['_merge']].fillna(value='both')
merge_drop = mn_merge_concat_1.drop_duplicates(subset=['Kode Barang'], keep='last')

#clean bahan df bulan 3
merge_drop_clean = merge_drop.iloc[:,0:23]

#create Df bulan 3
mn_merge_2 = pd.merge(merge_drop_clean,mn_bulan_3, how='outer' ,on=['Kode Barang'], indicator=True, suffixes=("_x", ""),)
mn_merge_2["_merge"].replace({"right_only": "right_only_second"}, inplace=True)
mn_merge_2_right = mn_merge_2.loc[mn_merge_2['_merge'] == 'right_only_second']
mn_merge_2_right = mn_merge_2_right.dropna(axis='columns')
mn_merge_concat_2 = pd.concat([mn_bulan_3,mn_merge_2_right])
mn_merge_concat_2['_merge'] = mn_merge_concat_2[['_merge']].fillna(value='both')
merge_drop_2 = mn_merge_concat_2.drop_duplicates(subset=['Kode Barang'], keep='last')

#finishing Df bulan 1
mn_bulan_1['_merge'] = 'both_first'

#merger all bulan
mn_all = pd.concat([mn_bulan_1,merge_drop,merge_drop_2],ignore_index=True)

# perhitungan stock bayangan 
# All both
mn_all.loc[mn_all['_merge'] == 'both_first', 'stock bayangan'] = mn_all['Stock Awal']+mn_all['Stock In']
mn_all.loc[mn_all['_merge'] == 'both', 'stock bayangan'] = mn_all['Stock In']
mn_all.loc[mn_all['_merge'] == 'both', 'stock bayangan'] = mn_all['Stock In']
# right only first
mn_all.loc[mn_all['_merge'] == 'right_only_first', 'stock bayangan'] = mn_all['Stock Awal']+mn_all['Stock In']
# right only second
mn_all.loc[mn_all['_merge'] == 'right_only_second', 'stock bayangan'] = mn_all['Stock Awal']+mn_all['Stock In']

In [10]:
#mn_all.to_csv(r'C:\Users\afriz\Documents\Pekerjaan\YENS\Monthly Project\Monthly Project\ready data set\mainan_testing_modeling_5.csv', index=False)

# Barang Besar

In [11]:
barber_dkt_1 = pd.read_excel(r'C:\Users\afriz\Documents\Pekerjaan\YENS\Monthly Project\Monthly Project\mainan dan barber\BARBER\barber_dkt_4.xlsx')
barber_dkt_2 = pd.read_excel(r'C:\Users\afriz\Documents\Pekerjaan\YENS\Monthly Project\Monthly Project\mainan dan barber\BARBER\barber_dkt_5.xlsx')
barber_dkt_3 = pd.read_excel(r'C:\Users\afriz\Documents\Pekerjaan\YENS\Monthly Project\Monthly Project\mainan dan barber\BARBER\barber_dkt_6.xlsx')

barber_lbg_1 = pd.read_excel(r'C:\Users\afriz\Documents\Pekerjaan\YENS\Monthly Project\Monthly Project\mainan dan barber\BARBER\barber_lbg_4.xlsx')
barber_lbg_2 = pd.read_excel(r'C:\Users\afriz\Documents\Pekerjaan\YENS\Monthly Project\Monthly Project\mainan dan barber\BARBER\barber_lbg_5.xlsx')
barber_lbg_3 = pd.read_excel(r'C:\Users\afriz\Documents\Pekerjaan\YENS\Monthly Project\Monthly Project\mainan dan barber\BARBER\barber_lbg_6.xlsx')

barber_stb_1 = pd.read_excel(r'C:\Users\afriz\Documents\Pekerjaan\YENS\Monthly Project\Monthly Project\mainan dan barber\BARBER\barber_stb_4.xlsx')
barber_stb_2 = pd.read_excel(r'C:\Users\afriz\Documents\Pekerjaan\YENS\Monthly Project\Monthly Project\mainan dan barber\BARBER\barber_stb_5.xlsx')
barber_stb_3 = pd.read_excel(r'C:\Users\afriz\Documents\Pekerjaan\YENS\Monthly Project\Monthly Project\mainan dan barber\BARBER\barber_stb_6.xlsx')

barber_tki_1 = pd.read_excel(r'C:\Users\afriz\Documents\Pekerjaan\YENS\Monthly Project\Monthly Project\mainan dan barber\BARBER\barber_tki_4.xlsx')
barber_tki_2 = pd.read_excel(r'C:\Users\afriz\Documents\Pekerjaan\YENS\Monthly Project\Monthly Project\mainan dan barber\BARBER\barber_tki_5.xlsx')
barber_tki_3 = pd.read_excel(r'C:\Users\afriz\Documents\Pekerjaan\YENS\Monthly Project\Monthly Project\mainan dan barber\BARBER\barber_tki_6.xlsx')

In [12]:
barber_dkt_1.columns = barber_dkt_1.iloc[4]
barber_dkt_2.columns = barber_dkt_2.iloc[4]
barber_dkt_3.columns = barber_dkt_3.iloc[4]

barber_lbg_1.columns = barber_lbg_1.iloc[4]
barber_lbg_2.columns = barber_lbg_2.iloc[4]
barber_lbg_3.columns = barber_lbg_3.iloc[4]

barber_stb_1.columns = barber_stb_1.iloc[4]
barber_stb_2.columns = barber_stb_2.iloc[4]
barber_stb_3.columns = barber_stb_3.iloc[4]

barber_tki_1.columns = barber_tki_1.iloc[4]
barber_tki_2.columns = barber_tki_2.iloc[4]
barber_tki_3.columns = barber_tki_3.iloc[4]

In [13]:
barber_dkt_1 = barber_dkt_1.drop(barber_dkt_1.index[0:5])
barber_dkt_2 = barber_dkt_2.drop(barber_dkt_2.index[0:5])
barber_dkt_3 = barber_dkt_3.drop(barber_dkt_3.index[0:5])

barber_lbg_1 = barber_lbg_1.drop(barber_lbg_1.index[0:5])
barber_lbg_2 = barber_lbg_2.drop(barber_lbg_2.index[0:5])
barber_lbg_3 = barber_lbg_3.drop(barber_lbg_3.index[0:5])

barber_stb_1 = barber_stb_1.drop(barber_stb_1.index[0:5])
barber_stb_2 = barber_stb_2.drop(barber_stb_2.index[0:5])
barber_stb_3 = barber_stb_3.drop(barber_stb_3.index[0:5])

barber_tki_1 = barber_tki_1.drop(barber_tki_1.index[0:5])
barber_tki_2 = barber_tki_2.drop(barber_tki_2.index[0:5])
barber_tki_3 = barber_tki_3.drop(barber_tki_3.index[0:5])

In [14]:

barber_dkt_1 = barber_dkt_1[:-1]
barber_dkt_2 = barber_dkt_2[:-1]
barber_dkt_3 = barber_dkt_3[:-1]

barber_lbg_1 = barber_lbg_1[:-1]
barber_lbg_2 = barber_lbg_2[:-1]
barber_lbg_3 = barber_lbg_3[:-1]

barber_stb_1 = barber_stb_1[:-1]
barber_stb_2 = barber_stb_2[:-1]
barber_stb_3 = barber_stb_3[:-1]

barber_tki_1 = barber_tki_1[:-1]
barber_tki_2 = barber_tki_2[:-1]
barber_tki_3 = barber_tki_3[:-1]

In [15]:
barber_dkt_1['cabang'] = 'dkt'
barber_dkt_2['cabang'] = 'dkt'
barber_dkt_3['cabang'] = 'dkt'

barber_lbg_1['cabang'] = 'lbg'
barber_lbg_2['cabang'] = 'lbg'
barber_lbg_3['cabang'] = 'lbg'

barber_stb_1['cabang'] = 'stb'
barber_stb_2['cabang'] = 'stb'
barber_stb_3['cabang'] = 'stb'

barber_tki_1['cabang'] = 'tki'
barber_tki_2['cabang'] = 'tki'
barber_tki_3['cabang'] = 'tki'

In [16]:
barber_dkt_1['bulan'] = '4'
barber_dkt_2['bulan'] = '5'
barber_dkt_3['bulan'] = '6'

barber_lbg_1['bulan'] = '4'
barber_lbg_2['bulan'] = '5'
barber_lbg_3['bulan'] = '6'

barber_stb_1['bulan'] = '4'
barber_stb_2['bulan'] = '5'
barber_stb_3['bulan'] = '6'

barber_tki_1['bulan'] = '4'
barber_tki_2['bulan'] = '5'
barber_tki_3['bulan'] = '6'

In [17]:
bb_bulan_1 = pd.concat([barber_dkt_1,barber_lbg_1,barber_stb_1,barber_tki_1], ignore_index=True)
bb_bulan_2 = pd.concat([barber_dkt_2,barber_lbg_2,barber_stb_2,barber_tki_2], ignore_index=True)
bb_bulan_3 = pd.concat([barber_dkt_3,barber_lbg_3,barber_stb_3,barber_tki_3], ignore_index=True)

In [18]:
#create Df bulan 2
bb_merge_1 = pd.merge(bb_bulan_1,bb_bulan_2, how='outer' ,on=['Kode Barang'], indicator=True, suffixes=("_x", ""),)
bb_merge_1["_merge"].replace({"right_only": "right_only_first"}, inplace=True)
bb_merge_1_right = bb_merge_1.loc[bb_merge_1['_merge'] == 'right_only_first']
bb_merge_1_right = bb_merge_1_right.dropna(axis='columns')
bb_merge_concat_1 = pd.concat([bb_bulan_2,bb_merge_1_right])
bb_merge_concat_1['_merge'] = bb_merge_concat_1[['_merge']].fillna(value='both')
merge_drop = bb_merge_concat_1.drop_duplicates(subset=['Kode Barang'], keep='last')

#clean bahan df bulan 3
merge_drop_clean = merge_drop.iloc[:,0:23]

#create Df bulan 3
bb_merge_2 = pd.merge(merge_drop_clean,bb_bulan_3, how='outer' ,on=['Kode Barang'], indicator=True, suffixes=("_x", ""),)
bb_merge_2["_merge"].replace({"right_only": "right_only_second"}, inplace=True)
bb_merge_2_right = bb_merge_2.loc[bb_merge_2['_merge'] == 'right_only_second']
bb_merge_2_right = bb_merge_2_right.dropna(axis='columns')
bb_merge_concat_2 = pd.concat([bb_bulan_3,bb_merge_2_right])
bb_merge_concat_2['_merge'] = bb_merge_concat_2[['_merge']].fillna(value='both')
merge_drop_2 = bb_merge_concat_2.drop_duplicates(subset=['Kode Barang'], keep='last')

#finishing Df bulan 1
bb_bulan_1['_merge'] = 'both_first'

#merger all bulan
bb_all = pd.concat([bb_bulan_1,merge_drop,merge_drop_2],ignore_index=True)

# perhitungan stock bayangan 
# All both
bb_all.loc[bb_all['_merge'] == 'both_first', 'stock bayangan'] = bb_all['Stock Awal']+bb_all['Stock In']
bb_all.loc[bb_all['_merge'] == 'both', 'stock bayangan'] = bb_all['Stock In']
bb_all.loc[bb_all['_merge'] == 'both', 'stock bayangan'] = bb_all['Stock In']
# right only first
bb_all.loc[bb_all['_merge'] == 'right_only_first', 'stock bayangan'] = bb_all['Stock Awal']+bb_all['Stock In']
# right only second
bb_all.loc[bb_all['_merge'] == 'right_only_second', 'stock bayangan'] = bb_all['Stock Awal']+bb_all['Stock In']

In [19]:
#bb_all.to_csv(r'C:\Users\afriz\Documents\Pekerjaan\YENS\Monthly Project\Monthly Project\ready data set\barber_testing_modeling_5.csv', index=False)

# FOOD

In [20]:
Food_dkt_1 = pd.read_excel(r'C:\Users\afriz\Documents\Pekerjaan\YENS\Monthly Project\Monthly Project\Food\Food_dkt_22_4.xlsx')
Food_dkt_2 = pd.read_excel(r'C:\Users\afriz\Documents\Pekerjaan\YENS\Monthly Project\Monthly Project\Food\Food_dkt_22_5.xlsx')
Food_dkt_3 = pd.read_excel(r'C:\Users\afriz\Documents\Pekerjaan\YENS\Monthly Project\Monthly Project\Food\Food_dkt_22_6.xlsx')

Food_lbg_1 = pd.read_excel(r'C:\Users\afriz\Documents\Pekerjaan\YENS\Monthly Project\Monthly Project\Food\Food_lbg_22_4.xlsx')
Food_lbg_2 = pd.read_excel(r'C:\Users\afriz\Documents\Pekerjaan\YENS\Monthly Project\Monthly Project\Food\Food_lbg_22_5.xlsx')
Food_lbg_3 = pd.read_excel(r'C:\Users\afriz\Documents\Pekerjaan\YENS\Monthly Project\Monthly Project\Food\Food_lbg_22_6.xlsx')

Food_stb_1 = pd.read_excel(r'C:\Users\afriz\Documents\Pekerjaan\YENS\Monthly Project\Monthly Project\Food\Food_stb_22_4.xlsx')
Food_stb_2 = pd.read_excel(r'C:\Users\afriz\Documents\Pekerjaan\YENS\Monthly Project\Monthly Project\Food\Food_stb_22_5.xlsx')
Food_stb_3 = pd.read_excel(r'C:\Users\afriz\Documents\Pekerjaan\YENS\Monthly Project\Monthly Project\Food\Food_stb_22_6.xlsx')

Food_tki_1 = pd.read_excel(r'C:\Users\afriz\Documents\Pekerjaan\YENS\Monthly Project\Monthly Project\Food\Food_tki_22_4.xlsx')
Food_tki_2 = pd.read_excel(r'C:\Users\afriz\Documents\Pekerjaan\YENS\Monthly Project\Monthly Project\Food\Food_tki_22_5.xlsx')
Food_tki_3 = pd.read_excel(r'C:\Users\afriz\Documents\Pekerjaan\YENS\Monthly Project\Monthly Project\Food\Food_tki_22_6.xlsx')

In [21]:
Food_dkt_1.columns = Food_dkt_1.iloc[4]
Food_dkt_2.columns = Food_dkt_2.iloc[4]
Food_dkt_3.columns = Food_dkt_3.iloc[4]

Food_lbg_1.columns = Food_lbg_1.iloc[4]
Food_lbg_2.columns = Food_lbg_2.iloc[4]
Food_lbg_3.columns = Food_lbg_3.iloc[4]

Food_stb_1.columns = Food_stb_1.iloc[4]
Food_stb_2.columns = Food_stb_2.iloc[4]
Food_stb_3.columns = Food_stb_3.iloc[4]

Food_tki_1.columns = Food_tki_1.iloc[4]
Food_tki_2.columns = Food_tki_2.iloc[4]
Food_tki_3.columns = Food_tki_3.iloc[4]

In [22]:
Food_dkt_1 = Food_dkt_1.drop(Food_dkt_1.index[0:5])
Food_dkt_2 = Food_dkt_2.drop(Food_dkt_2.index[0:5])
Food_dkt_3 = Food_dkt_3.drop(Food_dkt_3.index[0:5])

Food_lbg_1 = Food_lbg_1.drop(Food_lbg_1.index[0:5])
Food_lbg_2 = Food_lbg_2.drop(Food_lbg_2.index[0:5])
Food_lbg_3 = Food_lbg_3.drop(Food_lbg_3.index[0:5])

Food_stb_1 = Food_stb_1.drop(Food_stb_1.index[0:5])
Food_stb_2 = Food_stb_2.drop(Food_stb_2.index[0:5])
Food_stb_3 = Food_stb_3.drop(Food_stb_3.index[0:5])

Food_tki_1 = Food_tki_1.drop(Food_tki_1.index[0:5])
Food_tki_2 = Food_tki_2.drop(Food_tki_2.index[0:5])
Food_tki_3 = Food_tki_3.drop(Food_tki_3.index[0:5])

In [23]:
Food_dkt_1 = Food_dkt_1[:-1]
Food_dkt_2 = Food_dkt_2[:-1]
Food_dkt_3 = Food_dkt_3[:-1]

Food_lbg_1 = Food_lbg_1[:-1]
Food_lbg_2 = Food_lbg_2[:-1]
Food_lbg_3 = Food_lbg_3[:-1]

Food_stb_1 = Food_stb_1[:-1]
Food_stb_2 = Food_stb_2[:-1]
Food_stb_3 = Food_stb_3[:-1]

Food_tki_1 = Food_tki_1[:-1]
Food_tki_2 = Food_tki_2[:-1]
Food_tki_3 = Food_tki_3[:-1]

In [24]:
Food_dkt_1['cabang'] = 'dkt'
Food_dkt_2['cabang'] = 'dkt'
Food_dkt_3['cabang'] = 'dkt'

Food_lbg_1['cabang'] = 'lbg'
Food_lbg_2['cabang'] = 'lbg'
Food_lbg_3['cabang'] = 'lbg'

Food_stb_1['cabang'] = 'stb'
Food_stb_2['cabang'] = 'stb'
Food_stb_3['cabang'] = 'stb'

Food_tki_1['cabang'] = 'tki'
Food_tki_2['cabang'] = 'tki'
Food_tki_3['cabang'] = 'tki'

In [25]:
Food_dkt_1['bulan'] = '4'
Food_dkt_2['bulan'] = '5'
Food_dkt_3['bulan'] = '6'

Food_lbg_1['bulan'] = '4'
Food_lbg_2['bulan'] = '5'
Food_lbg_3['bulan'] = '6'

Food_stb_1['bulan'] = '4'
Food_stb_2['bulan'] = '5'
Food_stb_3['bulan'] = '6'

Food_tki_1['bulan'] = '4'
Food_tki_2['bulan'] = '5'
Food_tki_3['bulan'] = '6'

In [26]:
fd_bulan_1 = pd.concat([Food_dkt_1,Food_lbg_1,Food_stb_1,Food_tki_1], ignore_index=True)
fd_bulan_2 = pd.concat([Food_dkt_2,Food_lbg_2,Food_stb_2,Food_tki_2], ignore_index=True)
fd_bulan_3 = pd.concat([Food_dkt_3,Food_lbg_3,Food_stb_3,Food_tki_3], ignore_index=True)

In [27]:
#create Df bulan 2
fd_merge_1 = pd.merge(fd_bulan_1,fd_bulan_2, how='outer' ,on=['Kode Barang'], indicator=True, suffixes=("_x", ""),)
fd_merge_1["_merge"].replace({"right_only": "right_only_first"}, inplace=True)
fd_merge_1_right = fd_merge_1.loc[fd_merge_1['_merge'] == 'right_only_first']
fd_merge_1_right = fd_merge_1_right.dropna(axis='columns')
fd_merge_concat_1 = pd.concat([fd_bulan_2,fd_merge_1_right])
fd_merge_concat_1['_merge'] = fd_merge_concat_1[['_merge']].fillna(value='both')
merge_drop = fd_merge_concat_1.drop_duplicates(subset=['Kode Barang'], keep='last')

#clean bahan df bulan 3
merge_drop_clean = merge_drop.iloc[:,0:23]

#create Df bulan 3
fd_merge_2 = pd.merge(merge_drop_clean,fd_bulan_3, how='outer' ,on=['Kode Barang'], indicator=True, suffixes=("_x", ""),)
fd_merge_2["_merge"].replace({"right_only": "right_only_second"}, inplace=True)
fd_merge_2_right = fd_merge_2.loc[fd_merge_2['_merge'] == 'right_only_second']
fd_merge_2_right = fd_merge_2_right.dropna(axis='columns')
fd_merge_concat_2 = pd.concat([fd_bulan_3,fd_merge_2_right])
fd_merge_concat_2['_merge'] = fd_merge_concat_2[['_merge']].fillna(value='both')
merge_drop_2 = fd_merge_concat_2.drop_duplicates(subset=['Kode Barang'], keep='last')

#finishing Df bulan 1
fd_bulan_1['_merge'] = 'both_first'

#merger all bulan
food_all = pd.concat([fd_bulan_1,merge_drop,merge_drop_2],ignore_index=True)

# perhitungan stock bayangan 
# All both
food_all.loc[food_all['_merge'] == 'both_first', 'stock bayangan'] = food_all['Stock Awal']+food_all['Stock In']
food_all.loc[food_all['_merge'] == 'both', 'stock bayangan'] = food_all['Stock In']
food_all.loc[food_all['_merge'] == 'both', 'stock bayangan'] = food_all['Stock In']
# right only first
food_all.loc[food_all['_merge'] == 'right_only_first', 'stock bayangan'] = food_all['Stock Awal']+food_all['Stock In']
# right only second
food_all.loc[food_all['_merge'] == 'right_only_second', 'stock bayangan'] = food_all['Stock Awal']+food_all['Stock In']

In [28]:
#fd_all.to_csv(r'C:\Users\afriz\Documents\Pekerjaan\YENS\Monthly Project\Monthly Project\ready data set\food_testing_modeling_5.csv', index=False)

# TOILETRIES

In [29]:
Toiletries_dkt_1 = pd.read_excel(r'C:\Users\afriz\Documents\Pekerjaan\YENS\Monthly Project\Monthly Project\Toiletries\Toiletries_dkt_22_4.xlsx')
Toiletries_dkt_2 = pd.read_excel(r'C:\Users\afriz\Documents\Pekerjaan\YENS\Monthly Project\Monthly Project\Toiletries\Toiletries_dkt_22_5.xlsx')
Toiletries_dkt_3 = pd.read_excel(r'C:\Users\afriz\Documents\Pekerjaan\YENS\Monthly Project\Monthly Project\Toiletries\Toiletries_dkt_22_6.xlsx')

Toiletries_lbg_1 = pd.read_excel(r'C:\Users\afriz\Documents\Pekerjaan\YENS\Monthly Project\Monthly Project\Toiletries\Toiletries_lbg_22_4.xlsx')
Toiletries_lbg_2 = pd.read_excel(r'C:\Users\afriz\Documents\Pekerjaan\YENS\Monthly Project\Monthly Project\Toiletries\Toiletries_lbg_22_5.xlsx')
Toiletries_lbg_3 = pd.read_excel(r'C:\Users\afriz\Documents\Pekerjaan\YENS\Monthly Project\Monthly Project\Toiletries\Toiletries_lbg_22_6.xlsx')

Toiletries_stb_1 = pd.read_excel(r'C:\Users\afriz\Documents\Pekerjaan\YENS\Monthly Project\Monthly Project\Toiletries\Toiletries_stb_22_4.xlsx')
Toiletries_stb_2 = pd.read_excel(r'C:\Users\afriz\Documents\Pekerjaan\YENS\Monthly Project\Monthly Project\Toiletries\Toiletries_stb_22_5.xlsx')
Toiletries_stb_3 = pd.read_excel(r'C:\Users\afriz\Documents\Pekerjaan\YENS\Monthly Project\Monthly Project\Toiletries\Toiletries_stb_22_6.xlsx')

Toiletries_tki_1 = pd.read_excel(r'C:\Users\afriz\Documents\Pekerjaan\YENS\Monthly Project\Monthly Project\Toiletries\Toiletries_tki_22_4.xlsx')
Toiletries_tki_2 = pd.read_excel(r'C:\Users\afriz\Documents\Pekerjaan\YENS\Monthly Project\Monthly Project\Toiletries\Toiletries_tki_22_5.xlsx')
Toiletries_tki_3 = pd.read_excel(r'C:\Users\afriz\Documents\Pekerjaan\YENS\Monthly Project\Monthly Project\Toiletries\Toiletries_tki_22_6.xlsx')

In [30]:
Toiletries_dkt_1.columns = Toiletries_dkt_1.iloc[4]
Toiletries_dkt_2.columns = Toiletries_dkt_2.iloc[4]
Toiletries_dkt_3.columns = Toiletries_dkt_3.iloc[4]

Toiletries_lbg_1.columns = Toiletries_lbg_1.iloc[4]
Toiletries_lbg_2.columns = Toiletries_lbg_2.iloc[4]
Toiletries_lbg_3.columns = Toiletries_lbg_3.iloc[4]

Toiletries_stb_1.columns = Toiletries_stb_1.iloc[4]
Toiletries_stb_2.columns = Toiletries_stb_2.iloc[4]
Toiletries_stb_3.columns = Toiletries_stb_3.iloc[4]

Toiletries_tki_1.columns = Toiletries_tki_1.iloc[4]
Toiletries_tki_2.columns = Toiletries_tki_2.iloc[4]
Toiletries_tki_3.columns = Toiletries_tki_3.iloc[4]

In [31]:
Toiletries_dkt_1 = Toiletries_dkt_1.drop(Toiletries_dkt_1.index[0:5])
Toiletries_dkt_2 = Toiletries_dkt_2.drop(Toiletries_dkt_2.index[0:5])
Toiletries_dkt_3 = Toiletries_dkt_3.drop(Toiletries_dkt_3.index[0:5])

Toiletries_lbg_1 = Toiletries_lbg_1.drop(Toiletries_lbg_1.index[0:5])
Toiletries_lbg_2 = Toiletries_lbg_2.drop(Toiletries_lbg_2.index[0:5])
Toiletries_lbg_3 = Toiletries_lbg_3.drop(Toiletries_lbg_3.index[0:5])

Toiletries_stb_1 = Toiletries_stb_1.drop(Toiletries_stb_1.index[0:5])
Toiletries_stb_2 = Toiletries_stb_2.drop(Toiletries_stb_2.index[0:5])
Toiletries_stb_3 = Toiletries_stb_3.drop(Toiletries_stb_3.index[0:5])

Toiletries_tki_1 = Toiletries_tki_1.drop(Toiletries_tki_1.index[0:5])
Toiletries_tki_2 = Toiletries_tki_2.drop(Toiletries_tki_2.index[0:5])
Toiletries_tki_3 = Toiletries_tki_3.drop(Toiletries_tki_3.index[0:5])

In [32]:
Toiletries_dkt_1 = Toiletries_dkt_1[:-1]
Toiletries_dkt_2 = Toiletries_dkt_2[:-1]
Toiletries_dkt_3 = Toiletries_dkt_3[:-1]

Toiletries_lbg_1 = Toiletries_lbg_1[:-1]
Toiletries_lbg_2 = Toiletries_lbg_2[:-1]
Toiletries_lbg_3 = Toiletries_lbg_3[:-1]

Toiletries_stb_1 = Toiletries_stb_1[:-1]
Toiletries_stb_2 = Toiletries_stb_2[:-1]
Toiletries_stb_3 = Toiletries_stb_3[:-1]

Toiletries_tki_1 = Toiletries_tki_1[:-1]
Toiletries_tki_2 = Toiletries_tki_2[:-1]
Toiletries_tki_3 = Toiletries_tki_3[:-1]

In [33]:
Toiletries_dkt_1['cabang'] = 'dkt'
Toiletries_dkt_2['cabang'] = 'dkt'
Toiletries_dkt_3['cabang'] = 'dkt'

Toiletries_lbg_1['cabang'] = 'lbg'
Toiletries_lbg_2['cabang'] = 'lbg'
Toiletries_lbg_3['cabang'] = 'lbg'

Toiletries_stb_1['cabang'] = 'stb'
Toiletries_stb_2['cabang'] = 'stb'
Toiletries_stb_3['cabang'] = 'stb'

Toiletries_tki_1['cabang'] = 'tki'
Toiletries_tki_2['cabang'] = 'tki'
Toiletries_tki_3['cabang'] = 'tki'

In [34]:
Toiletries_dkt_1['bulan'] = '4'
Toiletries_dkt_2['bulan'] = '5'
Toiletries_dkt_3['bulan'] = '6'

Toiletries_lbg_1['bulan'] = '4'
Toiletries_lbg_2['bulan'] = '5'
Toiletries_lbg_3['bulan'] = '6'

Toiletries_stb_1['bulan'] = '4'
Toiletries_stb_2['bulan'] = '5'
Toiletries_stb_3['bulan'] = '6'

Toiletries_tki_1['bulan'] = '4'
Toiletries_tki_2['bulan'] = '5'
Toiletries_tki_3['bulan'] = '6'

In [35]:
tlt_bulan_1 = pd.concat([Toiletries_dkt_1,Toiletries_lbg_1,Toiletries_stb_1,Toiletries_tki_1], ignore_index=True)
tlt_bulan_2 = pd.concat([Toiletries_dkt_2,Toiletries_lbg_2,Toiletries_stb_2,Toiletries_tki_2], ignore_index=True)
tlt_bulan_3 = pd.concat([Toiletries_dkt_3,Toiletries_lbg_3,Toiletries_stb_3,Toiletries_tki_3], ignore_index=True)

In [36]:
#create Df bulan 2
tlt_merge_1 = pd.merge(tlt_bulan_1,tlt_bulan_2, how='outer' ,on=['Kode Barang'], indicator=True, suffixes=("_x", ""),)
tlt_merge_1["_merge"].replace({"right_only": "right_only_first"}, inplace=True)
tlt_merge_1_right = tlt_merge_1.loc[tlt_merge_1['_merge'] == 'right_only_first']
tlt_merge_1_right = tlt_merge_1_right.dropna(axis='columns')
tlt_merge_concat_1 = pd.concat([tlt_bulan_2,tlt_merge_1_right])
tlt_merge_concat_1['_merge'] = tlt_merge_concat_1[['_merge']].fillna(value='both')
merge_drop = tlt_merge_concat_1.drop_duplicates(subset=['Kode Barang'], keep='last')

#clean bahan df bulan 3
merge_drop_clean = merge_drop.iloc[:,0:23]

#create Df bulan 3
tlt_merge_2 = pd.merge(merge_drop_clean,tlt_bulan_3, how='outer' ,on=['Kode Barang'], indicator=True, suffixes=("_x", ""),)
tlt_merge_2["_merge"].replace({"right_only": "right_only_second"}, inplace=True)
tlt_merge_2_right = tlt_merge_2.loc[tlt_merge_2['_merge'] == 'right_only_second']
tlt_merge_2_right = tlt_merge_2_right.dropna(axis='columns')
tlt_merge_concat_2 = pd.concat([tlt_bulan_3,tlt_merge_2_right])
tlt_merge_concat_2['_merge'] = tlt_merge_concat_2[['_merge']].fillna(value='both')
merge_drop_2 = tlt_merge_concat_2.drop_duplicates(subset=['Kode Barang'], keep='last')

#finishing Df bulan 1
tlt_bulan_1['_merge'] = 'both_first'

#merger all bulan
tlt_all = pd.concat([tlt_bulan_1,merge_drop,merge_drop_2],ignore_index=True)

# perhitungan stock bayangan 
# All both
tlt_all.loc[tlt_all['_merge'] == 'both_first', 'stock bayangan'] = tlt_all['Stock Awal']+tlt_all['Stock In']
tlt_all.loc[tlt_all['_merge'] == 'both', 'stock bayangan'] = tlt_all['Stock In']
tlt_all.loc[tlt_all['_merge'] == 'both', 'stock bayangan'] = tlt_all['Stock In']
# right only first
tlt_all.loc[tlt_all['_merge'] == 'right_only_first', 'stock bayangan'] = tlt_all['Stock Awal']+tlt_all['Stock In']
# right only second
tlt_all.loc[tlt_all['_merge'] == 'right_only_second', 'stock bayangan'] = tlt_all['Stock Awal']+tlt_all['Stock In']

In [37]:
#tlt_all.to_csv(r'C:\Users\afriz\Documents\Pekerjaan\YENS\Monthly Project\Monthly Project\ready data set\Toiletries_testing_modeling_5.csv', index=False)

# KONSINYASI

In [38]:
Konsinyasi_dkt_1 = pd.read_excel(r'C:\Users\afriz\Documents\Pekerjaan\YENS\Monthly Project\Monthly Project\Konsinyasi\Konsinyasi_dkt_22_4.xlsx')
Konsinyasi_dkt_2 = pd.read_excel(r'C:\Users\afriz\Documents\Pekerjaan\YENS\Monthly Project\Monthly Project\Konsinyasi\Konsinyasi_dkt_22_5.xlsx')
Konsinyasi_dkt_3 = pd.read_excel(r'C:\Users\afriz\Documents\Pekerjaan\YENS\Monthly Project\Monthly Project\Konsinyasi\Konsinyasi_dkt_22_6.xlsx')

Konsinyasi_lbg_1 = pd.read_excel(r'C:\Users\afriz\Documents\Pekerjaan\YENS\Monthly Project\Monthly Project\Konsinyasi\Konsinyasi_lbg_22_4.xlsx')
Konsinyasi_lbg_2 = pd.read_excel(r'C:\Users\afriz\Documents\Pekerjaan\YENS\Monthly Project\Monthly Project\Konsinyasi\Konsinyasi_lbg_22_5.xlsx')
Konsinyasi_lbg_3 = pd.read_excel(r'C:\Users\afriz\Documents\Pekerjaan\YENS\Monthly Project\Monthly Project\Konsinyasi\Konsinyasi_lbg_22_6.xlsx')

Konsinyasi_stb_1 = pd.read_excel(r'C:\Users\afriz\Documents\Pekerjaan\YENS\Monthly Project\Monthly Project\Konsinyasi\Konsinyasi_stb_22_4.xlsx')
Konsinyasi_stb_2 = pd.read_excel(r'C:\Users\afriz\Documents\Pekerjaan\YENS\Monthly Project\Monthly Project\Konsinyasi\Konsinyasi_stb_22_5.xlsx')
Konsinyasi_stb_3 = pd.read_excel(r'C:\Users\afriz\Documents\Pekerjaan\YENS\Monthly Project\Monthly Project\Konsinyasi\Konsinyasi_stb_22_6.xlsx')

Konsinyasi_tki_1 = pd.read_excel(r'C:\Users\afriz\Documents\Pekerjaan\YENS\Monthly Project\Monthly Project\Konsinyasi\Konsinyasi_tki_22_4.xlsx')
Konsinyasi_tki_2 = pd.read_excel(r'C:\Users\afriz\Documents\Pekerjaan\YENS\Monthly Project\Monthly Project\Konsinyasi\Konsinyasi_tki_22_5.xlsx')
Konsinyasi_tki_3 = pd.read_excel(r'C:\Users\afriz\Documents\Pekerjaan\YENS\Monthly Project\Monthly Project\Konsinyasi\Konsinyasi_tki_22_6.xlsx')

In [39]:
Konsinyasi_dkt_1.columns = Konsinyasi_dkt_1.iloc[4]
Konsinyasi_dkt_2.columns = Konsinyasi_dkt_2.iloc[4]
Konsinyasi_dkt_3.columns = Konsinyasi_dkt_3.iloc[4]

Konsinyasi_lbg_1.columns = Konsinyasi_lbg_1.iloc[4]
Konsinyasi_lbg_2.columns = Konsinyasi_lbg_2.iloc[4]
Konsinyasi_lbg_3.columns = Konsinyasi_lbg_3.iloc[4]

Konsinyasi_stb_1.columns = Konsinyasi_stb_1.iloc[4]
Konsinyasi_stb_2.columns = Konsinyasi_stb_2.iloc[4]
Konsinyasi_stb_3.columns = Konsinyasi_stb_3.iloc[4]

Konsinyasi_tki_1.columns = Konsinyasi_tki_1.iloc[4]
Konsinyasi_tki_2.columns = Konsinyasi_tki_2.iloc[4]
Konsinyasi_tki_3.columns = Konsinyasi_tki_3.iloc[4]

In [40]:
Konsinyasi_dkt_1 = Konsinyasi_dkt_1.drop(Konsinyasi_dkt_1.index[0:5])
Konsinyasi_dkt_2 = Konsinyasi_dkt_2.drop(Konsinyasi_dkt_2.index[0:5])
Konsinyasi_dkt_3 = Konsinyasi_dkt_3.drop(Konsinyasi_dkt_3.index[0:5])

Konsinyasi_lbg_1 = Konsinyasi_lbg_1.drop(Konsinyasi_lbg_1.index[0:5])
Konsinyasi_lbg_2 = Konsinyasi_lbg_2.drop(Konsinyasi_lbg_2.index[0:5])
Konsinyasi_lbg_3 = Konsinyasi_lbg_3.drop(Konsinyasi_lbg_3.index[0:5])

Konsinyasi_stb_1 = Konsinyasi_stb_1.drop(Konsinyasi_stb_1.index[0:5])
Konsinyasi_stb_2 = Konsinyasi_stb_2.drop(Konsinyasi_stb_2.index[0:5])
Konsinyasi_stb_3 = Konsinyasi_stb_3.drop(Konsinyasi_stb_3.index[0:5])

Konsinyasi_tki_1 = Konsinyasi_tki_1.drop(Konsinyasi_tki_1.index[0:5])
Konsinyasi_tki_2 = Konsinyasi_tki_2.drop(Konsinyasi_tki_2.index[0:5])
Konsinyasi_tki_3 = Konsinyasi_tki_3.drop(Konsinyasi_tki_3.index[0:5])

In [41]:
Konsinyasi_dkt_1 = Konsinyasi_dkt_1[:-1]
Konsinyasi_dkt_2 = Konsinyasi_dkt_2[:-1]
Konsinyasi_dkt_3 = Konsinyasi_dkt_3[:-1]

Konsinyasi_lbg_1 = Konsinyasi_lbg_1[:-1]
Konsinyasi_lbg_2 = Konsinyasi_lbg_2[:-1]
Konsinyasi_lbg_3 = Konsinyasi_lbg_3[:-1]

Konsinyasi_stb_1 = Konsinyasi_stb_1[:-1]
Konsinyasi_stb_2 = Konsinyasi_stb_2[:-1]
Konsinyasi_stb_3 = Konsinyasi_stb_3[:-1]

Konsinyasi_tki_1 = Konsinyasi_tki_1[:-1]
Konsinyasi_tki_2 = Konsinyasi_tki_2[:-1]
Konsinyasi_tki_3 = Konsinyasi_tki_3[:-1]

In [42]:
Konsinyasi_dkt_1['cabang'] = 'dkt'
Konsinyasi_dkt_2['cabang'] = 'dkt'
Konsinyasi_dkt_3['cabang'] = 'dkt'

Konsinyasi_lbg_1['cabang'] = 'lbg'
Konsinyasi_lbg_2['cabang'] = 'lbg'
Konsinyasi_lbg_3['cabang'] = 'lbg'

Konsinyasi_stb_1['cabang'] = 'stb'
Konsinyasi_stb_2['cabang'] = 'stb'
Konsinyasi_stb_3['cabang'] = 'stb'

Konsinyasi_tki_1['cabang'] = 'tki'
Konsinyasi_tki_2['cabang'] = 'tki'
Konsinyasi_tki_3['cabang'] = 'tki'

In [43]:
Konsinyasi_dkt_1['bulan'] = '4'
Konsinyasi_dkt_2['bulan'] = '5'
Konsinyasi_dkt_3['bulan'] = '6'

Konsinyasi_lbg_1['bulan'] = '4'
Konsinyasi_lbg_2['bulan'] = '5'
Konsinyasi_lbg_3['bulan'] = '6'

Konsinyasi_stb_1['bulan'] = '4'
Konsinyasi_stb_2['bulan'] = '5'
Konsinyasi_stb_3['bulan'] = '6'

Konsinyasi_tki_1['bulan'] = '4'
Konsinyasi_tki_2['bulan'] = '5'
Konsinyasi_tki_3['bulan'] = '6'

In [44]:
kns_bulan_1 = pd.concat([Konsinyasi_dkt_1,Konsinyasi_lbg_1,Konsinyasi_stb_1,Konsinyasi_tki_1], ignore_index=True)
kns_bulan_2 = pd.concat([Konsinyasi_dkt_2,Konsinyasi_lbg_2,Konsinyasi_stb_2,Konsinyasi_tki_2], ignore_index=True)
kns_bulan_3 = pd.concat([Konsinyasi_dkt_3,Konsinyasi_lbg_3,Konsinyasi_stb_3,Konsinyasi_tki_3], ignore_index=True)

In [45]:
#create Df bulan 2
kns_merge_1 = pd.merge(kns_bulan_1,kns_bulan_2, how='outer' ,on=['Kode Barang'], indicator=True, suffixes=("_x", ""),)
kns_merge_1["_merge"].replace({"right_only": "right_only_first"}, inplace=True)
kns_merge_1_right = kns_merge_1.loc[kns_merge_1['_merge'] == 'right_only_first']
kns_merge_1_right = kns_merge_1_right.dropna(axis='columns')
kns_merge_concat_1 = pd.concat([kns_bulan_2,kns_merge_1_right])
kns_merge_concat_1['_merge'] = kns_merge_concat_1[['_merge']].fillna(value='both')
merge_drop = kns_merge_concat_1.drop_duplicates(subset=['Kode Barang'], keep='last')

#clean bahan df bulan 3
merge_drop_clean = merge_drop.iloc[:,0:23]

#create Df bulan 3
kns_merge_2 = pd.merge(merge_drop_clean,kns_bulan_3, how='outer' ,on=['Kode Barang'], indicator=True, suffixes=("_x", ""),)
kns_merge_2["_merge"].replace({"right_only": "right_only_second"}, inplace=True)
kns_merge_2_right = kns_merge_2.loc[kns_merge_2['_merge'] == 'right_only_second']
kns_merge_2_right = kns_merge_2_right.dropna(axis='columns')
kns_merge_concat_2 = pd.concat([kns_bulan_3,kns_merge_2_right])
kns_merge_concat_2['_merge'] = kns_merge_concat_2[['_merge']].fillna(value='both')
merge_drop_2 = kns_merge_concat_2.drop_duplicates(subset=['Kode Barang'], keep='last')

#finishing Df bulan 1
kns_bulan_1['_merge'] = 'both_first'

#merger all bulan
kns_all = pd.concat([kns_bulan_1,merge_drop,merge_drop_2],ignore_index=True)

# perhitungan stock bayangan 
# All both
kns_all.loc[kns_all['_merge'] == 'both_first', 'stock bayangan'] = kns_all['Stock Awal']+kns_all['Stock In']
kns_all.loc[kns_all['_merge'] == 'both', 'stock bayangan'] = kns_all['Stock In']
kns_all.loc[kns_all['_merge'] == 'both', 'stock bayangan'] = kns_all['Stock In']
# right only first
kns_all.loc[kns_all['_merge'] == 'right_only_first', 'stock bayangan'] = kns_all['Stock Awal']+kns_all['Stock In']
# right only second
kns_all.loc[kns_all['_merge'] == 'right_only_second', 'stock bayangan'] = kns_all['Stock Awal']+kns_all['Stock In']

In [46]:
#kns_all.to_csv(r'C:\Users\afriz\Documents\Pekerjaan\YENS\Monthly Project\Monthly Project\ready data set\Konsinyasi_testing_modeling_5.csv', index=False)

# Fashion Anak

In [47]:
Fashion_Anak_dkt_1 = pd.read_excel(r'C:\Users\afriz\Documents\Pekerjaan\YENS\Monthly Project\Monthly Project\Fashion Anak\Fashion_Anak_dkt_4.xlsx')
Fashion_Anak_dkt_2 = pd.read_excel(r'C:\Users\afriz\Documents\Pekerjaan\YENS\Monthly Project\Monthly Project\Fashion Anak\Fashion_Anak_dkt_5.xlsx')
Fashion_Anak_dkt_3 = pd.read_excel(r'C:\Users\afriz\Documents\Pekerjaan\YENS\Monthly Project\Monthly Project\Fashion Anak\Fashion_Anak_dkt_6.xlsx')

Fashion_Anak_lbg_1 = pd.read_excel(r'C:\Users\afriz\Documents\Pekerjaan\YENS\Monthly Project\Monthly Project\Fashion Anak\Fashion_Anak_lbg_4.xlsx')
Fashion_Anak_lbg_2 = pd.read_excel(r'C:\Users\afriz\Documents\Pekerjaan\YENS\Monthly Project\Monthly Project\Fashion Anak\Fashion_Anak_lbg_5.xlsx')
Fashion_Anak_lbg_3 = pd.read_excel(r'C:\Users\afriz\Documents\Pekerjaan\YENS\Monthly Project\Monthly Project\Fashion Anak\Fashion_Anak_lbg_6.xlsx')

Fashion_Anak_stb_1 = pd.read_excel(r'C:\Users\afriz\Documents\Pekerjaan\YENS\Monthly Project\Monthly Project\Fashion Anak\Fashion_Anak_stb_4.xlsx')
Fashion_Anak_stb_2 = pd.read_excel(r'C:\Users\afriz\Documents\Pekerjaan\YENS\Monthly Project\Monthly Project\Fashion Anak\Fashion_Anak_stb_5.xlsx')
Fashion_Anak_stb_3 = pd.read_excel(r'C:\Users\afriz\Documents\Pekerjaan\YENS\Monthly Project\Monthly Project\Fashion Anak\Fashion_Anak_stb_6.xlsx')

Fashion_Anak_tki_1 = pd.read_excel(r'C:\Users\afriz\Documents\Pekerjaan\YENS\Monthly Project\Monthly Project\Fashion Anak\Fashion_Anak_tki_4.xlsx')
Fashion_Anak_tki_2 = pd.read_excel(r'C:\Users\afriz\Documents\Pekerjaan\YENS\Monthly Project\Monthly Project\Fashion Anak\Fashion_Anak_tki_5.xlsx')
Fashion_Anak_tki_3 = pd.read_excel(r'C:\Users\afriz\Documents\Pekerjaan\YENS\Monthly Project\Monthly Project\Fashion Anak\Fashion_Anak_tki_6.xlsx')

In [48]:
Fashion_Anak_dkt_1.columns = Fashion_Anak_dkt_1.iloc[4]
Fashion_Anak_dkt_2.columns = Fashion_Anak_dkt_2.iloc[4]
Fashion_Anak_dkt_3.columns = Fashion_Anak_dkt_3.iloc[4]

Fashion_Anak_lbg_1.columns = Fashion_Anak_lbg_1.iloc[4]
Fashion_Anak_lbg_2.columns = Fashion_Anak_lbg_2.iloc[4]
Fashion_Anak_lbg_3.columns = Fashion_Anak_lbg_3.iloc[4]

Fashion_Anak_stb_1.columns = Fashion_Anak_stb_1.iloc[4]
Fashion_Anak_stb_2.columns = Fashion_Anak_stb_2.iloc[4]
Fashion_Anak_stb_3.columns = Fashion_Anak_stb_3.iloc[4]

Fashion_Anak_tki_1.columns = Fashion_Anak_tki_1.iloc[4]
Fashion_Anak_tki_2.columns = Fashion_Anak_tki_2.iloc[4]
Fashion_Anak_tki_3.columns = Fashion_Anak_tki_3.iloc[4]

In [49]:
Fashion_Anak_dkt_1 = Fashion_Anak_dkt_1.drop(Fashion_Anak_dkt_1.index[0:5])
Fashion_Anak_dkt_2 = Fashion_Anak_dkt_2.drop(Fashion_Anak_dkt_2.index[0:5])
Fashion_Anak_dkt_3 = Fashion_Anak_dkt_3.drop(Fashion_Anak_dkt_3.index[0:5])

Fashion_Anak_lbg_1 = Fashion_Anak_lbg_1.drop(Fashion_Anak_lbg_1.index[0:5])
Fashion_Anak_lbg_2 = Fashion_Anak_lbg_2.drop(Fashion_Anak_lbg_2.index[0:5])
Fashion_Anak_lbg_3 = Fashion_Anak_lbg_3.drop(Fashion_Anak_lbg_3.index[0:5])

Fashion_Anak_stb_1 = Fashion_Anak_stb_1.drop(Fashion_Anak_stb_1.index[0:5])
Fashion_Anak_stb_2 = Fashion_Anak_stb_2.drop(Fashion_Anak_stb_2.index[0:5])
Fashion_Anak_stb_3 = Fashion_Anak_stb_3.drop(Fashion_Anak_stb_3.index[0:5])

Fashion_Anak_tki_1 = Fashion_Anak_tki_1.drop(Fashion_Anak_tki_1.index[0:5])
Fashion_Anak_tki_2 = Fashion_Anak_tki_2.drop(Fashion_Anak_tki_2.index[0:5])
Fashion_Anak_tki_3 = Fashion_Anak_tki_3.drop(Fashion_Anak_tki_3.index[0:5])

In [50]:
Fashion_Anak_dkt_1 = Fashion_Anak_dkt_1[:-1]
Fashion_Anak_dkt_2 = Fashion_Anak_dkt_2[:-1]
Fashion_Anak_dkt_3 = Fashion_Anak_dkt_3[:-1]

Fashion_Anak_lbg_1 = Fashion_Anak_lbg_1[:-1]
Fashion_Anak_lbg_2 = Fashion_Anak_lbg_2[:-1]
Fashion_Anak_lbg_3 = Fashion_Anak_lbg_3[:-1]

Fashion_Anak_stb_1 = Fashion_Anak_stb_1[:-1]
Fashion_Anak_stb_2 = Fashion_Anak_stb_2[:-1]
Fashion_Anak_stb_3 = Fashion_Anak_stb_3[:-1]

Fashion_Anak_tki_1 = Fashion_Anak_tki_1[:-1]
Fashion_Anak_tki_2 = Fashion_Anak_tki_2[:-1]
Fashion_Anak_tki_3 = Fashion_Anak_tki_3[:-1]

In [51]:
Fashion_Anak_dkt_1['cabang'] = 'dkt'
Fashion_Anak_dkt_2['cabang'] = 'dkt'
Fashion_Anak_dkt_3['cabang'] = 'dkt'

Fashion_Anak_lbg_1['cabang'] = 'lbg'
Fashion_Anak_lbg_2['cabang'] = 'lbg'
Fashion_Anak_lbg_3['cabang'] = 'lbg'

Fashion_Anak_stb_1['cabang'] = 'stb'
Fashion_Anak_stb_2['cabang'] = 'stb'
Fashion_Anak_stb_3['cabang'] = 'stb'

Fashion_Anak_tki_1['cabang'] = 'tki'
Fashion_Anak_tki_2['cabang'] = 'tki'
Fashion_Anak_tki_3['cabang'] = 'tki'

In [52]:
Fashion_Anak_dkt_1['bulan'] = '4'
Fashion_Anak_dkt_2['bulan'] = '5'
Fashion_Anak_dkt_3['bulan'] = '6'

Fashion_Anak_lbg_1['bulan'] = '4'
Fashion_Anak_lbg_2['bulan'] = '5'
Fashion_Anak_lbg_3['bulan'] = '6'

Fashion_Anak_stb_1['bulan'] = '4'
Fashion_Anak_stb_2['bulan'] = '5'
Fashion_Anak_stb_3['bulan'] = '6'

Fashion_Anak_tki_1['bulan'] = '4'
Fashion_Anak_tki_2['bulan'] = '5'
Fashion_Anak_tki_3['bulan'] = '6'

In [53]:
fa_bulan_1 = pd.concat([Fashion_Anak_dkt_1,Fashion_Anak_lbg_1,Fashion_Anak_stb_1,Fashion_Anak_tki_1], ignore_index=True)
fa_bulan_2 = pd.concat([Fashion_Anak_dkt_2,Fashion_Anak_lbg_2,Fashion_Anak_stb_2,Fashion_Anak_tki_2], ignore_index=True)
fa_bulan_3 = pd.concat([Fashion_Anak_dkt_3,Fashion_Anak_lbg_3,Fashion_Anak_stb_3,Fashion_Anak_tki_3], ignore_index=True)

In [54]:
#create Df bulan 2
fa_merge_1 = pd.merge(fa_bulan_1,fa_bulan_2, how='outer' ,on=['Kode Barang'], indicator=True, suffixes=("_x", ""),)
fa_merge_1["_merge"].replace({"right_only": "right_only_first"}, inplace=True)
fa_merge_1_right = fa_merge_1.loc[fa_merge_1['_merge'] == 'right_only_first']
fa_merge_1_right = fa_merge_1_right.dropna(axis='columns')
fa_merge_concat_1 = pd.concat([fa_bulan_2,fa_merge_1_right])
fa_merge_concat_1['_merge'] = fa_merge_concat_1[['_merge']].fillna(value='both')
merge_drop = fa_merge_concat_1.drop_duplicates(subset=['Kode Barang'], keep='last')

#clean bahan df bulan 3
merge_drop_clean = merge_drop.iloc[:,0:23]

#create Df bulan 3
fa_merge_2 = pd.merge(merge_drop_clean,fa_bulan_3, how='outer' ,on=['Kode Barang'], indicator=True, suffixes=("_x", ""),)
fa_merge_2["_merge"].replace({"right_only": "right_only_second"}, inplace=True)
fa_merge_2_right = fa_merge_2.loc[fa_merge_2['_merge'] == 'right_only_second']
fa_merge_2_right = fa_merge_2_right.dropna(axis='columns')
fa_merge_concat_2 = pd.concat([fa_bulan_3,fa_merge_2_right])
fa_merge_concat_2['_merge'] = fa_merge_concat_2[['_merge']].fillna(value='both')
merge_drop_2 = fa_merge_concat_2.drop_duplicates(subset=['Kode Barang'], keep='last')

#finishing Df bulan 1
fa_bulan_1['_merge'] = 'both_first'

#merger all bulan
fa_all = pd.concat([fa_bulan_1,merge_drop,merge_drop_2],ignore_index=True)

# perhitungan stock bayangan 
# All both
fa_all.loc[fa_all['_merge'] == 'both_first', 'stock bayangan'] = fa_all['Stock Awal']+fa_all['Stock In']
fa_all.loc[fa_all['_merge'] == 'both', 'stock bayangan'] = fa_all['Stock In']
fa_all.loc[fa_all['_merge'] == 'both', 'stock bayangan'] = fa_all['Stock In']
# right only first
fa_all.loc[fa_all['_merge'] == 'right_only_first', 'stock bayangan'] = fa_all['Stock Awal']+fa_all['Stock In']
# right only second
fa_all.loc[fa_all['_merge'] == 'right_only_second', 'stock bayangan'] = fa_all['Stock Awal']+fa_all['Stock In']

In [55]:
#fa_all.to_csv(r'C:\Users\afriz\Documents\Pekerjaan\YENS\Monthly Project\Monthly Project\ready data set\fashion_Anak_testing_modeling_5.csv', index=False)

# Fashion Baby

In [56]:
Fashion_Baby_dkt_1 = pd.read_excel(r'C:\Users\afriz\Documents\Pekerjaan\YENS\Monthly Project\Monthly Project\Fashion Baby\Fashion_Baby_dkt_4.xlsx')
Fashion_Baby_dkt_2 = pd.read_excel(r'C:\Users\afriz\Documents\Pekerjaan\YENS\Monthly Project\Monthly Project\Fashion Baby\Fashion_Baby_dkt_5.xlsx')
Fashion_Baby_dkt_3 = pd.read_excel(r'C:\Users\afriz\Documents\Pekerjaan\YENS\Monthly Project\Monthly Project\Fashion Baby\Fashion_Baby_dkt_6.xlsx')

Fashion_Baby_lbg_1 = pd.read_excel(r'C:\Users\afriz\Documents\Pekerjaan\YENS\Monthly Project\Monthly Project\Fashion Baby\Fashion_Baby_lbg_4.xlsx')
Fashion_Baby_lbg_2 = pd.read_excel(r'C:\Users\afriz\Documents\Pekerjaan\YENS\Monthly Project\Monthly Project\Fashion Baby\Fashion_Baby_lbg_5.xlsx')
Fashion_Baby_lbg_3 = pd.read_excel(r'C:\Users\afriz\Documents\Pekerjaan\YENS\Monthly Project\Monthly Project\Fashion Baby\Fashion_Baby_lbg_6.xlsx')

Fashion_Baby_stb_1 = pd.read_excel(r'C:\Users\afriz\Documents\Pekerjaan\YENS\Monthly Project\Monthly Project\Fashion Baby\Fashion_Baby_stb_4.xlsx')
Fashion_Baby_stb_2 = pd.read_excel(r'C:\Users\afriz\Documents\Pekerjaan\YENS\Monthly Project\Monthly Project\Fashion Baby\Fashion_Baby_stb_5.xlsx')
Fashion_Baby_stb_3 = pd.read_excel(r'C:\Users\afriz\Documents\Pekerjaan\YENS\Monthly Project\Monthly Project\Fashion Baby\Fashion_Baby_stb_6.xlsx')

Fashion_Baby_tki_1 = pd.read_excel(r'C:\Users\afriz\Documents\Pekerjaan\YENS\Monthly Project\Monthly Project\Fashion Baby\Fashion_Baby_tki_4.xlsx')
Fashion_Baby_tki_2 = pd.read_excel(r'C:\Users\afriz\Documents\Pekerjaan\YENS\Monthly Project\Monthly Project\Fashion Baby\Fashion_Baby_tki_5.xlsx')
Fashion_Baby_tki_3 = pd.read_excel(r'C:\Users\afriz\Documents\Pekerjaan\YENS\Monthly Project\Monthly Project\Fashion Baby\Fashion_Baby_tki_6.xlsx')

In [57]:
Fashion_Baby_dkt_1.columns = Fashion_Baby_dkt_1.iloc[4]
Fashion_Baby_dkt_2.columns = Fashion_Baby_dkt_2.iloc[4]
Fashion_Baby_dkt_3.columns = Fashion_Baby_dkt_3.iloc[4]

Fashion_Baby_lbg_1.columns = Fashion_Baby_lbg_1.iloc[4]
Fashion_Baby_lbg_2.columns = Fashion_Baby_lbg_2.iloc[4]
Fashion_Baby_lbg_3.columns = Fashion_Baby_lbg_3.iloc[4]

Fashion_Baby_stb_1.columns = Fashion_Baby_stb_1.iloc[4]
Fashion_Baby_stb_2.columns = Fashion_Baby_stb_2.iloc[4]
Fashion_Baby_stb_3.columns = Fashion_Baby_stb_3.iloc[4]

Fashion_Baby_tki_1.columns = Fashion_Baby_tki_1.iloc[4]
Fashion_Baby_tki_2.columns = Fashion_Baby_tki_2.iloc[4]
Fashion_Baby_tki_3.columns = Fashion_Baby_tki_3.iloc[4]

In [58]:
Fashion_Baby_dkt_1 = Fashion_Baby_dkt_1.drop(Fashion_Baby_dkt_1.index[0:5])
Fashion_Baby_dkt_2 = Fashion_Baby_dkt_2.drop(Fashion_Baby_dkt_2.index[0:5])
Fashion_Baby_dkt_3 = Fashion_Baby_dkt_3.drop(Fashion_Baby_dkt_3.index[0:5])

Fashion_Baby_lbg_1 = Fashion_Baby_lbg_1.drop(Fashion_Baby_lbg_1.index[0:5])
Fashion_Baby_lbg_2 = Fashion_Baby_lbg_2.drop(Fashion_Baby_lbg_2.index[0:5])
Fashion_Baby_lbg_3 = Fashion_Baby_lbg_3.drop(Fashion_Baby_lbg_3.index[0:5])

Fashion_Baby_stb_1 = Fashion_Baby_stb_1.drop(Fashion_Baby_stb_1.index[0:5])
Fashion_Baby_stb_2 = Fashion_Baby_stb_2.drop(Fashion_Baby_stb_2.index[0:5])
Fashion_Baby_stb_3 = Fashion_Baby_stb_3.drop(Fashion_Baby_stb_3.index[0:5])

Fashion_Baby_tki_1 = Fashion_Baby_tki_1.drop(Fashion_Baby_tki_1.index[0:5])
Fashion_Baby_tki_2 = Fashion_Baby_tki_2.drop(Fashion_Baby_tki_2.index[0:5])
Fashion_Baby_tki_3 = Fashion_Baby_tki_3.drop(Fashion_Baby_tki_3.index[0:5])

In [59]:
Fashion_Baby_dkt_1 = Fashion_Baby_dkt_1[:-1]
Fashion_Baby_dkt_2 = Fashion_Baby_dkt_2[:-1]
Fashion_Baby_dkt_3 = Fashion_Baby_dkt_3[:-1]

Fashion_Baby_lbg_1 = Fashion_Baby_lbg_1[:-1]
Fashion_Baby_lbg_2 = Fashion_Baby_lbg_2[:-1]
Fashion_Baby_lbg_3 = Fashion_Baby_lbg_3[:-1]

Fashion_Baby_stb_1 = Fashion_Baby_stb_1[:-1]
Fashion_Baby_stb_2 = Fashion_Baby_stb_2[:-1]
Fashion_Baby_stb_3 = Fashion_Baby_stb_3[:-1]

Fashion_Baby_tki_1 = Fashion_Baby_tki_1[:-1]
Fashion_Baby_tki_2 = Fashion_Baby_tki_2[:-1]
Fashion_Baby_tki_3 = Fashion_Baby_tki_3[:-1]

In [60]:
Fashion_Baby_dkt_1['cabang'] = 'dkt'
Fashion_Baby_dkt_2['cabang'] = 'dkt'
Fashion_Baby_dkt_3['cabang'] = 'dkt'

Fashion_Baby_lbg_1['cabang'] = 'lbg'
Fashion_Baby_lbg_2['cabang'] = 'lbg'
Fashion_Baby_lbg_3['cabang'] = 'lbg'

Fashion_Baby_stb_1['cabang'] = 'stb'
Fashion_Baby_stb_2['cabang'] = 'stb'
Fashion_Baby_stb_3['cabang'] = 'stb'

Fashion_Baby_tki_1['cabang'] = 'tki'
Fashion_Baby_tki_2['cabang'] = 'tki'
Fashion_Baby_tki_3['cabang'] = 'tki'

In [61]:
Fashion_Baby_dkt_1['bulan'] = '4'
Fashion_Baby_dkt_2['bulan'] = '5'
Fashion_Baby_dkt_3['bulan'] = '6'

Fashion_Baby_lbg_1['bulan'] = '4'
Fashion_Baby_lbg_2['bulan'] = '5'
Fashion_Baby_lbg_3['bulan'] = '6'

Fashion_Baby_stb_1['bulan'] = '4'
Fashion_Baby_stb_2['bulan'] = '5'
Fashion_Baby_stb_3['bulan'] = '6'

Fashion_Baby_tki_1['bulan'] = '4'
Fashion_Baby_tki_2['bulan'] = '5'
Fashion_Baby_tki_3['bulan'] = '6'

In [62]:
fb_bulan_1 = pd.concat([Fashion_Baby_dkt_1,Fashion_Baby_lbg_1,Fashion_Baby_stb_1,Fashion_Baby_tki_1], ignore_index=True)
fb_bulan_2 = pd.concat([Fashion_Baby_dkt_2,Fashion_Baby_lbg_2,Fashion_Baby_stb_2,Fashion_Baby_tki_2], ignore_index=True)
fb_bulan_3 = pd.concat([Fashion_Baby_dkt_3,Fashion_Baby_lbg_3,Fashion_Baby_stb_3,Fashion_Baby_tki_3], ignore_index=True)

In [63]:
#create Df bulan 2
fb_merge_1 = pd.merge(fb_bulan_1,fb_bulan_2, how='outer' ,on=['Kode Barang'], indicator=True, suffixes=("_x", ""),)
fb_merge_1["_merge"].replace({"right_only": "right_only_first"}, inplace=True)
fb_merge_1_right = fb_merge_1.loc[fb_merge_1['_merge'] == 'right_only_first']
fb_merge_1_right = fb_merge_1_right.dropna(axis='columns')
fb_merge_concat_1 = pd.concat([fb_bulan_2,fb_merge_1_right])
fb_merge_concat_1['_merge'] = fb_merge_concat_1[['_merge']].fillna(value='both')
merge_drop = fb_merge_concat_1.drop_duplicates(subset=['Kode Barang'], keep='last')

#clean bahan df bulan 3
merge_drop_clean = merge_drop.iloc[:,0:23]

#create Df bulan 3
fb_merge_2 = pd.merge(merge_drop_clean,fb_bulan_3, how='outer' ,on=['Kode Barang'], indicator=True, suffixes=("_x", ""),)
fb_merge_2["_merge"].replace({"right_only": "right_only_second"}, inplace=True)
fb_merge_2_right = fb_merge_2.loc[fb_merge_2['_merge'] == 'right_only_second']
fb_merge_2_right = fb_merge_2_right.dropna(axis='columns')
fb_merge_concat_2 = pd.concat([fb_bulan_3,fb_merge_2_right])
fb_merge_concat_2['_merge'] = fb_merge_concat_2[['_merge']].fillna(value='both')
merge_drop_2 = fb_merge_concat_2.drop_duplicates(subset=['Kode Barang'], keep='last')

#finishing Df bulan 1
fb_bulan_1['_merge'] = 'both_first'

#merger all bulan
fb_all = pd.concat([fb_bulan_1,merge_drop,merge_drop_2],ignore_index=True)

# perhitungan stock bayangan 
# All both
fb_all.loc[fb_all['_merge'] == 'both_first', 'stock bayangan'] = fb_all['Stock Awal']+fb_all['Stock In']
fb_all.loc[fb_all['_merge'] == 'both', 'stock bayangan'] = fb_all['Stock In']
fb_all.loc[fb_all['_merge'] == 'both', 'stock bayangan'] = fb_all['Stock In']
# right only first
fb_all.loc[fb_all['_merge'] == 'right_only_first', 'stock bayangan'] = fb_all['Stock Awal']+fb_all['Stock In']
# right only second
fb_all.loc[fb_all['_merge'] == 'right_only_second', 'stock bayangan'] = fb_all['Stock Awal']+fb_all['Stock In']

In [64]:
#fb_all.to_csv(r'C:\Users\afriz\Documents\Pekerjaan\YENS\Monthly Project\Monthly Project\ready data set\Fashion_Baby_testing_modeling_5.csv', index=False)

# Fashion Dewasa

In [65]:
Fashion_Dewasa_dkt_1 = pd.read_excel(r'C:\Users\afriz\Documents\Pekerjaan\YENS\Monthly Project\Monthly Project\Fashion Dewasa\Fashion_Dewasa_dkt_4.xlsx')
Fashion_Dewasa_dkt_2 = pd.read_excel(r'C:\Users\afriz\Documents\Pekerjaan\YENS\Monthly Project\Monthly Project\Fashion Dewasa\Fashion_Dewasa_dkt_5.xlsx')
Fashion_Dewasa_dkt_3 = pd.read_excel(r'C:\Users\afriz\Documents\Pekerjaan\YENS\Monthly Project\Monthly Project\Fashion Dewasa\Fashion_Dewasa_dkt_6.xlsx')

Fashion_Dewasa_lbg_1 = pd.read_excel(r'C:\Users\afriz\Documents\Pekerjaan\YENS\Monthly Project\Monthly Project\Fashion Dewasa\Fashion_Dewasa_lbg_4.xlsx')
Fashion_Dewasa_lbg_2 = pd.read_excel(r'C:\Users\afriz\Documents\Pekerjaan\YENS\Monthly Project\Monthly Project\Fashion Dewasa\Fashion_Dewasa_lbg_5.xlsx')
Fashion_Dewasa_lbg_3 = pd.read_excel(r'C:\Users\afriz\Documents\Pekerjaan\YENS\Monthly Project\Monthly Project\Fashion Dewasa\Fashion_Dewasa_lbg_6.xlsx')

Fashion_Dewasa_stb_1 = pd.read_excel(r'C:\Users\afriz\Documents\Pekerjaan\YENS\Monthly Project\Monthly Project\Fashion Dewasa\Fashion_Dewasa_stb_4.xlsx')
Fashion_Dewasa_stb_2 = pd.read_excel(r'C:\Users\afriz\Documents\Pekerjaan\YENS\Monthly Project\Monthly Project\Fashion Dewasa\Fashion_Dewasa_stb_5.xlsx')
Fashion_Dewasa_stb_3 = pd.read_excel(r'C:\Users\afriz\Documents\Pekerjaan\YENS\Monthly Project\Monthly Project\Fashion Dewasa\Fashion_Dewasa_stb_6.xlsx')

Fashion_Dewasa_tki_1 = pd.read_excel(r'C:\Users\afriz\Documents\Pekerjaan\YENS\Monthly Project\Monthly Project\Fashion Dewasa\Fashion_Dewasa_tki_4.xlsx')
Fashion_Dewasa_tki_2 = pd.read_excel(r'C:\Users\afriz\Documents\Pekerjaan\YENS\Monthly Project\Monthly Project\Fashion Dewasa\Fashion_Dewasa_tki_5.xlsx')
Fashion_Dewasa_tki_3 = pd.read_excel(r'C:\Users\afriz\Documents\Pekerjaan\YENS\Monthly Project\Monthly Project\Fashion Dewasa\Fashion_Dewasa_tki_6.xlsx')

In [66]:
Fashion_Dewasa_dkt_1.columns = Fashion_Dewasa_dkt_1.iloc[4]
Fashion_Dewasa_dkt_2.columns = Fashion_Dewasa_dkt_2.iloc[4]
Fashion_Dewasa_dkt_3.columns = Fashion_Dewasa_dkt_3.iloc[4]

Fashion_Dewasa_lbg_1.columns = Fashion_Dewasa_lbg_1.iloc[4]
Fashion_Dewasa_lbg_2.columns = Fashion_Dewasa_lbg_2.iloc[4]
Fashion_Dewasa_lbg_3.columns = Fashion_Dewasa_lbg_3.iloc[4]

Fashion_Dewasa_stb_1.columns = Fashion_Dewasa_stb_1.iloc[4]
Fashion_Dewasa_stb_2.columns = Fashion_Dewasa_stb_2.iloc[4]
Fashion_Dewasa_stb_3.columns = Fashion_Dewasa_stb_3.iloc[4]

Fashion_Dewasa_tki_1.columns = Fashion_Dewasa_tki_1.iloc[4]
Fashion_Dewasa_tki_2.columns = Fashion_Dewasa_tki_2.iloc[4]
Fashion_Dewasa_tki_3.columns = Fashion_Dewasa_tki_3.iloc[4]

In [67]:
Fashion_Dewasa_dkt_1 = Fashion_Dewasa_dkt_1.drop(Fashion_Dewasa_dkt_1.index[0:5])
Fashion_Dewasa_dkt_2 = Fashion_Dewasa_dkt_2.drop(Fashion_Dewasa_dkt_2.index[0:5])
Fashion_Dewasa_dkt_3 = Fashion_Dewasa_dkt_3.drop(Fashion_Dewasa_dkt_3.index[0:5])

Fashion_Dewasa_lbg_1 = Fashion_Dewasa_lbg_1.drop(Fashion_Dewasa_lbg_1.index[0:5])
Fashion_Dewasa_lbg_2 = Fashion_Dewasa_lbg_2.drop(Fashion_Dewasa_lbg_2.index[0:5])
Fashion_Dewasa_lbg_3 = Fashion_Dewasa_lbg_3.drop(Fashion_Dewasa_lbg_3.index[0:5])

Fashion_Dewasa_stb_1 = Fashion_Dewasa_stb_1.drop(Fashion_Dewasa_stb_1.index[0:5])
Fashion_Dewasa_stb_2 = Fashion_Dewasa_stb_2.drop(Fashion_Dewasa_stb_2.index[0:5])
Fashion_Dewasa_stb_3 = Fashion_Dewasa_stb_3.drop(Fashion_Dewasa_stb_3.index[0:5])

Fashion_Dewasa_tki_1 = Fashion_Dewasa_tki_1.drop(Fashion_Dewasa_tki_1.index[0:5])
Fashion_Dewasa_tki_2 = Fashion_Dewasa_tki_2.drop(Fashion_Dewasa_tki_2.index[0:5])
Fashion_Dewasa_tki_3 = Fashion_Dewasa_tki_3.drop(Fashion_Dewasa_tki_3.index[0:5])

In [68]:
Fashion_Dewasa_dkt_1 = Fashion_Dewasa_dkt_1[:-1]
Fashion_Dewasa_dkt_2 = Fashion_Dewasa_dkt_2[:-1]
Fashion_Dewasa_dkt_3 = Fashion_Dewasa_dkt_3[:-1]

Fashion_Dewasa_lbg_1 = Fashion_Dewasa_lbg_1[:-1]
Fashion_Dewasa_lbg_2 = Fashion_Dewasa_lbg_2[:-1]
Fashion_Dewasa_lbg_3 = Fashion_Dewasa_lbg_3[:-1]

Fashion_Dewasa_stb_1 = Fashion_Dewasa_stb_1[:-1]
Fashion_Dewasa_stb_2 = Fashion_Dewasa_stb_2[:-1]
Fashion_Dewasa_stb_3 = Fashion_Dewasa_stb_3[:-1]

Fashion_Dewasa_tki_1 = Fashion_Dewasa_tki_1[:-1]
Fashion_Dewasa_tki_2 = Fashion_Dewasa_tki_2[:-1]
Fashion_Dewasa_tki_3 = Fashion_Dewasa_tki_3[:-1]

In [69]:
Fashion_Dewasa_dkt_1['cabang'] = 'dkt'
Fashion_Dewasa_dkt_2['cabang'] = 'dkt'
Fashion_Dewasa_dkt_3['cabang'] = 'dkt'

Fashion_Dewasa_lbg_1['cabang'] = 'lbg'
Fashion_Dewasa_lbg_2['cabang'] = 'lbg'
Fashion_Dewasa_lbg_3['cabang'] = 'lbg'

Fashion_Dewasa_stb_1['cabang'] = 'stb'
Fashion_Dewasa_stb_2['cabang'] = 'stb'
Fashion_Dewasa_stb_3['cabang'] = 'stb'

Fashion_Dewasa_tki_1['cabang'] = 'tki'
Fashion_Dewasa_tki_2['cabang'] = 'tki'
Fashion_Dewasa_tki_3['cabang'] = 'tki'

In [70]:
Fashion_Dewasa_dkt_1['bulan'] = '4'
Fashion_Dewasa_dkt_2['bulan'] = '5'
Fashion_Dewasa_dkt_3['bulan'] = '6'

Fashion_Dewasa_lbg_1['bulan'] = '4'
Fashion_Dewasa_lbg_2['bulan'] = '5'
Fashion_Dewasa_lbg_3['bulan'] = '6'

Fashion_Dewasa_stb_1['bulan'] = '4'
Fashion_Dewasa_stb_2['bulan'] = '5'
Fashion_Dewasa_stb_3['bulan'] = '6'

Fashion_Dewasa_tki_1['bulan'] = '4'
Fashion_Dewasa_tki_2['bulan'] = '5'
Fashion_Dewasa_tki_3['bulan'] = '6'

In [71]:
fd_bulan_1 = pd.concat([Fashion_Dewasa_dkt_1,Fashion_Dewasa_lbg_1,Fashion_Dewasa_stb_1,Fashion_Dewasa_tki_1], ignore_index=True)
fd_bulan_2 = pd.concat([Fashion_Dewasa_dkt_2,Fashion_Dewasa_lbg_2,Fashion_Dewasa_stb_2,Fashion_Dewasa_tki_2], ignore_index=True)
fd_bulan_3 = pd.concat([Fashion_Dewasa_dkt_3,Fashion_Dewasa_lbg_3,Fashion_Dewasa_stb_3,Fashion_Dewasa_tki_3], ignore_index=True)

In [72]:
#create Df bulan 2
fd_merge_1 = pd.merge(fd_bulan_1,fd_bulan_2, how='outer' ,on=['Kode Barang'], indicator=True, suffixes=("_x", ""),)
fd_merge_1["_merge"].replace({"right_only": "right_only_first"}, inplace=True)
fd_merge_1_right = fd_merge_1.loc[fd_merge_1['_merge'] == 'right_only_first']
fd_merge_1_right = fd_merge_1_right.dropna(axis='columns')
fd_merge_concat_1 = pd.concat([fd_bulan_2,fd_merge_1_right])
fd_merge_concat_1['_merge'] = fd_merge_concat_1[['_merge']].fillna(value='both')
merge_drop = fd_merge_concat_1.drop_duplicates(subset=['Kode Barang'], keep='last')

#clean bahan df bulan 3
merge_drop_clean = merge_drop.iloc[:,0:23]

#create Df bulan 3
fd_merge_2 = pd.merge(merge_drop_clean,fd_bulan_3, how='outer' ,on=['Kode Barang'], indicator=True, suffixes=("_x", ""),)
fd_merge_2["_merge"].replace({"right_only": "right_only_second"}, inplace=True)
fd_merge_2_right = fd_merge_2.loc[fd_merge_2['_merge'] == 'right_only_second']
fd_merge_2_right = fd_merge_2_right.dropna(axis='columns')
fd_merge_concat_2 = pd.concat([fd_bulan_3,fd_merge_2_right])
fd_merge_concat_2['_merge'] = fd_merge_concat_2[['_merge']].fillna(value='both')
merge_drop_2 = fd_merge_concat_2.drop_duplicates(subset=['Kode Barang'], keep='last')

#finishing Df bulan 1
fd_bulan_1['_merge'] = 'both_first'

#merger all bulan
fd_all = pd.concat([fd_bulan_1,merge_drop,merge_drop_2],ignore_index=True)

# perhitungan stock bayangan 
# All both
fd_all.loc[fd_all['_merge'] == 'both_first', 'stock bayangan'] = fd_all['Stock Awal']+fd_all['Stock In']
fd_all.loc[fd_all['_merge'] == 'both', 'stock bayangan'] = fd_all['Stock In']
fd_all.loc[fd_all['_merge'] == 'both', 'stock bayangan'] = fd_all['Stock In']
# right only first
fd_all.loc[fd_all['_merge'] == 'right_only_first', 'stock bayangan'] = fd_all['Stock Awal']+fd_all['Stock In']
# right only second
fd_all.loc[fd_all['_merge'] == 'right_only_second', 'stock bayangan'] = fd_all['Stock Awal']+fd_all['Stock In']

In [73]:
#fd_all.to_csv(r'C:\Users\afriz\Documents\Pekerjaan\YENS\Monthly Project\Monthly Project\ready data set\Fashion_Dewasa_testing_modeling_5.csv', index=False)

# Accesories

In [74]:
Accesories_dkt_1 = pd.read_excel(r'C:\Users\afriz\Documents\Pekerjaan\YENS\Monthly Project\Monthly Project\Accesories\Accesories_dkt_22_4.xlsx')
Accesories_dkt_2 = pd.read_excel(r'C:\Users\afriz\Documents\Pekerjaan\YENS\Monthly Project\Monthly Project\Accesories\Accesories_dkt_22_5.xlsx')
Accesories_dkt_3 = pd.read_excel(r'C:\Users\afriz\Documents\Pekerjaan\YENS\Monthly Project\Monthly Project\Accesories\Accesories_dkt_22_6.xlsx')

Accesories_lbg_1 = pd.read_excel(r'C:\Users\afriz\Documents\Pekerjaan\YENS\Monthly Project\Monthly Project\Accesories\Accesories_lbg_22_4.xlsx')
Accesories_lbg_2 = pd.read_excel(r'C:\Users\afriz\Documents\Pekerjaan\YENS\Monthly Project\Monthly Project\Accesories\Accesories_lbg_22_5.xlsx')
Accesories_lbg_3 = pd.read_excel(r'C:\Users\afriz\Documents\Pekerjaan\YENS\Monthly Project\Monthly Project\Accesories\Accesories_lbg_22_6.xlsx')

Accesories_stb_1 = pd.read_excel(r'C:\Users\afriz\Documents\Pekerjaan\YENS\Monthly Project\Monthly Project\Accesories\Accesories_stb_22_4.xlsx')
Accesories_stb_2 = pd.read_excel(r'C:\Users\afriz\Documents\Pekerjaan\YENS\Monthly Project\Monthly Project\Accesories\Accesories_stb_22_5.xlsx')
Accesories_stb_3 = pd.read_excel(r'C:\Users\afriz\Documents\Pekerjaan\YENS\Monthly Project\Monthly Project\Accesories\Accesories_stb_22_6.xlsx')

Accesories_tki_1 = pd.read_excel(r'C:\Users\afriz\Documents\Pekerjaan\YENS\Monthly Project\Monthly Project\Accesories\Accesories_tki_22_4.xlsx')
Accesories_tki_2 = pd.read_excel(r'C:\Users\afriz\Documents\Pekerjaan\YENS\Monthly Project\Monthly Project\Accesories\Accesories_tki_22_5.xlsx')
Accesories_tki_3 = pd.read_excel(r'C:\Users\afriz\Documents\Pekerjaan\YENS\Monthly Project\Monthly Project\Accesories\Accesories_tki_22_6.xlsx')

In [75]:
Accesories_dkt_1.columns = Accesories_dkt_1.iloc[4]
Accesories_dkt_2.columns = Accesories_dkt_2.iloc[4]
Accesories_dkt_3.columns = Accesories_dkt_3.iloc[4]

Accesories_lbg_1.columns = Accesories_lbg_1.iloc[4]
Accesories_lbg_2.columns = Accesories_lbg_2.iloc[4]
Accesories_lbg_3.columns = Accesories_lbg_3.iloc[4]

Accesories_stb_1.columns = Accesories_stb_1.iloc[4]
Accesories_stb_2.columns = Accesories_stb_2.iloc[4]
Accesories_stb_3.columns = Accesories_stb_3.iloc[4]

Accesories_tki_1.columns = Accesories_tki_1.iloc[4]
Accesories_tki_2.columns = Accesories_tki_2.iloc[4]
Accesories_tki_3.columns = Accesories_tki_3.iloc[4]

In [76]:
Accesories_dkt_1 = Accesories_dkt_1.drop(Accesories_dkt_1.index[0:5])
Accesories_dkt_2 = Accesories_dkt_2.drop(Accesories_dkt_2.index[0:5])
Accesories_dkt_3 = Accesories_dkt_3.drop(Accesories_dkt_3.index[0:5])

Accesories_lbg_1 = Accesories_lbg_1.drop(Accesories_lbg_1.index[0:5])
Accesories_lbg_2 = Accesories_lbg_2.drop(Accesories_lbg_2.index[0:5])
Accesories_lbg_3 = Accesories_lbg_3.drop(Accesories_lbg_3.index[0:5])

Accesories_stb_1 = Accesories_stb_1.drop(Accesories_stb_1.index[0:5])
Accesories_stb_2 = Accesories_stb_2.drop(Accesories_stb_2.index[0:5])
Accesories_stb_3 = Accesories_stb_3.drop(Accesories_stb_3.index[0:5])

Accesories_tki_1 = Accesories_tki_1.drop(Accesories_tki_1.index[0:5])
Accesories_tki_2 = Accesories_tki_2.drop(Accesories_tki_2.index[0:5])
Accesories_tki_3 = Accesories_tki_3.drop(Accesories_tki_3.index[0:5])

In [77]:
Accesories_dkt_1 = Accesories_dkt_1[:-1]
Accesories_dkt_2 = Accesories_dkt_2[:-1]
Accesories_dkt_3 = Accesories_dkt_3[:-1]

Accesories_lbg_1 = Accesories_lbg_1[:-1]
Accesories_lbg_2 = Accesories_lbg_2[:-1]
Accesories_lbg_3 = Accesories_lbg_3[:-1]

Accesories_stb_1 = Accesories_stb_1[:-1]
Accesories_stb_2 = Accesories_stb_2[:-1]
Accesories_stb_3 = Accesories_stb_3[:-1]

Accesories_tki_1 = Accesories_tki_1[:-1]
Accesories_tki_2 = Accesories_tki_2[:-1]
Accesories_tki_3 = Accesories_tki_3[:-1]

In [78]:
Accesories_dkt_1['cabang'] = 'dkt'
Accesories_dkt_2['cabang'] = 'dkt'
Accesories_dkt_3['cabang'] = 'dkt'

Accesories_lbg_1['cabang'] = 'lbg'
Accesories_lbg_2['cabang'] = 'lbg'
Accesories_lbg_3['cabang'] = 'lbg'

Accesories_stb_1['cabang'] = 'stb'
Accesories_stb_2['cabang'] = 'stb'
Accesories_stb_3['cabang'] = 'stb'

Accesories_tki_1['cabang'] = 'tki'
Accesories_tki_2['cabang'] = 'tki'
Accesories_tki_3['cabang'] = 'tki'

In [79]:
Accesories_dkt_1['bulan'] = '4'
Accesories_dkt_2['bulan'] = '5'
Accesories_dkt_3['bulan'] = '6'

Accesories_lbg_1['bulan'] = '4'
Accesories_lbg_2['bulan'] = '5'
Accesories_lbg_3['bulan'] = '6'

Accesories_stb_1['bulan'] = '4'
Accesories_stb_2['bulan'] = '5'
Accesories_stb_3['bulan'] = '6'

Accesories_tki_1['bulan'] = '4'
Accesories_tki_2['bulan'] = '5'
Accesories_tki_3['bulan'] = '6'

In [80]:
acc_bulan_1 = pd.concat([Accesories_dkt_1,Accesories_lbg_1,Accesories_stb_1,Accesories_tki_1], ignore_index=True)
acc_bulan_2 = pd.concat([Accesories_dkt_2,Accesories_lbg_2,Accesories_stb_2,Accesories_tki_2], ignore_index=True)
acc_bulan_3 = pd.concat([Accesories_dkt_3,Accesories_lbg_3,Accesories_stb_3,Accesories_tki_3], ignore_index=True)

In [81]:
#create Df bulan 2
acc_merge_1 = pd.merge(acc_bulan_1,acc_bulan_2, how='outer' ,on=['Kode Barang'], indicator=True, suffixes=("_x", ""),)
acc_merge_1["_merge"].replace({"right_only": "right_only_first"}, inplace=True)
acc_merge_1_right = acc_merge_1.loc[acc_merge_1['_merge'] == 'right_only_first']
acc_merge_1_right = acc_merge_1_right.dropna(axis='columns')
acc_merge_concat_1 = pd.concat([acc_bulan_2,acc_merge_1_right])
acc_merge_concat_1['_merge'] = acc_merge_concat_1[['_merge']].fillna(value='both')
merge_drop = acc_merge_concat_1.drop_duplicates(subset=['Kode Barang'], keep='last')

#clean bahan df bulan 3
merge_drop_clean = merge_drop.iloc[:,0:23]

#create Df bulan 3
acc_merge_2 = pd.merge(merge_drop_clean,acc_bulan_3, how='outer' ,on=['Kode Barang'], indicator=True, suffixes=("_x", ""),)
acc_merge_2["_merge"].replace({"right_only": "right_only_second"}, inplace=True)
acc_merge_2_right = acc_merge_2.loc[acc_merge_2['_merge'] == 'right_only_second']
acc_merge_2_right = acc_merge_2_right.dropna(axis='columns')
acc_merge_concat_2 = pd.concat([acc_bulan_3,acc_merge_2_right])
acc_merge_concat_2['_merge'] = acc_merge_concat_2[['_merge']].fillna(value='both')
merge_drop_2 = acc_merge_concat_2.drop_duplicates(subset=['Kode Barang'], keep='last')

#finishing Df bulan 1
acc_bulan_1['_merge'] = 'both_first'

#merger all bulan
acc_all = pd.concat([acc_bulan_1,merge_drop,merge_drop_2],ignore_index=True)

# perhitungan stock bayangan 
# All both
acc_all.loc[acc_all['_merge'] == 'both_first', 'stock bayangan'] = acc_all['Stock Awal']+acc_all['Stock In']
acc_all.loc[acc_all['_merge'] == 'both', 'stock bayangan'] = acc_all['Stock In']
acc_all.loc[acc_all['_merge'] == 'both', 'stock bayangan'] = acc_all['Stock In']
# right only first
acc_all.loc[acc_all['_merge'] == 'right_only_first', 'stock bayangan'] = acc_all['Stock Awal']+acc_all['Stock In']
# right only second
acc_all.loc[acc_all['_merge'] == 'right_only_second', 'stock bayangan'] = acc_all['Stock Awal']+acc_all['Stock In']

In [82]:
#acc_all.to_csv(r'C:\Users\afriz\Documents\Pekerjaan\YENS\Monthly Project\Monthly Project\ready data set\Accesories_testing_modeling_5.csv', index=False)

# Elekronik

In [83]:
Elektronik_dkt_1 = pd.read_excel(r'C:\Users\afriz\Documents\Pekerjaan\YENS\Monthly Project\Monthly Project\Elektronik\Elektronik_dkt_22_4.xlsx')
Elektronik_dkt_2 = pd.read_excel(r'C:\Users\afriz\Documents\Pekerjaan\YENS\Monthly Project\Monthly Project\Elektronik\Elektronik_dkt_22_5.xlsx')
Elektronik_dkt_3 = pd.read_excel(r'C:\Users\afriz\Documents\Pekerjaan\YENS\Monthly Project\Monthly Project\Elektronik\Elektronik_dkt_22_6.xlsx')

Elektronik_lbg_1 = pd.read_excel(r'C:\Users\afriz\Documents\Pekerjaan\YENS\Monthly Project\Monthly Project\Elektronik\Elektronik_lbg_22_4.xlsx')
Elektronik_lbg_2 = pd.read_excel(r'C:\Users\afriz\Documents\Pekerjaan\YENS\Monthly Project\Monthly Project\Elektronik\Elektronik_lbg_22_5.xlsx')
Elektronik_lbg_3 = pd.read_excel(r'C:\Users\afriz\Documents\Pekerjaan\YENS\Monthly Project\Monthly Project\Elektronik\Elektronik_lbg_22_6.xlsx')

Elektronik_stb_1 = pd.read_excel(r'C:\Users\afriz\Documents\Pekerjaan\YENS\Monthly Project\Monthly Project\Elektronik\Elektronik_stb_22_4.xlsx')
Elektronik_stb_2 = pd.read_excel(r'C:\Users\afriz\Documents\Pekerjaan\YENS\Monthly Project\Monthly Project\Elektronik\Elektronik_stb_22_5.xlsx')
Elektronik_stb_3 = pd.read_excel(r'C:\Users\afriz\Documents\Pekerjaan\YENS\Monthly Project\Monthly Project\Elektronik\Elektronik_stb_22_6.xlsx')

Elektronik_tki_1 = pd.read_excel(r'C:\Users\afriz\Documents\Pekerjaan\YENS\Monthly Project\Monthly Project\Elektronik\Elektronik_tki_22_4.xlsx')
Elektronik_tki_2 = pd.read_excel(r'C:\Users\afriz\Documents\Pekerjaan\YENS\Monthly Project\Monthly Project\Elektronik\Elektronik_tki_22_5.xlsx')
Elektronik_tki_3 = pd.read_excel(r'C:\Users\afriz\Documents\Pekerjaan\YENS\Monthly Project\Monthly Project\Elektronik\Elektronik_tki_22_6.xlsx')

In [84]:
Elektronik_dkt_1.columns = Elektronik_dkt_1.iloc[4]
Elektronik_dkt_2.columns = Elektronik_dkt_2.iloc[4]
Elektronik_dkt_3.columns = Elektronik_dkt_3.iloc[4]

Elektronik_lbg_1.columns = Elektronik_lbg_1.iloc[4]
Elektronik_lbg_2.columns = Elektronik_lbg_2.iloc[4]
Elektronik_lbg_3.columns = Elektronik_lbg_3.iloc[4]

Elektronik_stb_1.columns = Elektronik_stb_1.iloc[4]
Elektronik_stb_2.columns = Elektronik_stb_2.iloc[4]
Elektronik_stb_3.columns = Elektronik_stb_3.iloc[4]

Elektronik_tki_1.columns = Elektronik_tki_1.iloc[4]
Elektronik_tki_2.columns = Elektronik_tki_2.iloc[4]
Elektronik_tki_3.columns = Elektronik_tki_3.iloc[4]

In [85]:
Elektronik_dkt_1 = Elektronik_dkt_1.drop(Elektronik_dkt_1.index[0:5])
Elektronik_dkt_2 = Elektronik_dkt_2.drop(Elektronik_dkt_2.index[0:5])
Elektronik_dkt_3 = Elektronik_dkt_3.drop(Elektronik_dkt_3.index[0:5])

Elektronik_lbg_1 = Elektronik_lbg_1.drop(Elektronik_lbg_1.index[0:5])
Elektronik_lbg_2 = Elektronik_lbg_2.drop(Elektronik_lbg_2.index[0:5])
Elektronik_lbg_3 = Elektronik_lbg_3.drop(Elektronik_lbg_3.index[0:5])

Elektronik_stb_1 = Elektronik_stb_1.drop(Elektronik_stb_1.index[0:5])
Elektronik_stb_2 = Elektronik_stb_2.drop(Elektronik_stb_2.index[0:5])
Elektronik_stb_3 = Elektronik_stb_3.drop(Elektronik_stb_3.index[0:5])

Elektronik_tki_1 = Elektronik_tki_1.drop(Elektronik_tki_1.index[0:5])
Elektronik_tki_2 = Elektronik_tki_2.drop(Elektronik_tki_2.index[0:5])
Elektronik_tki_3 = Elektronik_tki_3.drop(Elektronik_tki_3.index[0:5])

In [86]:
Elektronik_dkt_1 = Elektronik_dkt_1[:-1]
Elektronik_dkt_2 = Elektronik_dkt_2[:-1]
Elektronik_dkt_3 = Elektronik_dkt_3[:-1]

Elektronik_lbg_1 = Elektronik_lbg_1[:-1]
Elektronik_lbg_2 = Elektronik_lbg_2[:-1]
Elektronik_lbg_3 = Elektronik_lbg_3[:-1]

Elektronik_stb_1 = Elektronik_stb_1[:-1]
Elektronik_stb_2 = Elektronik_stb_2[:-1]
Elektronik_stb_3 = Elektronik_stb_3[:-1]

Elektronik_tki_1 = Elektronik_tki_1[:-1]
Elektronik_tki_2 = Elektronik_tki_2[:-1]
Elektronik_tki_3 = Elektronik_tki_3[:-1]

In [87]:
Elektronik_dkt_1['cabang'] = 'dkt'
Elektronik_dkt_2['cabang'] = 'dkt'
Elektronik_dkt_3['cabang'] = 'dkt'

Elektronik_lbg_1['cabang'] = 'lbg'
Elektronik_lbg_2['cabang'] = 'lbg'
Elektronik_lbg_3['cabang'] = 'lbg'

Elektronik_stb_1['cabang'] = 'stb'
Elektronik_stb_2['cabang'] = 'stb'
Elektronik_stb_3['cabang'] = 'stb'

Elektronik_tki_1['cabang'] = 'tki'
Elektronik_tki_2['cabang'] = 'tki'
Elektronik_tki_3['cabang'] = 'tki'

In [88]:
Elektronik_dkt_1['bulan'] = '4'
Elektronik_dkt_2['bulan'] = '4'
Elektronik_dkt_3['bulan'] = '5'

Elektronik_lbg_1['bulan'] = '4'
Elektronik_lbg_2['bulan'] = '5'
Elektronik_lbg_3['bulan'] = '6'

Elektronik_stb_1['bulan'] = '4'
Elektronik_stb_2['bulan'] = '5'
Elektronik_stb_3['bulan'] = '6'

Elektronik_tki_1['bulan'] = '4'
Elektronik_tki_2['bulan'] = '5'
Elektronik_tki_3['bulan'] = '6'

In [89]:
elk_bulan_1 = pd.concat([Elektronik_dkt_1,Elektronik_lbg_1,Elektronik_stb_1,Elektronik_tki_1], ignore_index=True)
elk_bulan_2 = pd.concat([Elektronik_dkt_2,Elektronik_lbg_2,Elektronik_stb_2,Elektronik_tki_2], ignore_index=True)
elk_bulan_3 = pd.concat([Elektronik_dkt_3,Elektronik_lbg_3,Elektronik_stb_3,Elektronik_tki_3], ignore_index=True)

In [90]:
#create Df bulan 2
elk_merge_1 = pd.merge(elk_bulan_1,elk_bulan_2, how='outer' ,on=['Kode Barang'], indicator=True, suffixes=("_x", ""),)
elk_merge_1["_merge"].replace({"right_only": "right_only_first"}, inplace=True)
elk_merge_1_right = elk_merge_1.loc[elk_merge_1['_merge'] == 'right_only_first']
elk_merge_1_right = elk_merge_1_right.dropna(axis='columns')
elk_merge_concat_1 = pd.concat([elk_bulan_2,elk_merge_1_right])
elk_merge_concat_1['_merge'] = elk_merge_concat_1[['_merge']].fillna(value='both')
merge_drop = elk_merge_concat_1.drop_duplicates(subset=['Kode Barang'], keep='last')

#clean bahan df bulan 3
merge_drop_clean = merge_drop.iloc[:,0:23]

#create Df bulan 3
elk_merge_2 = pd.merge(merge_drop_clean,elk_bulan_3, how='outer' ,on=['Kode Barang'], indicator=True, suffixes=("_x", ""),)
elk_merge_2["_merge"].replace({"right_only": "right_only_second"}, inplace=True)
elk_merge_2_right = elk_merge_2.loc[elk_merge_2['_merge'] == 'right_only_second']
elk_merge_2_right = elk_merge_2_right.dropna(axis='columns')
elk_merge_concat_2 = pd.concat([elk_bulan_3,elk_merge_2_right])
elk_merge_concat_2['_merge'] = elk_merge_concat_2[['_merge']].fillna(value='both')
merge_drop_2 = elk_merge_concat_2.drop_duplicates(subset=['Kode Barang'], keep='last')

#finishing Df bulan 1
elk_bulan_1['_merge'] = 'both_first'

#merger all bulan
elk_all = pd.concat([elk_bulan_1,merge_drop,merge_drop_2],ignore_index=True)

# perhitungan stock bayangan 
# All both
elk_all.loc[elk_all['_merge'] == 'both_first', 'stock bayangan'] = elk_all['Stock Awal']+elk_all['Stock In']
elk_all.loc[elk_all['_merge'] == 'both', 'stock bayangan'] = elk_all['Stock In']
elk_all.loc[elk_all['_merge'] == 'both', 'stock bayangan'] = elk_all['Stock In']
# right only first
elk_all.loc[elk_all['_merge'] == 'right_only_first', 'stock bayangan'] = elk_all['Stock Awal']+elk_all['Stock In']
# right only second
elk_all.loc[elk_all['_merge'] == 'right_only_second', 'stock bayangan'] = elk_all['Stock Awal']+elk_all['Stock In']

In [91]:
#elk_all.to_csv(r'C:\Users\afriz\Documents\Pekerjaan\YENS\Monthly Project\Monthly Project\ready data set\Elektronik_testing_modeling_5.csv', index=False)

# Stationary

In [92]:
Stationary_dkt_1 = pd.read_excel(r'C:\Users\afriz\Documents\Pekerjaan\YENS\Monthly Project\Monthly Project\Stationary\Stationary_dkt_22_4.xlsx')
Stationary_dkt_2 = pd.read_excel(r'C:\Users\afriz\Documents\Pekerjaan\YENS\Monthly Project\Monthly Project\Stationary\Stationary_dkt_22_5.xlsx')
Stationary_dkt_3 = pd.read_excel(r'C:\Users\afriz\Documents\Pekerjaan\YENS\Monthly Project\Monthly Project\Stationary\Stationary_dkt_22_6.xlsx')

Stationary_lbg_1 = pd.read_excel(r'C:\Users\afriz\Documents\Pekerjaan\YENS\Monthly Project\Monthly Project\Stationary\Stationary_lbg_22_4.xlsx')
Stationary_lbg_2 = pd.read_excel(r'C:\Users\afriz\Documents\Pekerjaan\YENS\Monthly Project\Monthly Project\Stationary\Stationary_lbg_22_5.xlsx')
Stationary_lbg_3 = pd.read_excel(r'C:\Users\afriz\Documents\Pekerjaan\YENS\Monthly Project\Monthly Project\Stationary\Stationary_lbg_22_6.xlsx')

Stationary_stb_1 = pd.read_excel(r'C:\Users\afriz\Documents\Pekerjaan\YENS\Monthly Project\Monthly Project\Stationary\Stationary_stb_22_4.xlsx')
Stationary_stb_2 = pd.read_excel(r'C:\Users\afriz\Documents\Pekerjaan\YENS\Monthly Project\Monthly Project\Stationary\Stationary_stb_22_5.xlsx')
Stationary_stb_3 = pd.read_excel(r'C:\Users\afriz\Documents\Pekerjaan\YENS\Monthly Project\Monthly Project\Stationary\Stationary_stb_22_6.xlsx')

Stationary_tki_1 = pd.read_excel(r'C:\Users\afriz\Documents\Pekerjaan\YENS\Monthly Project\Monthly Project\Stationary\Stationary_tki_22_4.xlsx')
Stationary_tki_2 = pd.read_excel(r'C:\Users\afriz\Documents\Pekerjaan\YENS\Monthly Project\Monthly Project\Stationary\Stationary_tki_22_5.xlsx')
Stationary_tki_3 = pd.read_excel(r'C:\Users\afriz\Documents\Pekerjaan\YENS\Monthly Project\Monthly Project\Stationary\Stationary_tki_22_6.xlsx')

In [93]:
Stationary_dkt_1.columns = Stationary_dkt_1.iloc[4]
Stationary_dkt_2.columns = Stationary_dkt_2.iloc[4]
Stationary_dkt_3.columns = Stationary_dkt_3.iloc[4]

Stationary_lbg_1.columns = Stationary_lbg_1.iloc[4]
Stationary_lbg_2.columns = Stationary_lbg_2.iloc[4]
Stationary_lbg_3.columns = Stationary_lbg_3.iloc[4]

Stationary_stb_1.columns = Stationary_stb_1.iloc[4]
Stationary_stb_2.columns = Stationary_stb_2.iloc[4]
Stationary_stb_3.columns = Stationary_stb_3.iloc[4]

Stationary_tki_1.columns = Stationary_tki_1.iloc[4]
Stationary_tki_2.columns = Stationary_tki_2.iloc[4]
Stationary_tki_3.columns = Stationary_tki_3.iloc[4]

In [94]:
Stationary_dkt_1 = Stationary_dkt_1.drop(Stationary_dkt_1.index[0:5])
Stationary_dkt_2 = Stationary_dkt_2.drop(Stationary_dkt_2.index[0:5])
Stationary_dkt_3 = Stationary_dkt_3.drop(Stationary_dkt_3.index[0:5])

Stationary_lbg_1 = Stationary_lbg_1.drop(Stationary_lbg_1.index[0:5])
Stationary_lbg_2 = Stationary_lbg_2.drop(Stationary_lbg_2.index[0:5])
Stationary_lbg_3 = Stationary_lbg_3.drop(Stationary_lbg_3.index[0:5])

Stationary_stb_1 = Stationary_stb_1.drop(Stationary_stb_1.index[0:5])
Stationary_stb_2 = Stationary_stb_2.drop(Stationary_stb_2.index[0:5])
Stationary_stb_3 = Stationary_stb_3.drop(Stationary_stb_3.index[0:5])

Stationary_tki_1 = Stationary_tki_1.drop(Stationary_tki_1.index[0:5])
Stationary_tki_2 = Stationary_tki_2.drop(Stationary_tki_2.index[0:5])
Stationary_tki_3 = Stationary_tki_3.drop(Stationary_tki_3.index[0:5])

In [95]:
Stationary_dkt_1 = Stationary_dkt_1[:-1]
Stationary_dkt_2 = Stationary_dkt_2[:-1]
Stationary_dkt_3 = Stationary_dkt_3[:-1]

Stationary_lbg_1 = Stationary_lbg_1[:-1]
Stationary_lbg_2 = Stationary_lbg_2[:-1]
Stationary_lbg_3 = Stationary_lbg_3[:-1]

Stationary_stb_1 = Stationary_stb_1[:-1]
Stationary_stb_2 = Stationary_stb_2[:-1]
Stationary_stb_3 = Stationary_stb_3[:-1]

Stationary_tki_1 = Stationary_tki_1[:-1]
Stationary_tki_2 = Stationary_tki_2[:-1]
Stationary_tki_3 = Stationary_tki_3[:-1]

In [96]:
Stationary_dkt_1['cabang'] = 'dkt'
Stationary_dkt_2['cabang'] = 'dkt'
Stationary_dkt_3['cabang'] = 'dkt'

Stationary_lbg_1['cabang'] = 'lbg'
Stationary_lbg_2['cabang'] = 'lbg'
Stationary_lbg_3['cabang'] = 'lbg'

Stationary_stb_1['cabang'] = 'stb'
Stationary_stb_2['cabang'] = 'stb'
Stationary_stb_3['cabang'] = 'stb'

Stationary_tki_1['cabang'] = 'tki'
Stationary_tki_2['cabang'] = 'tki'
Stationary_tki_3['cabang'] = 'tki'

In [97]:
Stationary_dkt_1['bulan'] = '4'
Stationary_dkt_2['bulan'] = '5'
Stationary_dkt_3['bulan'] = '6'

Stationary_lbg_1['bulan'] = '4'
Stationary_lbg_2['bulan'] = '5'
Stationary_lbg_3['bulan'] = '6'

Stationary_stb_1['bulan'] = '4'
Stationary_stb_2['bulan'] = '5'
Stationary_stb_3['bulan'] = '6'

Stationary_tki_1['bulan'] = '4'
Stationary_tki_2['bulan'] = '5'
Stationary_tki_3['bulan'] = '6'

In [98]:
stn_bulan_1 = pd.concat([Stationary_dkt_1,Stationary_lbg_1,Stationary_stb_1,Stationary_tki_1], ignore_index=True)
stn_bulan_2 = pd.concat([Stationary_dkt_2,Stationary_lbg_2,Stationary_stb_2,Stationary_tki_2], ignore_index=True)
stn_bulan_3 = pd.concat([Stationary_dkt_3,Stationary_lbg_3,Stationary_stb_3,Stationary_tki_3], ignore_index=True)

In [99]:
#create Df bulan 2
stn_merge_1 = pd.merge(stn_bulan_1,stn_bulan_2, how='outer' ,on=['Kode Barang'], indicator=True, suffixes=("_x", ""),)
stn_merge_1["_merge"].replace({"right_only": "right_only_first"}, inplace=True)
stn_merge_1_right = stn_merge_1.loc[stn_merge_1['_merge'] == 'right_only_first']
stn_merge_1_right = stn_merge_1_right.dropna(axis='columns')
stn_merge_concat_1 = pd.concat([stn_bulan_2,stn_merge_1_right])
stn_merge_concat_1['_merge'] = stn_merge_concat_1[['_merge']].fillna(value='both')
merge_drop = stn_merge_concat_1.drop_duplicates(subset=['Kode Barang'], keep='last')

#clean bahan df bulan 3
merge_drop_clean = merge_drop.iloc[:,0:23]

#create Df bulan 3
stn_merge_2 = pd.merge(merge_drop_clean,stn_bulan_3, how='outer' ,on=['Kode Barang'], indicator=True, suffixes=("_x", ""),)
stn_merge_2["_merge"].replace({"right_only": "right_only_second"}, inplace=True)
stn_merge_2_right = stn_merge_2.loc[stn_merge_2['_merge'] == 'right_only_second']
stn_merge_2_right = stn_merge_2_right.dropna(axis='columns')
stn_merge_concat_2 = pd.concat([stn_bulan_3,stn_merge_2_right])
stn_merge_concat_2['_merge'] = stn_merge_concat_2[['_merge']].fillna(value='both')
merge_drop_2 = stn_merge_concat_2.drop_duplicates(subset=['Kode Barang'], keep='last')

#finishing Df bulan 1
stn_bulan_1['_merge'] = 'both_first'

#merger all bulan
stn_all = pd.concat([stn_bulan_1,merge_drop,merge_drop_2],ignore_index=True)

# perhitungan stock bayangan 
# All both
stn_all.loc[stn_all['_merge'] == 'both_first', 'stock bayangan'] = stn_all['Stock Awal']+stn_all['Stock In']
stn_all.loc[stn_all['_merge'] == 'both', 'stock bayangan'] = stn_all['Stock In']
stn_all.loc[stn_all['_merge'] == 'both', 'stock bayangan'] = stn_all['Stock In']
# right only first
stn_all.loc[stn_all['_merge'] == 'right_only_first', 'stock bayangan'] = stn_all['Stock Awal']+stn_all['Stock In']
# right only second
stn_all.loc[stn_all['_merge'] == 'right_only_second', 'stock bayangan'] = stn_all['Stock Awal']+stn_all['Stock In']

In [100]:
#stn_all.to_csv(r'C:\Users\afriz\Documents\Pekerjaan\YENS\Monthly Project\Monthly Project\ready data set\Stationary_testing_modeling_5.csv', index=False)

# Underwear

In [101]:
Underwear_dkt_1 = pd.read_excel(r'C:\Users\afriz\Documents\Pekerjaan\YENS\Monthly Project\Monthly Project\Underwear\Underwear_dkt_22_4.xlsx')
Underwear_dkt_2 = pd.read_excel(r'C:\Users\afriz\Documents\Pekerjaan\YENS\Monthly Project\Monthly Project\Underwear\Underwear_dkt_22_5.xlsx')
Underwear_dkt_3 = pd.read_excel(r'C:\Users\afriz\Documents\Pekerjaan\YENS\Monthly Project\Monthly Project\Underwear\Underwear_dkt_22_6.xlsx')

Underwear_lbg_1 = pd.read_excel(r'C:\Users\afriz\Documents\Pekerjaan\YENS\Monthly Project\Monthly Project\Underwear\Underwear_lbg_22_4.xlsx')
Underwear_lbg_2 = pd.read_excel(r'C:\Users\afriz\Documents\Pekerjaan\YENS\Monthly Project\Monthly Project\Underwear\Underwear_lbg_22_5.xlsx')
Underwear_lbg_3 = pd.read_excel(r'C:\Users\afriz\Documents\Pekerjaan\YENS\Monthly Project\Monthly Project\Underwear\Underwear_lbg_22_6.xlsx')

Underwear_stb_1 = pd.read_excel(r'C:\Users\afriz\Documents\Pekerjaan\YENS\Monthly Project\Monthly Project\Underwear\Underwear_stb_22_4.xlsx')
Underwear_stb_2 = pd.read_excel(r'C:\Users\afriz\Documents\Pekerjaan\YENS\Monthly Project\Monthly Project\Underwear\Underwear_stb_22_5.xlsx')
Underwear_stb_3 = pd.read_excel(r'C:\Users\afriz\Documents\Pekerjaan\YENS\Monthly Project\Monthly Project\Underwear\Underwear_stb_22_6.xlsx')

Underwear_tki_1 = pd.read_excel(r'C:\Users\afriz\Documents\Pekerjaan\YENS\Monthly Project\Monthly Project\Underwear\Underwear_tki_22_4.xlsx')
Underwear_tki_2 = pd.read_excel(r'C:\Users\afriz\Documents\Pekerjaan\YENS\Monthly Project\Monthly Project\Underwear\Underwear_tki_22_5.xlsx')
Underwear_tki_3 = pd.read_excel(r'C:\Users\afriz\Documents\Pekerjaan\YENS\Monthly Project\Monthly Project\Underwear\Underwear_tki_22_6.xlsx')

In [102]:
Underwear_dkt_1.columns = Underwear_dkt_1.iloc[4]
Underwear_dkt_2.columns = Underwear_dkt_2.iloc[4]
Underwear_dkt_3.columns = Underwear_dkt_3.iloc[4]

Underwear_lbg_1.columns = Underwear_lbg_1.iloc[4]
Underwear_lbg_2.columns = Underwear_lbg_2.iloc[4]
Underwear_lbg_3.columns = Underwear_lbg_3.iloc[4]

Underwear_stb_1.columns = Underwear_stb_1.iloc[4]
Underwear_stb_2.columns = Underwear_stb_2.iloc[4]
Underwear_stb_3.columns = Underwear_stb_3.iloc[4]

Underwear_tki_1.columns = Underwear_tki_1.iloc[4]
Underwear_tki_2.columns = Underwear_tki_2.iloc[4]
Underwear_tki_3.columns = Underwear_tki_3.iloc[4]

In [103]:
Underwear_dkt_1 = Underwear_dkt_1.drop(Underwear_dkt_1.index[0:5])
Underwear_dkt_2 = Underwear_dkt_2.drop(Underwear_dkt_2.index[0:5])
Underwear_dkt_3 = Underwear_dkt_3.drop(Underwear_dkt_3.index[0:5])

Underwear_lbg_1 = Underwear_lbg_1.drop(Underwear_lbg_1.index[0:5])
Underwear_lbg_2 = Underwear_lbg_2.drop(Underwear_lbg_2.index[0:5])
Underwear_lbg_3 = Underwear_lbg_3.drop(Underwear_lbg_3.index[0:5])

Underwear_stb_1 = Underwear_stb_1.drop(Underwear_stb_1.index[0:5])
Underwear_stb_2 = Underwear_stb_2.drop(Underwear_stb_2.index[0:5])
Underwear_stb_3 = Underwear_stb_3.drop(Underwear_stb_3.index[0:5])

Underwear_tki_1 = Underwear_tki_1.drop(Underwear_tki_1.index[0:5])
Underwear_tki_2 = Underwear_tki_2.drop(Underwear_tki_2.index[0:5])
Underwear_tki_3 = Underwear_tki_3.drop(Underwear_tki_3.index[0:5])

In [104]:
Underwear_dkt_1 = Underwear_dkt_1[:-1]
Underwear_dkt_2 = Underwear_dkt_2[:-1]
Underwear_dkt_3 = Underwear_dkt_3[:-1]

Underwear_lbg_1 = Underwear_lbg_1[:-1]
Underwear_lbg_2 = Underwear_lbg_2[:-1]
Underwear_lbg_3 = Underwear_lbg_3[:-1]

Underwear_stb_1 = Underwear_stb_1[:-1]
Underwear_stb_2 = Underwear_stb_2[:-1]
Underwear_stb_3 = Underwear_stb_3[:-1]

Underwear_tki_1 = Underwear_tki_1[:-1]
Underwear_tki_2 = Underwear_tki_2[:-1]
Underwear_tki_3 = Underwear_tki_3[:-1]

In [105]:
Underwear_dkt_1['cabang'] = 'dkt'
Underwear_dkt_2['cabang'] = 'dkt'
Underwear_dkt_3['cabang'] = 'dkt'

Underwear_lbg_1['cabang'] = 'lbg'
Underwear_lbg_2['cabang'] = 'lbg'
Underwear_lbg_3['cabang'] = 'lbg'

Underwear_stb_1['cabang'] = 'stb'
Underwear_stb_2['cabang'] = 'stb'
Underwear_stb_3['cabang'] = 'stb'

Underwear_tki_1['cabang'] = 'tki'
Underwear_tki_2['cabang'] = 'tki'
Underwear_tki_3['cabang'] = 'tki'

In [106]:
Underwear_dkt_1['bulan'] = '4'
Underwear_dkt_2['bulan'] = '5'
Underwear_dkt_3['bulan'] = '6'

Underwear_lbg_1['bulan'] = '4'
Underwear_lbg_2['bulan'] = '5'
Underwear_lbg_3['bulan'] = '6'

Underwear_stb_1['bulan'] = '4'
Underwear_stb_2['bulan'] = '5'
Underwear_stb_3['bulan'] = '6'

Underwear_tki_1['bulan'] = '4'
Underwear_tki_2['bulan'] = '5'
Underwear_tki_3['bulan'] = '6'

In [107]:
und_bulan_1 = pd.concat([Underwear_dkt_1,Underwear_lbg_1,Underwear_stb_1,Underwear_tki_1], ignore_index=True)
und_bulan_2 = pd.concat([Underwear_dkt_2,Underwear_lbg_2,Underwear_stb_2,Underwear_tki_2], ignore_index=True)
und_bulan_3 = pd.concat([Underwear_dkt_3,Underwear_lbg_3,Underwear_stb_3,Underwear_tki_3], ignore_index=True)

In [108]:
#create Df bulan 2
und_merge_1 = pd.merge(und_bulan_1,und_bulan_2, how='outer' ,on=['Kode Barang'], indicator=True, suffixes=("_x", ""),)
und_merge_1["_merge"].replace({"right_only": "right_only_first"}, inplace=True)
und_merge_1_right = und_merge_1.loc[und_merge_1['_merge'] == 'right_only_first']
und_merge_1_right = und_merge_1_right.dropna(axis='columns')
und_merge_concat_1 = pd.concat([und_bulan_2,und_merge_1_right])
und_merge_concat_1['_merge'] = und_merge_concat_1[['_merge']].fillna(value='both')
merge_drop = und_merge_concat_1.drop_duplicates(subset=['Kode Barang'], keep='last')

#clean bahan df bulan 3
merge_drop_clean = merge_drop.iloc[:,0:23]

#create Df bulan 3
und_merge_2 = pd.merge(merge_drop_clean,und_bulan_3, how='outer' ,on=['Kode Barang'], indicator=True, suffixes=("_x", ""),)
und_merge_2["_merge"].replace({"right_only": "right_only_second"}, inplace=True)
und_merge_2_right = und_merge_2.loc[und_merge_2['_merge'] == 'right_only_second']
und_merge_2_right = und_merge_2_right.dropna(axis='columns')
und_merge_concat_2 = pd.concat([und_bulan_3,und_merge_2_right])
und_merge_concat_2['_merge'] = und_merge_concat_2[['_merge']].fillna(value='both')
merge_drop_2 = und_merge_concat_2.drop_duplicates(subset=['Kode Barang'], keep='last')

#finishing Df bulan 1
und_bulan_1['_merge'] = 'both_first'

#merger all bulan
und_all = pd.concat([und_bulan_1,merge_drop,merge_drop_2],ignore_index=True)

# perhitungan stock bayangan 
# All both
und_all.loc[und_all['_merge'] == 'both_first', 'stock bayangan'] = und_all['Stock Awal']+und_all['Stock In']
und_all.loc[und_all['_merge'] == 'both', 'stock bayangan'] = und_all['Stock In']
und_all.loc[und_all['_merge'] == 'both', 'stock bayangan'] = und_all['Stock In']
# right only first
und_all.loc[und_all['_merge'] == 'right_only_first', 'stock bayangan'] = und_all['Stock Awal']+und_all['Stock In']
# right only second
und_all.loc[und_all['_merge'] == 'right_only_second', 'stock bayangan'] = und_all['Stock Awal']+und_all['Stock In']

In [109]:
#und_all.to_csv(r'C:\Users\afriz\Documents\Pekerjaan\YENS\Monthly Project\Monthly Project\ready data set\Underwear_testing_modeling_5.csv', index=False)

# Perlengkapan Anak

In [110]:
Perlengkapan_Anak_dkt_1 = pd.read_excel(r'C:\Users\afriz\Documents\Pekerjaan\YENS\Monthly Project\Monthly Project\Perlengkapan Anak\Perlengkapan_Anak_dkt_22_4.xlsx')
Perlengkapan_Anak_dkt_2 = pd.read_excel(r'C:\Users\afriz\Documents\Pekerjaan\YENS\Monthly Project\Monthly Project\Perlengkapan Anak\Perlengkapan_Anak_dkt_22_5.xlsx')
Perlengkapan_Anak_dkt_3 = pd.read_excel(r'C:\Users\afriz\Documents\Pekerjaan\YENS\Monthly Project\Monthly Project\Perlengkapan Anak\Perlengkapan_Anak_dkt_22_6.xlsx')

Perlengkapan_Anak_lbg_1 = pd.read_excel(r'C:\Users\afriz\Documents\Pekerjaan\YENS\Monthly Project\Monthly Project\Perlengkapan Anak\Perlengkapan_Anak_lbg_22_4.xlsx')
Perlengkapan_Anak_lbg_2 = pd.read_excel(r'C:\Users\afriz\Documents\Pekerjaan\YENS\Monthly Project\Monthly Project\Perlengkapan Anak\Perlengkapan_Anak_lbg_22_5.xlsx')
Perlengkapan_Anak_lbg_3 = pd.read_excel(r'C:\Users\afriz\Documents\Pekerjaan\YENS\Monthly Project\Monthly Project\Perlengkapan Anak\Perlengkapan_Anak_lbg_22_6.xlsx')

Perlengkapan_Anak_stb_1 = pd.read_excel(r'C:\Users\afriz\Documents\Pekerjaan\YENS\Monthly Project\Monthly Project\Perlengkapan Anak\Perlengkapan_Anak_stb_22_4.xlsx')
Perlengkapan_Anak_stb_2 = pd.read_excel(r'C:\Users\afriz\Documents\Pekerjaan\YENS\Monthly Project\Monthly Project\Perlengkapan Anak\Perlengkapan_Anak_stb_22_5.xlsx')
Perlengkapan_Anak_stb_3 = pd.read_excel(r'C:\Users\afriz\Documents\Pekerjaan\YENS\Monthly Project\Monthly Project\Perlengkapan Anak\Perlengkapan_Anak_stb_22_6.xlsx')

Perlengkapan_Anak_tki_1 = pd.read_excel(r'C:\Users\afriz\Documents\Pekerjaan\YENS\Monthly Project\Monthly Project\Perlengkapan Anak\Perlengkapan_Anak_tki_22_4.xlsx')
Perlengkapan_Anak_tki_2 = pd.read_excel(r'C:\Users\afriz\Documents\Pekerjaan\YENS\Monthly Project\Monthly Project\Perlengkapan Anak\Perlengkapan_Anak_tki_22_5.xlsx')
Perlengkapan_Anak_tki_3 = pd.read_excel(r'C:\Users\afriz\Documents\Pekerjaan\YENS\Monthly Project\Monthly Project\Perlengkapan Anak\Perlengkapan_Anak_tki_22_6.xlsx')

In [111]:
Perlengkapan_Anak_dkt_1.columns = Perlengkapan_Anak_dkt_1.iloc[4]
Perlengkapan_Anak_dkt_2.columns = Perlengkapan_Anak_dkt_2.iloc[4]
Perlengkapan_Anak_dkt_3.columns = Perlengkapan_Anak_dkt_3.iloc[4]

Perlengkapan_Anak_lbg_1.columns = Perlengkapan_Anak_lbg_1.iloc[4]
Perlengkapan_Anak_lbg_2.columns = Perlengkapan_Anak_lbg_2.iloc[4]
Perlengkapan_Anak_lbg_3.columns = Perlengkapan_Anak_lbg_3.iloc[4]

Perlengkapan_Anak_stb_1.columns = Perlengkapan_Anak_stb_1.iloc[4]
Perlengkapan_Anak_stb_2.columns = Perlengkapan_Anak_stb_2.iloc[4]
Perlengkapan_Anak_stb_3.columns = Perlengkapan_Anak_stb_3.iloc[4]

Perlengkapan_Anak_tki_1.columns = Perlengkapan_Anak_tki_1.iloc[4]
Perlengkapan_Anak_tki_2.columns = Perlengkapan_Anak_tki_2.iloc[4]
Perlengkapan_Anak_tki_3.columns = Perlengkapan_Anak_tki_3.iloc[4]

In [112]:
Perlengkapan_Anak_dkt_1 = Perlengkapan_Anak_dkt_1.drop(Perlengkapan_Anak_dkt_1.index[0:5])
Perlengkapan_Anak_dkt_2 = Perlengkapan_Anak_dkt_2.drop(Perlengkapan_Anak_dkt_2.index[0:5])
Perlengkapan_Anak_dkt_3 = Perlengkapan_Anak_dkt_3.drop(Perlengkapan_Anak_dkt_3.index[0:5])

Perlengkapan_Anak_lbg_1 = Perlengkapan_Anak_lbg_1.drop(Perlengkapan_Anak_lbg_1.index[0:5])
Perlengkapan_Anak_lbg_2 = Perlengkapan_Anak_lbg_2.drop(Perlengkapan_Anak_lbg_2.index[0:5])
Perlengkapan_Anak_lbg_3 = Perlengkapan_Anak_lbg_3.drop(Perlengkapan_Anak_lbg_3.index[0:5])

Perlengkapan_Anak_stb_1 = Perlengkapan_Anak_stb_1.drop(Perlengkapan_Anak_stb_1.index[0:5])
Perlengkapan_Anak_stb_2 = Perlengkapan_Anak_stb_2.drop(Perlengkapan_Anak_stb_2.index[0:5])
Perlengkapan_Anak_stb_3 = Perlengkapan_Anak_stb_3.drop(Perlengkapan_Anak_stb_3.index[0:5])

Perlengkapan_Anak_tki_1 = Perlengkapan_Anak_tki_1.drop(Perlengkapan_Anak_tki_1.index[0:5])
Perlengkapan_Anak_tki_2 = Perlengkapan_Anak_tki_2.drop(Perlengkapan_Anak_tki_2.index[0:5])
Perlengkapan_Anak_tki_3 = Perlengkapan_Anak_tki_3.drop(Perlengkapan_Anak_tki_3.index[0:5])

In [113]:
Perlengkapan_Anak_dkt_1 = Perlengkapan_Anak_dkt_1[:-1]
Perlengkapan_Anak_dkt_2 = Perlengkapan_Anak_dkt_2[:-1]
Perlengkapan_Anak_dkt_3 = Perlengkapan_Anak_dkt_3[:-1]

Perlengkapan_Anak_lbg_1 = Perlengkapan_Anak_lbg_1[:-1]
Perlengkapan_Anak_lbg_2 = Perlengkapan_Anak_lbg_2[:-1]
Perlengkapan_Anak_lbg_3 = Perlengkapan_Anak_lbg_3[:-1]

Perlengkapan_Anak_stb_1 = Perlengkapan_Anak_stb_1[:-1]
Perlengkapan_Anak_stb_2 = Perlengkapan_Anak_stb_2[:-1]
Perlengkapan_Anak_stb_3 = Perlengkapan_Anak_stb_3[:-1]

Perlengkapan_Anak_tki_1 = Perlengkapan_Anak_tki_1[:-1]
Perlengkapan_Anak_tki_2 = Perlengkapan_Anak_tki_2[:-1]
Perlengkapan_Anak_tki_3 = Perlengkapan_Anak_tki_3[:-1]

In [114]:
Perlengkapan_Anak_dkt_1['cabang'] = 'dkt'
Perlengkapan_Anak_dkt_2['cabang'] = 'dkt'
Perlengkapan_Anak_dkt_3['cabang'] = 'dkt'

Perlengkapan_Anak_lbg_1['cabang'] = 'lbg'
Perlengkapan_Anak_lbg_2['cabang'] = 'lbg'
Perlengkapan_Anak_lbg_3['cabang'] = 'lbg'

Perlengkapan_Anak_stb_1['cabang'] = 'stb'
Perlengkapan_Anak_stb_2['cabang'] = 'stb'
Perlengkapan_Anak_stb_3['cabang'] = 'stb'

Perlengkapan_Anak_tki_1['cabang'] = 'tki'
Perlengkapan_Anak_tki_2['cabang'] = 'tki'
Perlengkapan_Anak_tki_3['cabang'] = 'tki'

In [115]:
Perlengkapan_Anak_dkt_1['bulan'] = '4'
Perlengkapan_Anak_dkt_2['bulan'] = '5'
Perlengkapan_Anak_dkt_3['bulan'] = '6'

Perlengkapan_Anak_lbg_1['bulan'] = '4'
Perlengkapan_Anak_lbg_2['bulan'] = '5'
Perlengkapan_Anak_lbg_3['bulan'] = '6'

Perlengkapan_Anak_stb_1['bulan'] = '4'
Perlengkapan_Anak_stb_2['bulan'] = '5'
Perlengkapan_Anak_stb_3['bulan'] = '6'

Perlengkapan_Anak_tki_1['bulan'] = '4'
Perlengkapan_Anak_tki_2['bulan'] = '5'
Perlengkapan_Anak_tki_3['bulan'] = '6'

In [116]:
pa_bulan_1 = pd.concat([Perlengkapan_Anak_dkt_1,Perlengkapan_Anak_lbg_1,Perlengkapan_Anak_stb_1,Perlengkapan_Anak_tki_1], ignore_index=True)
pa_bulan_2 = pd.concat([Perlengkapan_Anak_dkt_2,Perlengkapan_Anak_lbg_2,Perlengkapan_Anak_stb_2,Perlengkapan_Anak_tki_2], ignore_index=True)
pa_bulan_3 = pd.concat([Perlengkapan_Anak_dkt_3,Perlengkapan_Anak_lbg_3,Perlengkapan_Anak_stb_3,Perlengkapan_Anak_tki_3], ignore_index=True)

In [117]:
#create Df bulan 2
pa_merge_1 = pd.merge(pa_bulan_1,pa_bulan_2, how='outer' ,on=['Kode Barang'], indicator=True, suffixes=("_x", ""),)
pa_merge_1["_merge"].replace({"right_only": "right_only_first"}, inplace=True)
pa_merge_1_right = pa_merge_1.loc[pa_merge_1['_merge'] == 'right_only_first']
pa_merge_1_right = pa_merge_1_right.dropna(axis='columns')
pa_merge_concat_1 = pd.concat([pa_bulan_2,pa_merge_1_right])
pa_merge_concat_1['_merge'] = pa_merge_concat_1[['_merge']].fillna(value='both')
merge_drop = pa_merge_concat_1.drop_duplicates(subset=['Kode Barang'], keep='last')

#clean bahan df bulan 3
merge_drop_clean = merge_drop.iloc[:,0:23]

#create Df bulan 3
pa_merge_2 = pd.merge(merge_drop_clean,pa_bulan_3, how='outer' ,on=['Kode Barang'], indicator=True, suffixes=("_x", ""),)
pa_merge_2["_merge"].replace({"right_only": "right_only_second"}, inplace=True)
pa_merge_2_right = pa_merge_2.loc[pa_merge_2['_merge'] == 'right_only_second']
pa_merge_2_right = pa_merge_2_right.dropna(axis='columns')
pa_merge_concat_2 = pd.concat([pa_bulan_3,pa_merge_2_right])
pa_merge_concat_2['_merge'] = pa_merge_concat_2[['_merge']].fillna(value='both')
merge_drop_2 = pa_merge_concat_2.drop_duplicates(subset=['Kode Barang'], keep='last')

#finishing Df bulan 1
pa_bulan_1['_merge'] = 'both_first'

#merger all bulan
pa_all = pd.concat([pa_bulan_1,merge_drop,merge_drop_2],ignore_index=True)

# perhitungan stock bayangan 
# All both
pa_all.loc[pa_all['_merge'] == 'both_first', 'stock bayangan'] = pa_all['Stock Awal']+pa_all['Stock In']
pa_all.loc[pa_all['_merge'] == 'both', 'stock bayangan'] = pa_all['Stock In']
pa_all.loc[pa_all['_merge'] == 'both', 'stock bayangan'] = pa_all['Stock In']
# right only first
pa_all.loc[pa_all['_merge'] == 'right_only_first', 'stock bayangan'] = pa_all['Stock Awal']+pa_all['Stock In']
# right only second
pa_all.loc[pa_all['_merge'] == 'right_only_second', 'stock bayangan'] = pa_all['Stock Awal']+pa_all['Stock In']

In [118]:
#pa_all.to_csv(r'C:\Users\afriz\Documents\Pekerjaan\YENS\Monthly Project\Monthly Project\ready data set\Perlengkapan_Anak_testing_modeling_5.csv', index=False)

# Perlengkapan Bayi

In [119]:
Perlengkapan_Bayi_dkt_1 = pd.read_excel(r'C:\Users\afriz\Documents\Pekerjaan\YENS\Monthly Project\Monthly Project\Perlengkapan Bayi\Perlengkapan_Bayi_dkt_22_4.xlsx')
Perlengkapan_Bayi_dkt_2 = pd.read_excel(r'C:\Users\afriz\Documents\Pekerjaan\YENS\Monthly Project\Monthly Project\Perlengkapan Bayi\Perlengkapan_Bayi_dkt_22_5.xlsx')
Perlengkapan_Bayi_dkt_3 = pd.read_excel(r'C:\Users\afriz\Documents\Pekerjaan\YENS\Monthly Project\Monthly Project\Perlengkapan Bayi\Perlengkapan_Bayi_dkt_22_6.xlsx')

Perlengkapan_Bayi_lbg_1 = pd.read_excel(r'C:\Users\afriz\Documents\Pekerjaan\YENS\Monthly Project\Monthly Project\Perlengkapan Bayi\Perlengkapan_Bayi_lbg_22_4.xlsx')
Perlengkapan_Bayi_lbg_2 = pd.read_excel(r'C:\Users\afriz\Documents\Pekerjaan\YENS\Monthly Project\Monthly Project\Perlengkapan Bayi\Perlengkapan_Bayi_lbg_22_5.xlsx')
Perlengkapan_Bayi_lbg_3 = pd.read_excel(r'C:\Users\afriz\Documents\Pekerjaan\YENS\Monthly Project\Monthly Project\Perlengkapan Bayi\Perlengkapan_Bayi_lbg_22_6.xlsx')

Perlengkapan_Bayi_stb_1 = pd.read_excel(r'C:\Users\afriz\Documents\Pekerjaan\YENS\Monthly Project\Monthly Project\Perlengkapan Bayi\Perlengkapan_Bayi_stb_22_4.xlsx')
Perlengkapan_Bayi_stb_2 = pd.read_excel(r'C:\Users\afriz\Documents\Pekerjaan\YENS\Monthly Project\Monthly Project\Perlengkapan Bayi\Perlengkapan_Bayi_stb_22_5.xlsx')
Perlengkapan_Bayi_stb_3 = pd.read_excel(r'C:\Users\afriz\Documents\Pekerjaan\YENS\Monthly Project\Monthly Project\Perlengkapan Bayi\Perlengkapan_Bayi_stb_22_6.xlsx')

Perlengkapan_Bayi_tki_1 = pd.read_excel(r'C:\Users\afriz\Documents\Pekerjaan\YENS\Monthly Project\Monthly Project\Perlengkapan Bayi\Perlengkapan_Bayi_tki_22_4.xlsx')
Perlengkapan_Bayi_tki_2 = pd.read_excel(r'C:\Users\afriz\Documents\Pekerjaan\YENS\Monthly Project\Monthly Project\Perlengkapan Bayi\Perlengkapan_Bayi_tki_22_5.xlsx')
Perlengkapan_Bayi_tki_3 = pd.read_excel(r'C:\Users\afriz\Documents\Pekerjaan\YENS\Monthly Project\Monthly Project\Perlengkapan Bayi\Perlengkapan_Bayi_tki_22_6.xlsx')

In [120]:
Perlengkapan_Bayi_dkt_1.columns = Perlengkapan_Bayi_dkt_1.iloc[4]
Perlengkapan_Bayi_dkt_2.columns = Perlengkapan_Bayi_dkt_2.iloc[4]
Perlengkapan_Bayi_dkt_3.columns = Perlengkapan_Bayi_dkt_3.iloc[4]

Perlengkapan_Bayi_lbg_1.columns = Perlengkapan_Bayi_lbg_1.iloc[4]
Perlengkapan_Bayi_lbg_2.columns = Perlengkapan_Bayi_lbg_2.iloc[4]
Perlengkapan_Bayi_lbg_3.columns = Perlengkapan_Bayi_lbg_3.iloc[4]

Perlengkapan_Bayi_stb_1.columns = Perlengkapan_Bayi_stb_1.iloc[4]
Perlengkapan_Bayi_stb_2.columns = Perlengkapan_Bayi_stb_2.iloc[4]
Perlengkapan_Bayi_stb_3.columns = Perlengkapan_Bayi_stb_3.iloc[4]

Perlengkapan_Bayi_tki_1.columns = Perlengkapan_Bayi_tki_1.iloc[4]
Perlengkapan_Bayi_tki_2.columns = Perlengkapan_Bayi_tki_2.iloc[4]
Perlengkapan_Bayi_tki_3.columns = Perlengkapan_Bayi_tki_3.iloc[4]

In [121]:
Perlengkapan_Bayi_dkt_1 = Perlengkapan_Bayi_dkt_1.drop(Perlengkapan_Bayi_dkt_1.index[0:5])
Perlengkapan_Bayi_dkt_2 = Perlengkapan_Bayi_dkt_2.drop(Perlengkapan_Bayi_dkt_2.index[0:5])
Perlengkapan_Bayi_dkt_3 = Perlengkapan_Bayi_dkt_3.drop(Perlengkapan_Bayi_dkt_3.index[0:5])

Perlengkapan_Bayi_lbg_1 = Perlengkapan_Bayi_lbg_1.drop(Perlengkapan_Bayi_lbg_1.index[0:5])
Perlengkapan_Bayi_lbg_2 = Perlengkapan_Bayi_lbg_2.drop(Perlengkapan_Bayi_lbg_2.index[0:5])
Perlengkapan_Bayi_lbg_3 = Perlengkapan_Bayi_lbg_3.drop(Perlengkapan_Bayi_lbg_3.index[0:5])

Perlengkapan_Bayi_stb_1 = Perlengkapan_Bayi_stb_1.drop(Perlengkapan_Bayi_stb_1.index[0:5])
Perlengkapan_Bayi_stb_2 = Perlengkapan_Bayi_stb_2.drop(Perlengkapan_Bayi_stb_2.index[0:5])
Perlengkapan_Bayi_stb_3 = Perlengkapan_Bayi_stb_3.drop(Perlengkapan_Bayi_stb_3.index[0:5])

Perlengkapan_Bayi_tki_1 = Perlengkapan_Bayi_tki_1.drop(Perlengkapan_Bayi_tki_1.index[0:5])
Perlengkapan_Bayi_tki_2 = Perlengkapan_Bayi_tki_2.drop(Perlengkapan_Bayi_tki_2.index[0:5])
Perlengkapan_Bayi_tki_3 = Perlengkapan_Bayi_tki_3.drop(Perlengkapan_Bayi_tki_3.index[0:5])

In [122]:
Perlengkapan_Bayi_dkt_1 = Perlengkapan_Bayi_dkt_1[:-1]
Perlengkapan_Bayi_dkt_2 = Perlengkapan_Bayi_dkt_2[:-1]
Perlengkapan_Bayi_dkt_3 = Perlengkapan_Bayi_dkt_3[:-1]

Perlengkapan_Bayi_lbg_1 = Perlengkapan_Bayi_lbg_1[:-1]
Perlengkapan_Bayi_lbg_2 = Perlengkapan_Bayi_lbg_2[:-1]
Perlengkapan_Bayi_lbg_3 = Perlengkapan_Bayi_lbg_3[:-1]

Perlengkapan_Bayi_stb_1 = Perlengkapan_Bayi_stb_1[:-1]
Perlengkapan_Bayi_stb_2 = Perlengkapan_Bayi_stb_2[:-1]
Perlengkapan_Bayi_stb_3 = Perlengkapan_Bayi_stb_3[:-1]

Perlengkapan_Bayi_tki_1 = Perlengkapan_Bayi_tki_1[:-1]
Perlengkapan_Bayi_tki_2 = Perlengkapan_Bayi_tki_2[:-1]
Perlengkapan_Bayi_tki_3 = Perlengkapan_Bayi_tki_3[:-1]

In [123]:
Perlengkapan_Bayi_dkt_1['cabang'] = 'dkt'
Perlengkapan_Bayi_dkt_2['cabang'] = 'dkt'
Perlengkapan_Bayi_dkt_3['cabang'] = 'dkt'

Perlengkapan_Bayi_lbg_1['cabang'] = 'lbg'
Perlengkapan_Bayi_lbg_2['cabang'] = 'lbg'
Perlengkapan_Bayi_lbg_3['cabang'] = 'lbg'

Perlengkapan_Bayi_stb_1['cabang'] = 'stb'
Perlengkapan_Bayi_stb_2['cabang'] = 'stb'
Perlengkapan_Bayi_stb_3['cabang'] = 'stb'

Perlengkapan_Bayi_tki_1['cabang'] = 'tki'
Perlengkapan_Bayi_tki_2['cabang'] = 'tki'
Perlengkapan_Bayi_tki_3['cabang'] = 'tki'

In [124]:
Perlengkapan_Bayi_dkt_1['bulan'] = '4'
Perlengkapan_Bayi_dkt_2['bulan'] = '5'
Perlengkapan_Bayi_dkt_3['bulan'] = '6'

Perlengkapan_Bayi_lbg_1['bulan'] = '4'
Perlengkapan_Bayi_lbg_2['bulan'] = '5'
Perlengkapan_Bayi_lbg_3['bulan'] = '6'

Perlengkapan_Bayi_stb_1['bulan'] = '4'
Perlengkapan_Bayi_stb_2['bulan'] = '5'
Perlengkapan_Bayi_stb_3['bulan'] = '6'

Perlengkapan_Bayi_tki_1['bulan'] = '4'
Perlengkapan_Bayi_tki_2['bulan'] = '5'
Perlengkapan_Bayi_tki_3['bulan'] = '6'

In [125]:
#create Df bulan 2
#pb_merge_1 = pd.merge(Perlengkapan_Bayi_stb_1,Perlengkapan_Bayi_stb_2, how='outer' ,on=['Kode Barang'], indicator=True, suffixes=("_x", ""),)
#pb_merge_1["_merge"].replace({"right_only": "right_only_first"}, inplace=True)
#pb_merge_1_right = pb_merge_1.loc[pb_merge_1['_merge'] == 'right_only_first']
#pb_merge_1_right = pb_merge_1_right.dropna(axis='columns')
#merge = pd.concat([Perlengkapan_Bayi_stb_2,pb_merge_1_right])
#merge['_merge'] = merge[['_merge']].fillna(value='both')
#merge_drop = merge.drop_duplicates(subset=['Kode Barang'], keep='last')

#clean bahan df bulan 3
#merge_drop_clean = merge_drop.iloc[:,0:23]

#create Df bulan 3
#pb_merge_2 = pd.merge(merge_drop_clean,Perlengkapan_Bayi_stb_3, how='outer' ,on=['Kode Barang'], indicator=True, suffixes=("_x", ""),)
#pb_merge_2["_merge"].replace({"right_only": "right_only_second"}, inplace=True)
#pb_merge_2_right = pb_merge_2.loc[pb_merge_2['_merge'] == 'right_only_second']
#pb_merge_2_right = pb_merge_2_right.dropna(axis='columns')
#merge_2 = pd.concat([Perlengkapan_Bayi_stb_3,pb_merge_2_right])
#merge_2['_merge'] = merge_2[['_merge']].fillna(value='both')
#merge_drop_2 = merge_2.drop_duplicates(subset=['Kode Barang'], keep='last')

#finishing Df bulan 1
#Perlengkapan_Bayi_stb_1['_merge'] = 'both_first'

#merger all bulan
#pb_stb = pd.concat([Perlengkapan_Bayi_stb_1,merge_drop,merge_drop_2],ignore_index=True)

# perhitungan stock bayangan 
# All both
#pb_stb.loc[pb_stb['_merge'] == 'both_first', 'stock bayangan'] = pb_stb['Stock Awal']+pb_stb['Stock In']
#pb_stb.loc[pb_stb['_merge'] == 'both', 'stock bayangan'] = pb_stb['Stock In']
#pb_stb.loc[pb_stb['_merge'] == 'both', 'stock bayangan'] = pb_stb['Stock In']
# right only first
#pb_stb.loc[pb_stb['_merge'] == 'right_only_first', 'stock bayangan'] = pb_stb['Stock Awal']+pb_stb['Stock In']
# right only second
#pb_stb.loc[pb_stb['_merge'] == 'right_only_second', 'stock bayangan'] = pb_stb['Stock Awal']+pb_stb['Stock In']

In [126]:
pb_bulan_1 = pd.concat([Perlengkapan_Bayi_dkt_1,Perlengkapan_Bayi_lbg_1,Perlengkapan_Bayi_stb_1,Perlengkapan_Bayi_tki_1], ignore_index=True)
pb_bulan_2 = pd.concat([Perlengkapan_Bayi_dkt_2,Perlengkapan_Bayi_lbg_2,Perlengkapan_Bayi_stb_2,Perlengkapan_Bayi_tki_2], ignore_index=True)
pb_bulan_3 = pd.concat([Perlengkapan_Bayi_dkt_3,Perlengkapan_Bayi_lbg_3,Perlengkapan_Bayi_stb_3,Perlengkapan_Bayi_tki_3], ignore_index=True)

In [127]:
#create Df bulan 2
pb_merge_1 = pd.merge(pb_bulan_1,pb_bulan_2, how='outer' ,on=['Kode Barang'], indicator=True, suffixes=("_x", ""),)
pb_merge_1["_merge"].replace({"right_only": "right_only_first"}, inplace=True)
pb_merge_1_right = pb_merge_1.loc[pb_merge_1['_merge'] == 'right_only_first']
pb_merge_1_right = pb_merge_1_right.dropna(axis='columns')
pb_merge_concat_1 = pd.concat([pb_bulan_2,pb_merge_1_right])
pb_merge_concat_1['_merge'] = pb_merge_concat_1[['_merge']].fillna(value='both')
merge_drop = pb_merge_concat_1.drop_duplicates(subset=['Kode Barang'], keep='last')

#clean bahan df bulan 3
merge_drop_clean = merge_drop.iloc[:,0:23]

#create Df bulan 3
pb_merge_2 = pd.merge(merge_drop_clean,pb_bulan_3, how='outer' ,on=['Kode Barang'], indicator=True, suffixes=("_x", ""),)
pb_merge_2["_merge"].replace({"right_only": "right_only_second"}, inplace=True)
pb_merge_2_right = pb_merge_2.loc[pb_merge_2['_merge'] == 'right_only_second']
pb_merge_2_right = pb_merge_2_right.dropna(axis='columns')
pb_merge_concat_2 = pd.concat([pb_bulan_3,pb_merge_2_right])
pb_merge_concat_2['_merge'] = pb_merge_concat_2[['_merge']].fillna(value='both')
merge_drop_2 = pb_merge_concat_2.drop_duplicates(subset=['Kode Barang'], keep='last')

#finishing Df bulan 1
pb_bulan_1['_merge'] = 'both_first'

#merger all bulan
pb_all = pd.concat([pb_bulan_1,merge_drop,merge_drop_2],ignore_index=True)

# perhitungan stock bayangan 
# All both
pb_all.loc[pb_all['_merge'] == 'both_first', 'stock bayangan'] = pb_all['Stock Awal']+pb_all['Stock In']
pb_all.loc[pb_all['_merge'] == 'both', 'stock bayangan'] = pb_all['Stock In']
pb_all.loc[pb_all['_merge'] == 'both', 'stock bayangan'] = pb_all['Stock In']
# right only first
pb_all.loc[pb_all['_merge'] == 'right_only_first', 'stock bayangan'] = pb_all['Stock Awal']+pb_all['Stock In']
# right only second
pb_all.loc[pb_all['_merge'] == 'right_only_second', 'stock bayangan'] = pb_all['Stock Awal']+pb_all['Stock In']

In [128]:
#pb_all.to_csv(r'C:\Users\afriz\Documents\Pekerjaan\YENS\Monthly Project\Monthly Project\ready data set\Perlengkapan_Bayi_testing_modeling_5.csv', index=False)

In [129]:
all = pd.concat([mn_all,bb_all,food_all,tlt_all,kns_all,fa_all,fb_all,fd_all,acc_all,elk_all,stn_all,und_all,pa_all,pb_all], ignore_index=True)

In [130]:
all.tail()

4,Kode Barang,Barcode,Artikel,Nama Barang,Keterangan Barang,Input Barang,Supplier,Input Supplier,Sub Dept,Kelompok,Stock Awal,Stock In,Stock Out,Penjualan,Stock Akhir,Harga Beli,Harga Jual,Stock By Harga Beli,Stock By Harga Jual,Jumlah Penjualan,Value Stock IN(HJ),cabang,bulan,_merge,stock bayangan
307298,03031153,03031153,03031153,HDK MY EMILY JUMBO,NaN,2022-06-15,L SEJATI,2020-09-05,PERLENGKAPAN BAYI,HANDUK/WASHLAP/SAPU TANGAN,0,6,0,1,5,60000,79500,300000,397500,79500,477000,tki,6,right_only_second,6
307299,03040711,03040711,03040711,GURITA BABY POLOS,NaN,2022-06-27,L SEJATI,2020-09-05,PERLENGKAPAN BAYI,BEDONG/FLANEL/GURITA,0,12,0,0,12,12500,16500,150000,198000,0,198000,tki,6,right_only_second,12
307300,03120208,03120208,CN283,STD BANANA BRUSH,NaN,2022-06-04,JAYA HARAPAN PD,2020-09-05,PERLENGKAPAN BAYI,SIKAT GIGI/SIKAT BOTOL,0,1,0,0,1,21850,29500,21850,29500,0,29500,tki,6,right_only_second,1
307301,8110009,8110009,8110009,KASA STRIL HEXA 16X,NaN,2021-02-08,CENTRAL BANDUNG RAYA CBR,2020-09-05,PERLENGKAPAN BAYI,PERLENGKAPAN KESEHATAN,-11,0,0,0,-11,3549.7,4000,-39046.7,-44000,0,0,tki,6,right_only_second,-11
307302,8110011,8110011,8110011,KASA STERL GR HUSADA,NaN,2021-02-08,CENTRAL BANDUNG RAYA CBR,2020-09-05,PERLENGKAPAN BAYI,PERLENGKAPAN KESEHATAN,-1,0,0,0,-1,3939.1,4500,-3939.1,-4500,0,0,tki,6,right_only_second,-1

In [131]:
#all.to_excel(r'C:\Users\afriz\Documents\Pekerjaan\YENS\Monthly Project\Monthly Project\ready data set\all2.xlsx', index=False)

In [132]:
#all.to_csv(r'C:\Users\afriz\Documents\Pekerjaan\YENS\Monthly Project\Monthly Project\ready data set\all2.csv', index=False)

# Labeling Personal

In [133]:
#dflabel_local = pd.read_csv(r'C:\Users\afriz\Documents\Pekerjaan\YENS\Monthly Project\Monthly Project\ready data set\all2.csv')

In [134]:
dflabel = all.copy()
dflabel['hitungan stcok satu bulan akhir'] = 0
dflabel.loc[dflabel['bulan'] == '3', 'hitungan stcok satu bulan akhir'] = dflabel['Stock Awal'] + dflabel['Stock In']

In [135]:
dflabel_ratna = dflabel[(dflabel['Supplier']=='ADIWARNA TUNGGAL JAYA CV') |
(dflabel['Supplier']=='AKSAMALA') |
(dflabel['Supplier']=='ALJ TRADING INDONESIA PT / LEO JAYA UD') |
(dflabel['Supplier']=='ANEKA BARU') |
(dflabel['Supplier']=='ANTARMITRA SEMBADA PT') |
(dflabel['Supplier']=='ANUGERAH MITRA SENTOSA') |
(dflabel['Supplier']=='ANUGERAH PHARMINDO LESTARI PT') |
(dflabel['Supplier']=='ARYALINDO CENTRA FORTUNA PT / AGUNG LESTARI PD') |
(dflabel['Supplier']=='BABY EMPIRE') |
(dflabel['Supplier']=='BABY GO INC') |
(dflabel['Supplier']=='BABY GO INC PUTUS') |
(dflabel['Supplier']=='BAHTERA CIPTA RAGA PRIMA PT') |
(dflabel['Supplier']=='BALITA KITA') |
(dflabel['Supplier']=='BANCEUY TUNGGAL JAYA PT') |
(dflabel['Supplier']=='BAYI KIDDY BANDUNG PT / BAYI KIDDY INDONESIA PT') |
(dflabel['Supplier']=='BELITUNG MAKMUR') |
(dflabel['Supplier']=='BUMI SANWA JAYA') |
(dflabel['Supplier']=='BUNNY SUKSES SELALU PT') |
(dflabel['Supplier']=='CAHAYA SEJAHTERA W DODO / DODORINDO JAYA ABD') |
(dflabel['Supplier']=='CAHAYA SEJAHTERA WALUYA BAMBI /  AURUM LITINDO SEJAHTRA PT') |
(dflabel['Supplier']=='CAHAYA SEJAHTERA WALUYA CLARIES PT') |
(dflabel['Supplier']=='CAHAYA SEJAHTERA WALUYA PUKU2 PT') |
(dflabel['Supplier']=='CARROL BABY') |
(dflabel['Supplier']=='CENTRAL BANDUNG RAYA CBR') |
(dflabel['Supplier']=='DAYA MUDA AGUNG PT') |
(dflabel['Supplier']=='DISTRIVERSA BUANAMAS PT') |
(dflabel['Supplier']=='DOLPHIN BEBE') |
(dflabel['Supplier']=='DOS NI ROHA PT') |
(dflabel['Supplier']=='ENSEVAL PUTERA MEGATRANDING PT') |
(dflabel['Supplier']=='GEORGE BABY') |
(dflabel['Supplier']=='HANAROO') |
(dflabel['Supplier']=='HAPPY KEMIRI') |
(dflabel['Supplier']=='HOLYSON') |
(dflabel['Supplier']=='IBU ANAK SUKSES PT') |
(dflabel['Supplier']=='IDEAL INTERNASIONAL MANDIRI') |
(dflabel['Supplier']=='INDIPAR / TK SLAMET OBAT (TOKEM)') |
(dflabel['Supplier']=='INTI MEDIKA SARANA PT') |
(dflabel['Supplier']=='INTRASARI RAYA PT / GODREJ DISTRIBUTION INDONESIA PT') |
(dflabel['Supplier']=='JAYA HARAPAN PD') |
(dflabel['Supplier']=='JAZA VENUS BANDUNG CUSSONS CV / MALINDO CEMERLANG PRATAMA PT') |
(dflabel['Supplier']=='JJ COLLECTION') |
(dflabel['Supplier']=='KK INDONESIA') |
(dflabel['Supplier']=='KREASI SUKSES MAKMUR') |
(dflabel['Supplier']=='MAHAMERU MEKAR DJAYA / ALAMUI LOGISTICS CEPER LMT') |
(dflabel['Supplier']=='MAHARATI') |
(dflabel['Supplier']=='MAHARDIKA JUJUR MANDIRI PT') |
(dflabel['Supplier']=='MAJU BERSAMA KITA JAYA') |
(dflabel['Supplier']=='MARGA NUSANTARA JAYA PT') |
(dflabel['Supplier']=='MBS AVENT') |
(dflabel['Supplier']=='MEDAL Q') |
(dflabel['Supplier']=='MENSA BINA SUKSES BABY SAFE PT') |
(dflabel['Supplier']=='MENSA BINA SUKSES PT') |
(dflabel['Supplier']=='MITRA SUKSES BERSAMA DISTRIBUSINDO') |
(dflabel['Supplier']=='MIVI BABY SHOP') |
(dflabel['Supplier']=='MULTI ADHI TUNGGAL') |
(dflabel['Supplier']=='MULTITRENDINDO / MOTHERCARE MAAG NUBY') |
(dflabel['Supplier']=='MY BABY') |
(dflabel['Supplier']=='NISHIKAWA (BAYI KIDDY BANDUNG)') |
(dflabel['Supplier']=='ORENJI MAKMUR GEMILANG') |
(dflabel['Supplier']=='ORGANIK SEHAT ALAMI PT') |
(dflabel['Supplier']=='PANCA PILAR PERKASA') |
(dflabel['Supplier']=='PANJUNAN  EVEREADY PT') |
(dflabel['Supplier']=='PARIT PADANG GLOBAL PT') |
(dflabel['Supplier']=='PRODERMA SUKSES MANDIRI (WHOTO)') |
(dflabel['Supplier']=='PUTRA NIAGA LIGIENT') |
(dflabel['Supplier']=='PUTRA NIAGA TANWIN / PUTRA NIAGA PT') |
(dflabel['Supplier']=='ROYAL MITRA PRETAMA PUTUS PT') |
(dflabel['Supplier']=='SASANA MEGAH AGUNG PT/  SARANA ABADI MAKMUR BERSAMA PT') |
(dflabel['Supplier']=='SEMESTA DISTRIBUSI INDONESIA PT') |
(dflabel['Supplier']=='SHAZMEE YOOPIE') |
(dflabel['Supplier']=='SINAR KEMIRI') |
(dflabel['Supplier']=='SINAR KHANDAGA LESTARI CLAIRES') |
(dflabel['Supplier']=='SINERGI MULTI DISTRINDO PIGEON PT') |
(dflabel['Supplier']=='SURYA DONASIN / AMARA') |
(dflabel['Supplier']=='SURYA DONASIN / CATUR SENTOSA ANUGRAH PT') |
(dflabel['Supplier']=='SURYA DONASIN CAP LANG PT / UNIRAMA DUTA NIAGA') |
(dflabel['Supplier']=='SWISS NIAGA JAYA PT') |
(dflabel['Supplier']=='TATA NASIONAL MAKMUR SENTOSA PT / MALINDO CEMERLANG PT') |
(dflabel['Supplier']=='TEMPO PT') |
(dflabel['Supplier']=='TIGARAKSA SATRIA PT') |
(dflabel['Supplier']=='TKPN') |
(dflabel['Supplier']=='TNP') |
(dflabel['Supplier']=='UNIRAMA DUTA NIAGA PT') |
(dflabel['Supplier']=='WATERU NATURAL ALKALINDO PT') |
(dflabel['Supplier']=='WICAKSANA OVERSEAS PT') 
]

dflabel_ratna = dflabel[(dflabel['Sub Dept']=='TOILETRIES') |
(dflabel['Sub Dept']=='PERLENGKAPAN BAYI')
]

dfrank_ratna = dflabel_ratna[['Supplier','Penjualan','Jumlah Penjualan','stock bayangan']]
dfrank_ratna = dfrank_ratna.groupby(['Supplier']).sum()
dfrank_ratna = dfrank_ratna.reset_index()
dfrank_ratna['rank penjualan'] = dfrank_ratna['Penjualan'].rank(method='dense')
dfrank_ratna['rank value'] = dfrank_ratna['Jumlah Penjualan'].rank(method='dense')
dfrank_ratna['value rank'] = dfrank_ratna['rank penjualan']+dfrank_ratna['rank value']
dfrank_ratna['rank'] = dfrank_ratna['value rank'].rank(method='dense', ascending=False)

with pd.ExcelWriter(r'C:\Users\afriz\Documents\Pekerjaan\YENS\Monthly Project\Monthly Project\ready data set\purchasing\22_4_6_ratna.xlsx') as ratna:
    dflabel_ratna.to_excel(ratna, sheet_name = 'label', index = False)
    dfrank_ratna.to_excel(ratna, sheet_name = 'rank', index = False)

In [136]:
dflabel_vero = dflabel[(dflabel['Supplier']=='ADA DJADI CV') |
(dflabel['Supplier']=='AILSA') |
(dflabel['Supplier']=='AK GARMENT') |
(dflabel['Supplier']=='AKAR BERINGIN DISTRIBUSINDO CV') |
(dflabel['Supplier']=='ALIF MOESLIM KIDS') |
(dflabel['Supplier']=='ALPINIKA UNGGUL LIBBY') |
(dflabel['Supplier']=='ANAK MUSLIM') |
(dflabel['Supplier']=='ANDRO NATANAEL KOSASIH') |
(dflabel['Supplier']=='ANEKA BABY') |
(dflabel['Supplier']=='ANEKA BARU') |
(dflabel['Supplier']=='ANEKA GLOBAL INDONESIA PT') |
(dflabel['Supplier']=='ANGELINA KARTIKA TIMUR CEMERLANG PT') |
(dflabel['Supplier']=='ANUGRAH DAYA') |
(dflabel['Supplier']=='AZADA KIDS') |
(dflabel['Supplier']=='BABIES') |
(dflabel['Supplier']=='BABY GIGGLES') |
(dflabel['Supplier']=='BABY GRAB AXIS') |
(dflabel['Supplier']=='BABY OLIVE MALANG/KONSI-STR1') |
(dflabel['Supplier']=='BABY PANDA') |
(dflabel['Supplier']=='BABY WAYS') |
(dflabel['Supplier']=='BAKUL BATIK') |
(dflabel['Supplier']=='BEAUTIFUL FASHION') |
(dflabel['Supplier']=='BEBISO') |
(dflabel['Supplier']=='BEE KIDS') |
(dflabel['Supplier']=='BENIO') |
(dflabel['Supplier']=='BENS KIDDOS') |
(dflabel['Supplier']=='BERKAT SUKSES GEMILANG / KONSI-BERKAT SUKSES') |
(dflabel['Supplier']=='BERRY KIDS') |
(dflabel['Supplier']=='BERUANG EMAS CV') |
(dflabel['Supplier']=='BINGO BUGS') |
(dflabel['Supplier']=='BRIEL') |
(dflabel['Supplier']=='C REN HOUSE') |
(dflabel['Supplier']=='CAHAYA ABADI') |
(dflabel['Supplier']=='CAHAYA MITRA GARMENT') |
(dflabel['Supplier']=='CALISYA') |
(dflabel['Supplier']=='CAN-CAN FASHION') |
(dflabel['Supplier']=='CARISA C-1 NEW') |
(dflabel['Supplier']=='CARROL BABY') |
(dflabel['Supplier']=='CASTLE') |
(dflabel['Supplier']=='CBB CAHAYA BERKAT BERSAMA CV') |
(dflabel['Supplier']=='CERITA') |
(dflabel['Supplier']=='CERVIE') |
(dflabel['Supplier']=='CHERRY BABY') |
(dflabel['Supplier']=='CHILDREN HOUSE') |
(dflabel['Supplier']=='CIPTA MANDIRI / KONSI-CIPTA MANDIRI') |
(dflabel['Supplier']=='CLEVER KIDS') |
(dflabel['Supplier']=='COLA JEANS') |
(dflabel['Supplier']=='D-I COLLECTION') |
(dflabel['Supplier']=='DAYA CIPTA SAKTI') |
(dflabel['Supplier']=='DAZLE') |
(dflabel['Supplier']=='DELLA') |
(dflabel['Supplier']=='DELLA VITA') |
(dflabel['Supplier']=='DIANA') |
(dflabel['Supplier']=='DICK PRAKARSA BUSANA') |
(dflabel['Supplier']=='DREAM LAND / BEAUTIFUL DREAM LAND') |
(dflabel['Supplier']=='EFFATA BUANA LESTARI CV / GIAT JAYA') |
(dflabel['Supplier']=='EKRILO MULIA JAYA') |
(dflabel['Supplier']=='ELMESA MEGA MAKMUR PT') |
(dflabel['Supplier']=='EMPAT JAYA COLLECTION') |
(dflabel['Supplier']=='ERIN') |
(dflabel['Supplier']=='ERTIGA COLLECTION') |
(dflabel['Supplier']=='EXO') |
(dflabel['Supplier']=='EXODUS') |
(dflabel['Supplier']=='FELYS') |
(dflabel['Supplier']=='FIDO COLLECTION') |
(dflabel['Supplier']=='FIVE STARS') |
(dflabel['Supplier']=='FRIENDLY MAKMUR JAYA ABAD') |
(dflabel['Supplier']=='FUL') |
(dflabel['Supplier']=='GAGAN NUSA PERKASA') |
(dflabel['Supplier']=='GAGAPRO') |
(dflabel['Supplier']=='GANDA WIJAYA') |
(dflabel['Supplier']=='GARMINDO PERKASA/RIDGES') |
(dflabel['Supplier']=='GARUDA MAS') |
(dflabel['Supplier']=='GEORGE BABY') |
(dflabel['Supplier']=='GI-DAE') |
(dflabel['Supplier']=='GIFA PRODUCTION GEMILANG') |
(dflabel['Supplier']=='GIVING') |
(dflabel['Supplier']=='GOOD NIGHT') |
(dflabel['Supplier']=='GRAZIA INDONESIA PT (BUDI SUKMA)') |
(dflabel['Supplier']=='GREENGO') |
(dflabel['Supplier']=='GUDIM') |
(dflabel['Supplier']=='GUY VOTA') |
(dflabel['Supplier']=='H ANNAS') |
(dflabel['Supplier']=='HAMSTER') |
(dflabel['Supplier']=='HENNY COLLECTION A.I.U.E.O') |
(dflabel['Supplier']=='HENVIO') |
(dflabel['Supplier']=='HEPPINN KIDS') |
(dflabel['Supplier']=='HERS') |
(dflabel['Supplier']=='HOSHI KIDS WEAR') |
(dflabel['Supplier']=='HUGO COLLECTION') |
(dflabel['Supplier']=="IMA'S HABSY BATIK COLLECTION") |
(dflabel['Supplier']=='IMAGE PRODUCTION / SAY HELLO KIDS') |
(dflabel['Supplier']=='INDO KIDS') |
(dflabel['Supplier']=='IVAN ENNY') |
(dflabel['Supplier']=='JADI SUKSES MANDIRI') |
(dflabel['Supplier']=='JANFWU GARMENT') |
(dflabel['Supplier']=='JAYA HARAPAN PD') |
(dflabel['Supplier']=='JK  COLLECTION ') |
(dflabel['Supplier']=='JOBEN MAJU BERSAMA') |
(dflabel['Supplier']=='JOLEE') |
(dflabel['Supplier']=='JUNIOR HOUSE') |
(dflabel['Supplier']=='JUNIOR JUNGLE') |
(dflabel['Supplier']=='JUNIOR KIDS WEAR') |
(dflabel['Supplier']=='KALIKA') |
(dflabel['Supplier']=='KANEBO') |
(dflabel['Supplier']=='KARYA BHINEKA LESTARI') |
(dflabel['Supplier']=='KEZIO KIDS') |
(dflabel['Supplier']=='KHUMIKU') |
(dflabel['Supplier']=='KIDS SHOP') |
(dflabel['Supplier']=='KISS LAND') |
(dflabel['Supplier']=='LAVIOLA FASHION') |
(dflabel['Supplier']=='LEADING GARMENT') |
(dflabel['Supplier']=='LENA FASHION') |
(dflabel['Supplier']=='LEVANI / LEVANI ABADI') |
(dflabel['Supplier']=='LIE ROSE') |
(dflabel['Supplier']=='LIELIE FASHION') |
(dflabel['Supplier']=='LISNA KIDS') |
(dflabel['Supplier']=='LITTLE INK') |
(dflabel['Supplier']=='LIVIO') |
(dflabel['Supplier']=='LK FASHION') |
(dflabel['Supplier']=='LOOPIE KIDS') |
(dflabel['Supplier']=='M231') |
(dflabel['Supplier']=='MADISON MAE') |
(dflabel['Supplier']=='MAJESTY COLLECTION') |
(dflabel['Supplier']=='MAJU TERUS PIYAMA') |
(dflabel['Supplier']=='MAMI&ME') |
(dflabel['Supplier']=='ME AND MOM') |
(dflabel['Supplier']=='ME BEE') |
(dflabel['Supplier']=='MICHELLE II') |
(dflabel['Supplier']=='MIGUEL KIDS WEAR') |
(dflabel['Supplier']=='MINI SARI KEBAYA') |
(dflabel['Supplier']=='MINIME CHILDREN WHOLESALE') |
(dflabel['Supplier']=='MITRA SANDANG ABADI') |
(dflabel['Supplier']=='MODERN STYLE YOURS') |
(dflabel['Supplier']=='MODERN UD') |
(dflabel['Supplier']=='MOLLY POLLY') |
(dflabel['Supplier']=='MOM N BAB CV') |
(dflabel['Supplier']=='MOOI OFFICIAL') |
(dflabel['Supplier']=='MOON-MOON') |
(dflabel['Supplier']=='MULIA DAMAI SEJAHTERA PT') |
(dflabel['Supplier']=='NARY') |
(dflabel['Supplier']=='NEW KIDS') |
(dflabel['Supplier']=='NEW M') |
(dflabel['Supplier']=='NICE KIDS') |
(dflabel['Supplier']=='NIQITA') |
(dflabel['Supplier']=='NORINDO MAJU ARDA LEON PT') |
(dflabel['Supplier']=='NOVA') |
(dflabel['Supplier']=='OLIVE SHOP') |
(dflabel['Supplier']=='PAKIS LESTARI SENTOSA PT') |
(dflabel['Supplier']=='PAN FASHION') |
(dflabel['Supplier']=='PANCAMITRA ICHIGO JAYA CUSTOM PT') |
(dflabel['Supplier']=='PANCAMITRA ICHIGO JAYA PT') |
(dflabel['Supplier']=='PARISCO') |
(dflabel['Supplier']=='PERDANA  TOKO PECI') |
(dflabel['Supplier']=='PILAR DISTRIBUSINDO FASHION') |
(dflabel['Supplier']=='PITERTAN') |
(dflabel['Supplier']=='PKM') |
(dflabel['Supplier']=='PLAYFUL TOYS') |
(dflabel['Supplier']=='POM POM') |
(dflabel['Supplier']=='POPSCL BRANDEDKIDSWEAR') |
(dflabel['Supplier']=='PRIMA CITRA LESTARI') |
(dflabel['Supplier']=='PRIMA JAYA') |
(dflabel['Supplier']=='PUTRI COLLECTION') |
(dflabel['Supplier']=='REASON') |
(dflabel['Supplier']=='RYAN COLLECTION') |
(dflabel['Supplier']=='SAIRAM JAYA GEMILANG CV') |
(dflabel['Supplier']=='SAN GRACE') |
(dflabel['Supplier']=='SARANA MEGA FORTUNA FLUFFY PT') |
(dflabel['Supplier']=='SC KIDS') |
(dflabel['Supplier']=='SEIZA') |
(dflabel['Supplier']=='SEJAHTERA') |
(dflabel['Supplier']=='SERKA JAYA') |
(dflabel['Supplier']=='SERKAJAYA CUSTOM') |
(dflabel['Supplier']=='SETIABUDI JAYA') |
(dflabel['Supplier']=='SEVTA NUSA ENERGI PT (HUGGY)') |
(dflabel['Supplier']=='SINARSURYA INTERBUSANA PT / DROPY UD') |
(dflabel['Supplier']=='SLEEPA HOLIC') |
(dflabel['Supplier']=='SM KIDS') |
(dflabel['Supplier']=='SRI') |
(dflabel['Supplier']=='SRVL.JR') |
(dflabel['Supplier']=='SUPER GIRL') |
(dflabel['Supplier']=='SUPER KID') |
(dflabel['Supplier']=='SURPRISE') |
(dflabel['Supplier']=='SWEETIE FASHION') |
(dflabel['Supplier']=='SWEETY CEMPAKA') |
(dflabel['Supplier']=='TAURUS') |
(dflabel['Supplier']=='TEDI SEASONAL') |
(dflabel['Supplier']=='TODA KIDDY') |
(dflabel['Supplier']=='TOKO ANAK GROSIR') |
(dflabel['Supplier']=='TOKO BERKAH') |
(dflabel['Supplier']=='TOKO HARICO KIDS') |
(dflabel['Supplier']=='TOKO KIMMY') |
(dflabel['Supplier']=='TOKO LIEM') |
(dflabel['Supplier']=='TOKO LINDA ASEMKA') |
(dflabel['Supplier']=='TOKO SUN-LY') |
(dflabel['Supplier']=='TOMOMI BABY') |
(dflabel['Supplier']=='TOP UP') |
(dflabel['Supplier']=='TRIHOPE') |
(dflabel['Supplier']=='TWIN TIGER BABY') |
(dflabel['Supplier']=='TYPHOON CHILDREN WEAR') |
(dflabel['Supplier']=='VANEL') |
(dflabel['Supplier']=='VELVET JUNIOR / CV EVERGREEN BUANA') |
(dflabel['Supplier']=='VISTA MEGAH LESTARI') |
(dflabel['Supplier']=='WEI KIDS') |
(dflabel['Supplier']=='WIN BEE') |
(dflabel['Supplier']=='WINI ANGGREINI') |
(dflabel['Supplier']=='WINS COLLECTION') |
(dflabel['Supplier']=='YANS') |
(dflabel['Supplier']=='YASA KIDS') |
(dflabel['Supplier']=='YOKUCI BABY OLIVE KIRENA/KONSI YOKUCHI STR2') |
(dflabel['Supplier']=='ZIKRA') |
(dflabel['Supplier']=='ZOZO / KIDZO') 
]

dflabel_vero = dflabel[(dflabel['Kelompok']=='ATASAN BABY') |
(dflabel['Kelompok']=='BAWAHAN BABY') |
(dflabel['Kelompok']=='SETELAN BABY') |
(dflabel['Kelompok']=='JUMPER/DRESS') |
(dflabel['Kelompok']=='JAKET/SWEATER BABY') |
(dflabel['Kelompok']=='PIYAMA BABY/SLEEPWEAR') |
(dflabel['Kelompok']=='KAOS KAKI/SARUNG TANGAN BABY') |
(dflabel['Kelompok']=='SINGLET') |
(dflabel['Kelompok']=='POPOK BABY') |
(dflabel['Kelompok']=='ATASAN PEREMPUAN') |
(dflabel['Kelompok']=='BAWAHAN PEREMPUAN') |
(dflabel['Kelompok']=='SETELAN PEREMPUAN') |
(dflabel['Kelompok']=='JAKET/SWEATER PEREMPUAN') |
(dflabel['Kelompok']=='PIYAMA PEREMPUAN') |
(dflabel['Kelompok']=='DRESS/TERUSAN/OVERALL') |
(dflabel['Kelompok']=='LEGGING/MANSET') |
(dflabel['Kelompok']=='ATASAN LAKI-LAKI') |
(dflabel['Kelompok']=='BAWAHAN LAKI LAKI') |
(dflabel['Kelompok']=='SETELAN LAKI') |
(dflabel['Kelompok']=='JAKET/SWEATER LAKI') |
(dflabel['Kelompok']=='PIYAMA LAKI-LAKI') |
(dflabel['Kelompok']=='BAWAHAN UNISEX') |
(dflabel['Kelompok']=='SETELAN UNISEX') |
(dflabel['Kelompok']=='JAKET/SWEATER UNISEX') |
(dflabel['Kelompok']=='PIYAMA UNISEX') |
(dflabel['Kelompok']=='KAOS KAKI') |
(dflabel['Kelompok']=='MUSLIM PEREMPUAN') |
(dflabel['Kelompok']=='MUSLIM LAKI') |
(dflabel['Kelompok']=='KNEEPAD') |
(dflabel['Kelompok']=='KOSTUM') |
(dflabel['Kelompok']=='JAS/ROMPI') |
(dflabel['Kelompok']=='SAJADAH') |
(dflabel['Kelompok']=='TOPI') ]

dfrank_vero = dflabel_vero[['Supplier','Penjualan','Jumlah Penjualan','stock bayangan']]
dfrank_vero = dfrank_vero.groupby(['Supplier']).sum()
dfrank_vero = dfrank_vero.reset_index()
dfrank_vero['rank penjualan'] = dfrank_vero['Penjualan'].rank(method='dense')
dfrank_vero['rank value'] = dfrank_vero['Jumlah Penjualan'].rank(method='dense')
dfrank_vero['value rank'] = dfrank_vero['rank penjualan']+dfrank_vero['rank value']
dfrank_vero['rank'] = dfrank_vero['value rank'].rank(method='dense', ascending=False)

with pd.ExcelWriter(r'C:\Users\afriz\Documents\Pekerjaan\YENS\Monthly Project\Monthly Project\ready data set\purchasing\22_4_6_vero.xlsx') as vero:
    dflabel_vero.to_excel(vero, sheet_name = 'label', index = False)
    dfrank_vero.to_excel(vero, sheet_name = 'rank', index = False)

In [137]:
dflabel_yuki = dflabel[ (dflabel['Supplier']=='AB2 JEANS / HOCK FASHION') |
(dflabel['Supplier']=='ABADI SUMBER JAYA CV') |
(dflabel['Supplier']=='ACC FASHION DEWASA') |
(dflabel['Supplier']=='ADONIS FASHION DEWASA') |
(dflabel['Supplier']=='AFNAS FASHION DEWASA') |
(dflabel['Supplier']=='AGEN JAYA') |
(dflabel['Supplier']=='AGUNG JAYA / AGUNG JAYA NUGRAHA') |
(dflabel['Supplier']=='AK GARMENT') |
(dflabel['Supplier']=='AKEMI FASHION DEWASA') |
(dflabel['Supplier']=='ALBENO FASHION DEWASA') |
(dflabel['Supplier']=='ALENA FASHION DEWASA') |
(dflabel['Supplier']=='ALEXANDER UD') |
(dflabel['Supplier']=='ALISAN') |
(dflabel['Supplier']=='ALSENO') |
(dflabel['Supplier']=='ALTON OFFICIAL FASHION DEWASA') |
(dflabel['Supplier']=='AM COLLECTION FASHION DEWASA') |
(dflabel['Supplier']=='AMI FASHION DEWASA') |
(dflabel['Supplier']=='AND 1-2U FASHION DEWASA') |
(dflabel['Supplier']=='ANDO KURNIA JAYA') |
(dflabel['Supplier']=='ANEKA BERKAT') |
(dflabel['Supplier']=='ANEKA BUSANA') |
(dflabel['Supplier']=='ANEKA PELANGI FASHION DEWASA') |
(dflabel['Supplier']=='ANGEL COLECTION') |
(dflabel['Supplier']=='ANGEL JAYA GLOBALINDO') |
(dflabel['Supplier']=='AQQ FASHION DEWASA') |
(dflabel['Supplier']=='ATEK BATIK') |
(dflabel['Supplier']=='AURORA FASHION DEWASA') |
(dflabel['Supplier']=='AUSTIN') |
(dflabel['Supplier']=='BABY STAR') |
(dflabel['Supplier']=='BABY WANG SHOES') |
(dflabel['Supplier']=='BADAWAL COLLECTION') |
(dflabel['Supplier']=='BANANA BABY WEAR') |
(dflabel['Supplier']=='BANDUNG VICTORY') |
(dflabel['Supplier']=='BATIK CANTING') |
(dflabel['Supplier']=='BATIK RIZKY (PEKALONGAN)') |
(dflabel['Supplier']=='BATIK SUCI') |
(dflabel['Supplier']=='BATIK SUGI') |
(dflabel['Supplier']=='BAYI MILLIONER MAS PT') |
(dflabel['Supplier']=='BEBISO') |
(dflabel['Supplier']=='BELLEZA FASHION DEWASA') |
(dflabel['Supplier']=='BELLIN FASHION DEWASA') |
(dflabel['Supplier']=='BINTANG JAYA DANS UD') |
(dflabel['Supplier']=='BLESSING FASHION DEWASA') |
(dflabel['Supplier']=='BRYLEA FASHION DEWASA') |
(dflabel['Supplier']=='BUANA SARANA CV') |
(dflabel['Supplier']=='C&S FAHION DEWASA') |
(dflabel['Supplier']=='CAHAYA ABADI') |
(dflabel['Supplier']=='CAHAYA BERKAT SDL JPT') |
(dflabel['Supplier']=='CAHAYA MITRA GEMILANG') |
(dflabel['Supplier']=='CAN-CAN FASHION') |
(dflabel['Supplier']=='CASA MODE') |
(dflabel['Supplier']=='CASTLE') |
(dflabel['Supplier']=='CBB CAHAYA BERKAT BERSAMA CV') |
(dflabel['Supplier']=='CDA COLLECTION') |
(dflabel['Supplier']=='CENTRAL MULIA') |
(dflabel['Supplier']=='CHIC FASHION') |
(dflabel['Supplier']=='CITRA BARU') |
(dflabel['Supplier']=='CLARKE FASHION DEWASA') |
(dflabel['Supplier']=='COVERAGE FASHION DEWASA') |
(dflabel['Supplier']=='CRYSTALITE DEWASA') |
(dflabel['Supplier']=='CYGNUS MODERN INDONESIA') |
(dflabel['Supplier']=='DANDELION FASHION DEWASA') |
(dflabel['Supplier']=='DANTE FASHION DEWASA') |
(dflabel['Supplier']=='DD DANIEL') |
(dflabel['Supplier']=='DE MODE') |
(dflabel['Supplier']=='DEO BAGS') |
(dflabel['Supplier']=='DUCHESS FASHION DEWASA') |
(dflabel['Supplier']=='DUNIA DOMPET DEWASA') |
(dflabel['Supplier']=='EGA BATIK (PEKALONGAN)') |
(dflabel['Supplier']=='ERA FASHION DEWASA') |
(dflabel['Supplier']=='ERIN') |
(dflabel['Supplier']=='EXCEL FASHION DEWASA') |
(dflabel['Supplier']=='EXITO FASHION DEWASA') |
(dflabel['Supplier']=='FAI STAR FASHION DEWASA') |
(dflabel['Supplier']=='FAMILY FASHION DEWASA') |
(dflabel['Supplier']=='FARIZ DEWASA') |
(dflabel['Supplier']=='FEECHIAS FASHION DEWASA') |
(dflabel['Supplier']=='FLOATING FASHION DEWASA') |
(dflabel['Supplier']=='FOLLOW ME FASHION DEWASA') |
(dflabel['Supplier']=='GARMINO FASHION DEWASA') |
(dflabel['Supplier']=='GAYANDA ') |
(dflabel['Supplier']=='GENES BATIK (PEKALONGAN)') |
(dflabel['Supplier']=='GIAT GARMENT JAYA') |
(dflabel['Supplier']=='GIAT JAYA') |
(dflabel['Supplier']=='GIFA PRODUCTION GEMILANG') |
(dflabel['Supplier']=='GJ COLLECTION') |
(dflabel['Supplier']=='GLOWS FASHION DEWASA') |
(dflabel['Supplier']=='GREEN ONE FASHION DEWASA') |
(dflabel['Supplier']=='HACE SUNRISE PT') |
(dflabel['Supplier']=='HACE SUNRISE PT/ KONNICHIWA') |
(dflabel['Supplier']=='HANJAYA') |
(dflabel['Supplier']=='HAWAII 2 DEWASA') |
(dflabel['Supplier']=='HERRA FASHION DEWASA') |
(dflabel['Supplier']=='HIMALAYA DEWASA') |
(dflabel['Supplier']=='HJ IMING') |
(dflabel['Supplier']=='HOFU DEWASA') |
(dflabel['Supplier']=='HONGKONG FASHION DEWASA') |
(dflabel['Supplier']=='HR CHENLY FASHION DEWASA') |
(dflabel['Supplier']=='I LUVA FASHION') |
(dflabel['Supplier']=='IBU JENY') |
(dflabel['Supplier']=='ID PROJECT') |
(dflabel['Supplier']=='IDA TAS DEWASA') |
(dflabel['Supplier']=='ILUVA FASHION DEWASA') |
(dflabel['Supplier']=='IMMANUEL KNITING CV') |
(dflabel['Supplier']=='INDOMODE PERKASA') |
(dflabel['Supplier']=='INEZ COLLECTION') |
(dflabel['Supplier']=='INEZ FASHION DEWASA') |
(dflabel['Supplier']=='INNOVA FASHION DEWASA') |
(dflabel['Supplier']=='ISTANA FASHION DEWASA') |
(dflabel['Supplier']=='ITALY FASHION DEWASA') |
(dflabel['Supplier']=='IVLY PUTUS / BUANA KREASI DJAJA CEMERLANG') |
(dflabel['Supplier']=='JAYA SENTOSA') |
(dflabel['Supplier']=='JEREMY BABY SHOES PT / JEREMY MAKMUR BERSAMA  PT') |
(dflabel['Supplier']=='JOBEN MAJU BERSAMA') |
(dflabel['Supplier']=='JONATHAN DOMPET') |
(dflabel['Supplier']=='JOVI FASHION DEWASA') |
(dflabel['Supplier']=='JUIZ DESIGN FASHION DEWASA') |
(dflabel['Supplier']=='JUNBERRY FASHION DEWASA') |
(dflabel['Supplier']=='KANEBO') |
(dflabel['Supplier']=='KARUNIA MAJU CV') |
(dflabel['Supplier']=='KAYIE MODA FASHION DEWASA') |
(dflabel['Supplier']=='KENCANA UNGU DEWASA') |
(dflabel['Supplier']=='KIMBERLY FASHION DEWASA') |
(dflabel['Supplier']=='KITTEN FASHION DEWASA') |
(dflabel['Supplier']=='KREASI SUKSES MAKMUR') |
(dflabel['Supplier']=='L SEJATI') |
(dflabel['Supplier']=='L SEJATI SEASONAL') |
(dflabel['Supplier']=='LAVERE FASHION DEWASA') |
(dflabel['Supplier']=='LECASO DENIM FASHION DEWASA') |
(dflabel['Supplier']=='LEGAND FASHION DEWASA') |
(dflabel['Supplier']=='LIELIE FASHION') |
(dflabel['Supplier']=='LILI FASHION') |
(dflabel['Supplier']=='LINDA FASHION DEWASA') |
(dflabel['Supplier']=='LITTLE PRINCE') |
(dflabel['Supplier']=='LIVINA FASHION DEWASA') |
(dflabel['Supplier']=='LOLY FASHION DEWASA') |
(dflabel['Supplier']=='LONG FASHION DEWASA') |
(dflabel['Supplier']=='LOOKS FASHION DEWASA') |
(dflabel['Supplier']=='LOVE BAG / CHANDRA JAYA FASHION DEWASA') |
(dflabel['Supplier']=='LUPITA FASHION DEWASA') |
(dflabel['Supplier']=='M2M FASHION DEWASA') |
(dflabel['Supplier']=='MAJESTY COLLECTION') |
(dflabel['Supplier']=='MAJU TERUS PIYAMA') |
(dflabel['Supplier']=='MAOO SHOES') |
(dflabel['Supplier']=='MASHAA ID_PASHMINA') |
(dflabel['Supplier']=='MASSA BARU FASHION DEWASA') |
(dflabel['Supplier']=='MAVIS / AZURI') |
(dflabel['Supplier']=='ME AND MOM') |
(dflabel['Supplier']=='METISSA') |
(dflabel['Supplier']=='MIAMORE FASHION DEWASA') |
(dflabel['Supplier']=='MINIME CHILDREN WHOLESALE') |
(dflabel['Supplier']=='MISS CHAIHONG FASHION DEWASA') |
(dflabel['Supplier']=='MONALISA') |
(dflabel['Supplier']=='MORENZA FASHION DEWASA') |
(dflabel['Supplier']=='MSH FASHION DEWASA') |
(dflabel['Supplier']=='MUFFIN FASHION DEWASA') |
(dflabel['Supplier']=='MURTIS DEWASA') |
(dflabel['Supplier']=='MY DREAM BJ HAMIL') |
(dflabel['Supplier']=='NAP BY HEDON FASHION DEWASA') |
(dflabel['Supplier']=='NATHANIAH FASHION DEWASA') |
(dflabel['Supplier']=='NCC FASHION DEWASA') |
(dflabel['Supplier']=='NEW AMENG 1') |
(dflabel['Supplier']=='NEW LIBERTY FASHION DEWASA') |
(dflabel['Supplier']=='NEW SEERA FASHION DEWASA') |
(dflabel['Supplier']=='NIKKO MODE DEWASA') |
(dflabel['Supplier']=='NIRWAN BATIK (PEKALONGAN)') |
(dflabel['Supplier']=='NOONA') |
(dflabel['Supplier']=='NOVA') |
(dflabel['Supplier']=='NOVA BATIK (PEKALONGAN)') |
(dflabel['Supplier']=='OCLO FASHION DEWASA') |
(dflabel['Supplier']=='OF COURSE FASHION DEWASA') |
(dflabel['Supplier']=='OLLANDA COLLECTION') |
(dflabel['Supplier']=='ORENJI MAKMUR GEMILANG') |
(dflabel['Supplier']=='ORENZ') |
(dflabel['Supplier']=='ORIGINAL FASHION DEWASA') |
(dflabel['Supplier']=='ORLANDO FASHION DEWASA') |
(dflabel['Supplier']=='OTANI FASHION DEWASA') |
(dflabel['Supplier']=='OZARA FASHION DEWASA') |
(dflabel['Supplier']=='PAKURAZI') |
(dflabel['Supplier']=='PANCAMITRA ICHIGO JAYA PT') |
(dflabel['Supplier']=='PANGERAN STORE FASHION DEWASA') |
(dflabel['Supplier']=='POETRI MURTIS') |
(dflabel['Supplier']=='POLO COUNTRY') |
(dflabel['Supplier']=='POPSTAR FASHION DEWASA') |
(dflabel['Supplier']=='PRATAMA SEJAHTERA MANUNGGAL PT') |
(dflabel['Supplier']=='PRETTY SHOP FASHION DEWASA') |
(dflabel['Supplier']=='QONITA BATIK (PEKALONGAN)') |
(dflabel['Supplier']=='QONNOQ') |
(dflabel['Supplier']=='QS FASHION DEWASA') |
(dflabel['Supplier']=='QUEEN DEWASA') |
(dflabel['Supplier']=='QUEEN MARDA FASHION DEWASA') |
(dflabel['Supplier']=='QUEENTIN FASHION DEWASA') |
(dflabel['Supplier']=='QUILLAVERS FASHION DEWASA') |
(dflabel['Supplier']=='RED ONE FASHION DEWASA') |
(dflabel['Supplier']=='REJEKI JAYA') |
(dflabel['Supplier']=='RIX FASHION DEWASA') |
(dflabel['Supplier']=='RIYU STYLE FASHION DEWASA') |
(dflabel['Supplier']=='RIZIQ BATIK') |
(dflabel['Supplier']=='RO01') |
(dflabel['Supplier']=='SANDANG JAYA MAKMUR') |
(dflabel['Supplier']=='SAUDARA FASHION DEWASA') |
(dflabel['Supplier']=='SEIKO COLLECTION') |
(dflabel['Supplier']=='SEMOGA SELALU GEMILANG PT') |
(dflabel['Supplier']=='SEPATU CLOE') |
(dflabel['Supplier']=='SERKA JAYA') |
(dflabel['Supplier']=='SETIABUDI JAYA') |
(dflabel['Supplier']=='SHAKIRA FASHION DEWASA') |
(dflabel['Supplier']=='SHERLEEN FASHION DEWASA') |
(dflabel['Supplier']=='SHINE & GLOW FASHION DEWASA') |
(dflabel['Supplier']=='SHINING FASHION DEWASA') |
(dflabel['Supplier']=='SHOES REPUBLIC') |
(dflabel['Supplier']=='SINAR PRATAMA AGUNG PT / BALMORAL') |
(dflabel['Supplier']=='SM KIDS') |
(dflabel['Supplier']=='SONIA FASHION DEWASA') |
(dflabel['Supplier']=='STARLA') |
(dflabel['Supplier']=='SUPPLIER MAINTENANCE') |
(dflabel['Supplier']=='SURYA') |
(dflabel['Supplier']=='SURYA FASHION DEWASA') |
(dflabel['Supplier']=='SYAHRINA BATIK (PEKALONGAN)') |
(dflabel['Supplier']=='SYLL RATNASARI FASHION DEWASA') |
(dflabel['Supplier']=='TAS PREMIUM') |
(dflabel['Supplier']=='TEDI SEASONAL') |
(dflabel['Supplier']=='THE POWER FASHION DEWASA') |
(dflabel['Supplier']=='TIRTA SARI (PEKALONGAN)') |
(dflabel['Supplier']=='TOKO ANGEL FASHION DEWASA') |
(dflabel['Supplier']=='TOKO EMILY FASHION DEWASA') |
(dflabel['Supplier']=='TOKO FASHION ASEMKA') |
(dflabel['Supplier']=='TOKO JAYA SENTOSA FASHION DEWASA') |
(dflabel['Supplier']=='TOKO JILL FASHION DEWASA') |
(dflabel['Supplier']=='TOKO LG FASHION DEWASA') |
(dflabel['Supplier']=='TOKO SOLO FASHION DEWASA') |
(dflabel['Supplier']=='TOP FASHION') |
(dflabel['Supplier']=='TOSCA FASHION DEWASA') |
(dflabel['Supplier']=='TURE JEANS FASHION DEWASA') |
(dflabel['Supplier']=='VALKEZ MODE FASHION DEWASA') |
(dflabel['Supplier']=='VALUE FASHION DEWASA') |
(dflabel['Supplier']=='VERCLINE FASHION DEWASA') |
(dflabel['Supplier']=='VERVE COLLECTION FASHION DEWASA') |
(dflabel['Supplier']=='VIORY FASHION DEWASA') |
(dflabel['Supplier']=='VIRAL FASHION DEWASA') |
(dflabel['Supplier']=='VISTA MEGAH LESTARI') |
(dflabel['Supplier']=='VIVALDI FASHION DEWASA') |
(dflabel['Supplier']=='VIVERE') |
(dflabel['Supplier']=='VIVI LYSSA FASHION DEWASA') |
(dflabel['Supplier']=='VOXY BIG FASHION DEWASA') |
(dflabel['Supplier']=='VOXY DEWASA') |
(dflabel['Supplier']=='WINDY FASHION DEWASA') |
(dflabel['Supplier']=='WUNAGO FASHION DEWASA') |
(dflabel['Supplier']=='WWW FASHION DEWASA') |
(dflabel['Supplier']=='XTREMZ') |
(dflabel['Supplier']=='YIUYIE FASHION DEWASA') |
(dflabel['Supplier']=='YOKA FASHION DEWASA') |
(dflabel['Supplier']=='YOORA FASHION DEWASA') |
(dflabel['Supplier']=='YOU COLLECTION FASHION DEWASA') |
(dflabel['Supplier']=='YUNA FASHION DEWASA') |
(dflabel['Supplier']=='YURI FASHION DEWASA') |
(dflabel['Supplier']=='ZEFAYA FASHION DEWASA') 
]

dflabel_yuki = dflabel[(dflabel['Kelompok']=='ATASAN DEWASA') |
(dflabel['Kelompok']=='BAWAHAN DEWASA') |
(dflabel['Kelompok']=='DRESS DEWASA') |
(dflabel['Kelompok']=='JAKET/SWEATER/OUTHER DEWASA') |
(dflabel['Kelompok']=='KERUDUNG/TOPI DEWASA') |
(dflabel['Kelompok']=='MUSLIM DEWASA') |
(dflabel['Kelompok']=='SETELAN DEWASA') |
(dflabel['Kelompok']=='MANSET/LEGGING DEWASA') |
(dflabel['Kelompok']=='TAS DEWASA') |
(dflabel['Kelompok']=='DOMPET') |
(dflabel['Kelompok']=='SENDAL DEWASA') |
(dflabel['Kelompok']=='SEPATU/SANDAL BABY') |
(dflabel['Kelompok']=='SEPATU/SANDAL LAKI-LAKI') |
(dflabel['Kelompok']=='SEPATU/SANDAL PEREMPUAN') |
(dflabel['Kelompok']=='SEPATU/SANDAL UNISEX') |
((dflabel['Supplier']=='LITTLE PRINCE') & (dflabel['Kelompok']=='ATASAN PEREMPUAN')) |
((dflabel['Supplier']=='LITTLE PRINCE') & (dflabel['Kelompok']=='DRESS/TERUSAN/OVERALL')) |
((dflabel['Supplier']=='LITTLE PRINCE') & (dflabel['Kelompok']=='LEGGING/MANSET')) |
((dflabel['Supplier']=='LITTLE PRINCE') & (dflabel['Kelompok']=='ATASAN LAKI-LAKI')) |
((dflabel['Supplier']=='LITTLE PRINCE') & (dflabel['Kelompok']=='BAWAHAN LAKI LAKI')) |
((dflabel['Supplier']=='LITTLE PRINCE') & (dflabel['Kelompok']=='ATASAN UNISEX')) |
((dflabel['Supplier']=='LITTLE PRINCE') & (dflabel['Kelompok']=='BAWAHAN UNISEX')) |
((dflabel['Supplier']=='LITTLE PRINCE') & (dflabel['Kelompok']=='SETELAN UNISEX')) |
((dflabel['Supplier']=='LITTLE PRINCE') & (dflabel['Kelompok']=='PIYAMA UNISEX')) |
((dflabel['Supplier']=='LITTLE PRINCE') & (dflabel['Kelompok']=='KAOS KAKI')) |
((dflabel['Supplier']=='LITTLE PRINCE') & (dflabel['Kelompok']=='MUSLIM PEREMPUAN')) |
((dflabel['Supplier']=='LITTLE PRINCE') & (dflabel['Kelompok']=='BAWAHAN PEREMPUAN')) |
((dflabel['Supplier']=='LITTLE PRINCE') & (dflabel['Kelompok']=='MUSLIM LAKI')) |
((dflabel['Supplier']=='LITTLE PRINCE') & (dflabel['Kelompok']=='JAKET/SWEATER PEREMPUAN')) |
((dflabel['Supplier']=='LITTLE PRINCE') & (dflabel['Kelompok']=='SETELAN LAKI')) |
((dflabel['Supplier']=='LITTLE PRINCE') & (dflabel['Kelompok']=='JAKET/SWEATER UNISEX')) |
((dflabel['Supplier']=='LITTLE PRINCE') & (dflabel['Kelompok']=='SAJADAH')) |
((dflabel['Supplier']=='LITTLE PRINCE') & (dflabel['Kelompok']=='BAWAHAN BABY')) |
((dflabel['Supplier']=='LITTLE PRINCE') & (dflabel['Kelompok']=='SETELAN BABY')) |
((dflabel['Supplier']=='LITTLE PRINCE') & (dflabel['Kelompok']=='JUMPER/DRESS')) |
((dflabel['Supplier']=='LITTLE PRINCE') & (dflabel['Kelompok']=='JAKET/SWEATER BABY')) |
((dflabel['Supplier']=='LITTLE PRINCE') & (dflabel['Kelompok']=='PIYAMA BABY/SLEEPWEAR')) |
((dflabel['Supplier']=='LITTLE PRINCE') & (dflabel['Kelompok']=='KAOS KAKI/SARUNG TANGAN BABY')) |
((dflabel['Supplier']=='LITTLE PRINCE') & (dflabel['Kelompok']=='POPOK BABY')) |
((dflabel['Supplier']=='LITTLE PRINCE') & (dflabel['Kelompok']=='ATASAN BABY')) |
((dflabel['Supplier']=='LITTLE PRINCE') & (dflabel['Kelompok']=='SETELAN DEWASA')) |
((dflabel['Supplier']=='LITTLE PRINCE') & (dflabel['Kelompok']=='PIYAMA IBU/DASTER')) |
((dflabel['Supplier']=='LITTLE PRINCE') & (dflabel['Kelompok']=='MUSLIM DEWASA')) |
((dflabel['Supplier']=='LITTLE PRINCE') & (dflabel['Kelompok']=='MASKER')) |
((dflabel['Supplier']=='LITTLE PRINCE') & (dflabel['Kelompok']=='TOPI')) |
((dflabel['Supplier']=='LITTLE PRINCE') & (dflabel['Kelompok']=='KALUNG/JEPIT/BANDANA/DASI')) |
((dflabel['Supplier']=='LITTLE PRINCE') & (dflabel['Kelompok']=='HANDUK/WASHLAP/SAPU TANGAN')) |
((dflabel['Supplier']=='LITTLE PRINCE') & (dflabel['Kelompok']=='BEDONG/FLANEL/GURITA')) |
((dflabel['Supplier']=='LITTLE PRINCE') & (dflabel['Kelompok']=='PERLAK'))
]

dfrank_yuki = dflabel_yuki[['Supplier','Penjualan','Jumlah Penjualan','stock bayangan']]
dfrank_yuki = dfrank_yuki.groupby(['Supplier']).sum()
dfrank_yuki = dfrank_yuki.reset_index()
dfrank_yuki['rank penjualan'] = dfrank_yuki['Penjualan'].rank(method='dense')
dfrank_yuki['rank value'] = dfrank_yuki['Jumlah Penjualan'].rank(method='dense')
dfrank_yuki['value rank'] = dfrank_yuki['rank penjualan']+dfrank_yuki['rank value']
dfrank_yuki['rank'] = dfrank_yuki['value rank'].rank(method='dense', ascending=False)

with pd.ExcelWriter(r'C:\Users\afriz\Documents\Pekerjaan\YENS\Monthly Project\Monthly Project\ready data set\purchasing\22_4_6_yuki.xlsx') as yuki:
    dflabel_yuki.to_excel(yuki, sheet_name = 'label', index = False)
    dfrank_yuki.to_excel(yuki, sheet_name = 'rank', index = False)

In [138]:
dflabel_april = dflabel[(dflabel['Supplier']=='ACCOSTA SUPER FOOD PT') |
(dflabel['Supplier']=='AGEN JAYA') |
(dflabel['Supplier']=='ANEKA TOYS') |
(dflabel['Supplier']=='ANJAYA SEJATI / TK KAWI AGUNG') |
(dflabel['Supplier']=='AWIDI ASEMKA') |
(dflabel['Supplier']=='BANDUNG VICTORY') |
(dflabel['Supplier']=='BARIEL & CO') |
(dflabel['Supplier']=='BINTANG PRIMA') |
(dflabel['Supplier']=='BUNNY SUKSES SELALU PT') |
(dflabel['Supplier']=='CITRA SASTRA NOVELTIS') |
(dflabel['Supplier']=='EKA BONEKA') |
(dflabel['Supplier']=='EMWAY GLOBALINDO PT') |
(dflabel['Supplier']=='ERA RAFI ASEMKA') |
(dflabel['Supplier']=='FRANGKI CHANDRA ASEMKA') |
(dflabel['Supplier']=='GOW N GOW / KURNIA PUTRA PERKASA TOYS') |
(dflabel['Supplier']=='HERO INTI PUTRA PT') |
(dflabel['Supplier']=='IMMANUEL KNITING CV') |
(dflabel['Supplier']=='INDOTOYS') |
(dflabel['Supplier']=='JAYA ABADI TOYS') |
(dflabel['Supplier']=='JIWA BINTANG USAHA CV') |
(dflabel['Supplier']=='JUSTIN TOYS ASEMKA') |
(dflabel['Supplier']=='JUVINHKW') |
(dflabel['Supplier']=='KONSEP GLOBAL MEDIA CV') |
(dflabel['Supplier']=='LOVELY BEAR') |
(dflabel['Supplier']=='NABILA ACESSORIES') |
(dflabel['Supplier']=='NONOKO') |
(dflabel['Supplier']=='PELANGI TOYS') |
(dflabel['Supplier']=='RAINBOW ACCESSORIES ASEMKA') |
(dflabel['Supplier']=='ROSE ACC ASEMKA') |
(dflabel['Supplier']=='ROWLING OFFICIAL') |
(dflabel['Supplier']=='SAMUDRA TOYS INDONESIA') |
(dflabel['Supplier']=='SAMUDRA TOYS INDONESIA (HOTWHEELS)') |
(dflabel['Supplier']=='SHELIA TOYS') |
(dflabel['Supplier']=='SINERGI MULTI DISTRINDO HOT WHEELS PT') |
(dflabel['Supplier']=='STAR TOY') |
(dflabel['Supplier']=='SUKSES MEGAH ABADI PT') |
(dflabel['Supplier']=='SURYA KENCANA ARTA INDAH PT') |
(dflabel['Supplier']=='TERANG DUNIA TOYS / PUTRA JAYA SUKSES GEMILANG PT') |
(dflabel['Supplier']=='TOSYEN OKTA PRIMA PT') |
(dflabel['Supplier']=='TRENDYLAND / CHARACTERLAND') |
(dflabel['Supplier']=='TRISINAR INDOPRATAMA PT') |
(dflabel['Supplier']=='YOGIKA SPORT') |
(dflabel['Supplier']=='YOPI BONEKA ANNISA') 
]

dflabel_april = dflabel[(dflabel['Kelompok']=='MAINAN BOY') |
(dflabel['Kelompok']=='MAINAN GIRL') |
(dflabel['Kelompok']=='MAINAN UMUM') |
(dflabel['Kelompok']=='PELAMPUNG/VEST') |
(dflabel['Kelompok']=='TUMBLR/BOTOL/LUNCBOX') |
(dflabel['Kelompok']=='FEEDING SET') |
(dflabel['Kelompok']=='KACAMATA') |
(dflabel['Kelompok']=='ACCECORIES') |
(dflabel['Kelompok']=='KALUNG/JEPIT/BANDANA/DASI') |
(dflabel['Kelompok']=='KACAMATA RENANG')
]

dfrank_april = dflabel_april[['Supplier','Penjualan','Jumlah Penjualan','stock bayangan']]
dfrank_april = dfrank_april.groupby(['Supplier']).sum()
dfrank_april = dfrank_april.reset_index()
dfrank_april['rank penjualan'] = dfrank_april['Penjualan'].rank(method='dense')
dfrank_april['rank value'] = dfrank_april['Jumlah Penjualan'].rank(method='dense')
dfrank_april['value rank'] = dfrank_april['rank penjualan']+dfrank_april['rank value']
dfrank_april['rank'] = dfrank_april['value rank'].rank(method='dense', ascending=False)

with pd.ExcelWriter(r'C:\Users\afriz\Documents\Pekerjaan\YENS\Monthly Project\Monthly Project\ready data set\purchasing\22_4_6_april.xlsx') as april:
    dflabel_april.to_excel(april, sheet_name = 'label', index = False)
    dfrank_april.to_excel(april, sheet_name = 'rank', index = False)

In [139]:
dflabel_ryan = dflabel[(dflabel['Supplier']=='ANGEL JAYA GLOBALINDO')|
(dflabel['Supplier']=='ANUGERAH EMPAT SAUDARA CV')|
(dflabel['Supplier']=='BABY CARE PUTUS / CIMUNCANG CV')|
(dflabel['Supplier']=='BABYBEE INDONESIA PT')|
(dflabel['Supplier']=='BAHTERA LAJU NUSANTARA PT')|
(dflabel['Supplier']=='BANGUN CITRA LESTARI')|
(dflabel['Supplier']=='BERKAT WIJAYA MULIA PT')|
(dflabel['Supplier']=='BERLIAN INTI CAHAYA CV')|
(dflabel['Supplier']=='CARROL BABY')|
(dflabel['Supplier']=='CIPTA GEMILANG ABADI CV (CRADLE DOODLE)')|
(dflabel['Supplier']=='DEN N JES')|
(dflabel['Supplier']=='DIALOGUE GARMINDO UTAMA PT')|
(dflabel['Supplier']=='DUNIA KIDO INDONESIA')|
(dflabel['Supplier']=='DWI SURYA PT')|
(dflabel['Supplier']=='GARUDA GRAHA UTAMA PT')|
(dflabel['Supplier']=='GISNIC NIAGA CEMERLANG')|
(dflabel['Supplier']=='HANDOKO INDO PACIFIC / CROWN INDONESIA PT')|
(dflabel['Supplier']=='HOKINA BABY')|
(dflabel['Supplier']=='IMMANUEL KNITING CV')|
(dflabel['Supplier']=='INDOSCOTS BABY UTAMA CV')|
(dflabel['Supplier']=='JEFFERYS INDONESIA PT')|
(dflabel['Supplier']=='KINDALIN UTAMA INTERNASIONAL PT')|
(dflabel['Supplier']=='KYRAKIDZ')|
(dflabel['Supplier']=='M2000')|
(dflabel['Supplier']=='MEGA VISI PRIMA JAYA PT (MEGATREND)')|
(dflabel['Supplier']=='MEGAH CASTELY UD / CASTELY BABYDOES PT')|
(dflabel['Supplier']=='MITRA MAKMUR LESTARI')|
(dflabel['Supplier']=='MULLAN CIPTA NUSANTARA PT')|
(dflabel['Supplier']=='MULTI ADHI TUNGGAL (BEDDING)')|
(dflabel['Supplier']=='PACIFIC INDAH PRATAMA PT')|
(dflabel['Supplier']=='RABAT ABADI JAYA PT')|
(dflabel['Supplier']=='RABAT ABADI JAYA PT / PUTERA RAJA SEJAHTERA PT')|
(dflabel['Supplier']=='ROSWELL MITRA PERKASA PT')|
(dflabel['Supplier']=='SKIDAMARINK')|
(dflabel['Supplier']=='SNI')|
(dflabel['Supplier']=='SUMBER JAYA II')|
(dflabel['Supplier']=='SUSUN 3 TOYS')|
(dflabel['Supplier']=='TIGA MAJU TERUS BB SMART PT')|
(dflabel['Supplier']=='TOMOKO')|
(dflabel['Supplier']=='WIM MOTOR PT')
]

dflabel_ryan = dflabel[(dflabel['Kelompok']=='BEDDING') |
(dflabel['Kelompok']=='FOLDING BATH') |
(dflabel['Kelompok']=='POTTY ') |
(dflabel['Kelompok']=='HANGER') |
(dflabel['Kelompok']=='STORAGE BOX') |
(dflabel['Sub Dept']=='BARANG BESAR')
]

dfrank_ryan = dflabel_ryan[['Supplier','Penjualan','Jumlah Penjualan','stock bayangan']]
dfrank_ryan = dfrank_ryan.groupby(['Supplier']).sum()
dfrank_ryan = dfrank_ryan.reset_index()
dfrank_ryan['rank penjualan'] = dfrank_ryan['Penjualan'].rank(method='dense')
dfrank_ryan['rank value'] = dfrank_ryan['Jumlah Penjualan'].rank(method='dense')
dfrank_ryan['value rank'] = dfrank_ryan['rank penjualan']+dfrank_ryan['rank value']
dfrank_ryan['rank'] = dfrank_ryan['value rank'].rank(method='dense', ascending=False)

with pd.ExcelWriter(r'C:\Users\afriz\Documents\Pekerjaan\YENS\Monthly Project\Monthly Project\ready data set\purchasing\22_4_6_ryan.xlsx') as ryan:
    dflabel_ryan.to_excel(ryan, sheet_name = 'label', index = False)
    dfrank_ryan.to_excel(ryan, sheet_name = 'rank', index = False)

In [140]:
dflabel_soimah = dflabel[(dflabel['Supplier']=='ADIWARNA TUNGGAL JAYA CV') |
(dflabel['Supplier']=='AFIS PRIMA PERDANA PT') |
(dflabel['Supplier']=='AMINDO ABADI SENTOSA PT') |
(dflabel['Supplier']=='ANTAR MITRA SEMBADA PT ( PLOSSA )') |
(dflabel['Supplier']=='BANCEUY TUNGGAL JAYA PT') |
(dflabel['Supplier']=='BEBILUCK') |
(dflabel['Supplier']=='BERKAH MANDIRI CV') |
(dflabel['Supplier']=='BERKAT WIJAYA MULIA PT') |
(dflabel['Supplier']=='CAHAYA INTI PUTRA SEJAHTERA PT') |
(dflabel['Supplier']=='CARLA ELVIRA BUDIYANTI /  BINTANG KIRANA SEJAHTERA PT') |
(dflabel['Supplier']=='DAPUR ABON') |
(dflabel['Supplier']=='DAYA MUDA AGUNG PT') |
(dflabel['Supplier']=='DINUS CIPTA MANDIRI') |
(dflabel['Supplier']=='DISTRIVERSA BUANAMAS PT') |
(dflabel['Supplier']=='EAST INDO FAIR TRADING PT') |
(dflabel['Supplier']=='ENSEVAL PUTERA MEGATRANDING BLACKMORES PT') |
(dflabel['Supplier']=='GEMPITA PANGAN INDONESIA PT') |
(dflabel['Supplier']=='GRACIA INDO UTAMA PT') |
(dflabel['Supplier']=='INTI BERKAT JAYA PT (IVENET)') |
(dflabel['Supplier']=='JAYA MAKMUR MANDIRI') |
(dflabel['Supplier']=='JENNY HELEN') |
(dflabel['Supplier']=='JUJUR CITRA SENTOSA CV') |
(dflabel['Supplier']=='KREASI SUKSES MAKMUR / VCO CONCOS') |
(dflabel['Supplier']=='MALIKI PUTRA FIRDAUS PT') |
(dflabel['Supplier']=='MANNA INDO LAKTA MAMA BEAR CV') |
(dflabel['Supplier']=='MARGA NUSANTARA (VITAMIN)') |
(dflabel['Supplier']=='MASUYA GRAHA TRIKENCANA PT') |
(dflabel['Supplier']=='MENSA BINA SUKSES PROMINA/TJ') |
(dflabel['Supplier']=='MITRA SUKSES BERSAMA DISTRIBUSINDO') |
(dflabel['Supplier']=='MONDIAL DINAMIKA RAHARJA PT') |
(dflabel['Supplier']=='ORGANIK SEHAT ALAMI PT') |
(dflabel['Supplier']=='PANCA PILAR PERKASA JAYA CV') |
(dflabel['Supplier']=='PANJUNAN PT') |
(dflabel['Supplier']=='PENTA VALENT') |
(dflabel['Supplier']=='PIO SOFT PUDDING') |
(dflabel['Supplier']=='REJEKI  TUJUH ALAM') |
(dflabel['Supplier']=='SINAR SOSRO PT') |
(dflabel['Supplier']=='SINARMAS') |
(dflabel['Supplier']=='SINERGI MULTI DISTRINDO PIGEON PT') |
(dflabel['Supplier']=='SURYA DONASIN / CATUR SENTOSA ANUGRAH PT') |
(dflabel['Supplier']=='SURYA DONASIN POCKY PT') |
(dflabel['Supplier']=='TEMPO PT') |
(dflabel['Supplier']=='TERANG KASIH MULIA CV') |
(dflabel['Supplier']=='TRIKARYA ABADI CV') |
(dflabel['Supplier']=='TRISTAR SUKSES MAKMUR APPLE MONKEY CV') |
(dflabel['Supplier']=='WANG WANG BABY MEAL BARN CV') |
(dflabel['Supplier']=='WICAKSANA OVERSEAS (VITAMIN)') |
(dflabel['Supplier']=='WYNETTES WALDEN INTERNATIONAL IMBOOST PT') 
]

dflabel_soimah = dflabel[((dflabel['Sub Dept']=='FOOD') | (dflabel['Kelompok']=='MAKANAN/SNACK/KALDU')) |
((dflabel['Sub Dept']=='FOOD') | (dflabel['Kelompok']=='SUSU/MINUMAN')) |
((dflabel['Sub Dept']=='ACCESORIES') & (dflabel['Kelompok']=='MASKER'))
]

dfrank_soimah = dflabel_soimah[['Supplier','Penjualan','Jumlah Penjualan','stock bayangan']]
dfrank_soimah = dfrank_soimah.groupby(['Supplier']).sum()
dfrank_soimah = dfrank_soimah.reset_index()
dfrank_soimah['rank penjualan'] = dfrank_soimah['Penjualan'].rank(method='dense')
dfrank_soimah['rank value'] = dfrank_soimah['Jumlah Penjualan'].rank(method='dense')
dfrank_soimah['value rank'] = dfrank_soimah['rank penjualan']+dfrank_soimah['rank value']
dfrank_soimah['rank'] = dfrank_soimah['value rank'].rank(method='dense', ascending=False)

with pd.ExcelWriter(r'C:\Users\afriz\Documents\Pekerjaan\YENS\Monthly Project\Monthly Project\ready data set\purchasing\22_4_6_soimah.xlsx') as soimah:
    dflabel_soimah.to_excel(soimah, sheet_name = 'label', index = False)
    dfrank_soimah.to_excel(soimah, sheet_name = 'rank', index = False)

In [141]:
dflabel_eri = dflabel[(dflabel['Supplier']=='AJUNSHOP OFFICIAL') |
(dflabel['Supplier']=='ALBA UNIVERSAL SENSI MASKER') |
(dflabel['Supplier']=='ANTAR MITRA SEMBADA PT ( PLOSSA )') |
(dflabel['Supplier']=='ANUGERAH CITRA LESTARI MASKER CV') |
(dflabel['Supplier']=='BALITA KITA') |
(dflabel['Supplier']=='BETADINE BU JENY') |
(dflabel['Supplier']=='BIBIN STORE ( SHOPEE OFFICIAL )') |
(dflabel['Supplier']=='ENSEVAL PUTERA MEGATRANDING BLACKMORES PT') |
(dflabel['Supplier']=='FIVE CARE MASKER') |
(dflabel['Supplier']=='GRACE BABY SHOP') |
(dflabel['Supplier']=='HDI CLOVER HONEY') |
(dflabel['Supplier']=='HUIOS DERMA CANTIKA PT') |
(dflabel['Supplier']=='INTEGRA MEDIA NUSANTARA PT') |
(dflabel['Supplier']=='INTI MEDIKA SARANA PT') |
(dflabel['Supplier']=='JAZA VENUS MASKER BAGUS CV') |
(dflabel['Supplier']=='KAIT EARLOOP CONNECTOR MASKER') |
(dflabel['Supplier']=='KAMPUNG KEARIFAN INDONESIA PT') |
(dflabel['Supplier']=='KENNIO HEALTHCARE OFFICIAL') |
(dflabel['Supplier']=='LAVME') |
(dflabel['Supplier']=='MENSA BINA SUKSES BABY SAFE PT') |
(dflabel['Supplier']=='MIRA PUTRA SINAR PERSADA PT') |
(dflabel['Supplier']=='PARIM OFFICIAL MASKER') |
(dflabel['Supplier']=='PEDIAKID') |
(dflabel['Supplier']=='PROVIT NUTRITION') |
(dflabel['Supplier']=='PUTRA NIAGA LIGIENT') |
(dflabel['Supplier']=='PUTRA NIAGA TANWIN / PUTRA NIAGA PT') |
(dflabel['Supplier']=='SARANA BINA PRATAMA') |
(dflabel['Supplier']=='SENSI MASKER') |
(dflabel['Supplier']=='SERAFTAMA KARYA AGUNG') |
(dflabel['Supplier']=='SINAR MAKMUR CV (MAKMUR BARU)') |
(dflabel['Supplier']=='SMART SECURITY') |
(dflabel['Supplier']=='SUMBERTAMA/CAMERA') |
(dflabel['Supplier']=='TATA NASIONAL MAKMUR SENTOSA PT / MALINDO CEMERLANG PT') |
(dflabel['Supplier']=='TRI BUWANA WINATRA DARYA') |
(dflabel['Supplier']=='UNITED DICO CITAS PT') |
(dflabel['Supplier']=='VERONICA VERENESIA WIPOL') |
(dflabel['Supplier']=='VIASHOPA HOLIC') |
(dflabel['Supplier']=='WAKAF DISTRIBUSI UTAMA') 
]

dflabel_eri = dflabel[(dflabel['Sub Dept']=='ELEKTRONIK') |
(dflabel['Kelompok']=='OBAT/VITAMIN/MADU') |
(dflabel['Kelompok']=='AIR DESINFECTAN') |
(dflabel['Kelompok']=='SANITIZER') |
(dflabel['Kelompok']=='MASKER') |
(dflabel['Kelompok']=='CICI BABY') |
(dflabel['Kelompok']=='COOL BABY') |
(dflabel['Kelompok']=='DOMEILAND') |
(dflabel['Kelompok']=='EXCELLENT KIDS WEAR') |
(dflabel['Kelompok']=='KINGS KIDS') |
(dflabel['Kelompok']=='MIMY BOYS') |
(dflabel['Kelompok']=='MINGSHENG') |
(dflabel['Kelompok']=='SHARK DONG YU') |
(dflabel['Kelompok']=='TONG BEI BEI') |
(dflabel['Kelompok']=='TONG YI') |
(dflabel['Kelompok']=='CI DOU GE') |
(dflabel['Kelompok']=='DOMEILAND') |
(dflabel['Kelompok']=='MINI WORLD') |
(dflabel['Kelompok']=='WENNY FULI') 
]

dfrank_eri = dflabel_eri[['Supplier','Penjualan','Jumlah Penjualan','stock bayangan']]
dfrank_eri = dfrank_eri.groupby(['Supplier']).sum()
dfrank_eri = dfrank_eri.reset_index()
dfrank_eri['rank penjualan'] = dfrank_eri['Penjualan'].rank(method='dense')
dfrank_eri['rank value'] = dfrank_eri['Jumlah Penjualan'].rank(method='dense')
dfrank_eri['value rank'] = dfrank_eri['rank penjualan']+dfrank_eri['rank value']
dfrank_eri['rank'] = dfrank_eri['value rank'].rank(method='dense', ascending=False)

with pd.ExcelWriter(r'C:\Users\afriz\Documents\Pekerjaan\YENS\Monthly Project\Monthly Project\ready data set\purchasing\22_4_6_eri.xlsx') as eri:
    dflabel_eri.to_excel(eri, sheet_name = 'label', index = False)
    dfrank_eri.to_excel(eri, sheet_name = 'rank', index = False)

In [142]:
dflabel1 = dflabel.copy()

In [143]:
dflabel_luis = dflabel[ (dflabel['Supplier']=='KONSI- KARTIKA FOOD') |
(dflabel['Supplier']=='KONSI- KITOSHINDO BIRTH BEYOND') |
(dflabel['Supplier']=='KONSI- WANARA CREATIVE DESIGN') |
(dflabel['Supplier']=='KONSI-2 JAYA BANDUNG') |
(dflabel['Supplier']=='KONSI-ACTIVE MOVE') |
(dflabel['Supplier']=='KONSI-AEVUMLAB HERBA ASIA') |
(dflabel['Supplier']=='KONSI-AIFA COLL DEWASA') |
(dflabel['Supplier']=='KONSI-AKSAMALA ADI ANDANA PT') |
(dflabel['Supplier']=='KONSI-ALAMII NATURA SEJAHTERA PT') |
(dflabel['Supplier']=='KONSI-ALEENA GLOBAL KREASINDO') |
(dflabel['Supplier']=='KONSI-ALENICE') |
(dflabel['Supplier']=='KONSI-ALMIRA COLLECTION') |
(dflabel['Supplier']=='KONSI-AMS OFFICIAL') |
(dflabel['Supplier']=='KONSI-ANAK KITA') |
(dflabel['Supplier']=='KONSI-ANCILLA') |
(dflabel['Supplier']=='KONSI-ANGEL SPORT') |
(dflabel['Supplier']=='KONSI-ANUGERAH REYNINDO SEJAHTERA  ARS PT') |
(dflabel['Supplier']=='KONSI-AUSTIN') |
(dflabel['Supplier']=='KONSI-AUSTIN NEW') |
(dflabel['Supplier']=='KONSI-AYA GEYA') |
(dflabel['Supplier']=='KONSI-AZMI COLLECTION') |
(dflabel['Supplier']=='KONSI-BABY DANISH SHOP') |
(dflabel['Supplier']=='KONSI-BABY DE') |
(dflabel['Supplier']=='KONSI-BABY LOOP') |
(dflabel['Supplier']=='KONSI-BABY OLIVE KIRENA') |
(dflabel['Supplier']=='KONSI-BABY REFS') |
(dflabel['Supplier']=='KONSI-BABY SEQUOIA') |
(dflabel['Supplier']=='KONSI-BAFFARO') |
(dflabel['Supplier']=='KONSI-BAJU DINAR') |
(dflabel['Supplier']=='KONSI-BAMBOO AND BUB') |
(dflabel['Supplier']=='KONSI-BANDUNG BEDSET CENTER') |
(dflabel['Supplier']=='KONSI-BANGUN KARYA REJEKI PT') |
(dflabel['Supplier']=='KONSI-BEN BEN PARTNER') |
(dflabel['Supplier']=='KONSI-BENOA SHOES') |
(dflabel['Supplier']=='KONSI-BINTANG KENCANA DEWASA') |
(dflabel['Supplier']=='KONSI-BOBOBOI KIDS') |
(dflabel['Supplier']=='KONSI-BOBOLOGY') |
(dflabel['Supplier']=='KONSI-BOTANINA HIJAU INDONESIA PT') |
(dflabel['Supplier']=='KONSI-BUANA MODE INDONESIA') |
(dflabel['Supplier']=='KONSI-CANDY POP') |
(dflabel['Supplier']=='KONSI-CEMERLANG ABADI MULIA PT') |
(dflabel['Supplier']=='KONSI-CHIODA SPORT') |
(dflabel['Supplier']=='KONSI-CINDY') |
(dflabel['Supplier']=='KONSI-COASTER') |
(dflabel['Supplier']=='KONSI-COTTON CUB') |
(dflabel['Supplier']=='KONSI-CRIBCOT') |
(dflabel['Supplier']=='KONSI-CV MAJU JAYA') |
(dflabel['Supplier']=='KONSI-DE REVANA CHOCOLATE') |
(dflabel['Supplier']=='KONSI-DHEERAJ SHEWARKRAM') |
(dflabel['Supplier']=='KONSI-DIGI JUNIOR') |
(dflabel['Supplier']=='KONSI-DIKKYDOO') |
(dflabel['Supplier']=='KONSI-DISTRO ANAQU') |
(dflabel['Supplier']=='KONSI-DOOGLE GRUP INDONESIA PT') |
(dflabel['Supplier']=='KONSI-DUCK-DUCK INTERNASIONAL OB 30') |
(dflabel['Supplier']=='KONSI-DUCK-DUCK INTERNASIONAL OB 70') |
(dflabel['Supplier']=='KONSI-EFFATA BUANA LESTARI / NICKS COLLECTION') |
(dflabel['Supplier']=='KONSI-ELEPHAS IND MY BABY&ME') |
(dflabel['Supplier']=='KONSI-ELIZABETH BAJU RENANG') |
(dflabel['Supplier']=='KONSI-ELLIE AND ME') |
(dflabel['Supplier']=='KONSI-ELLO KIDDIES') |
(dflabel['Supplier']=='KONSI-EMPIRE CORP') |
(dflabel['Supplier']=='KONSI-EPOCH BLOOMING TOYS PT') |
(dflabel['Supplier']=='KONSI-FAVORI CORP SEDAYA PT (INA COOKIDS)') |
(dflabel['Supplier']=='KONSI-FEIVEL INTERIOR') |
(dflabel['Supplier']=='KONSI-FOGLIA') |
(dflabel['Supplier']=='KONSI-GAFI') |
(dflabel['Supplier']=='KONSI-GAIA NIAGA PREMIUM PT') |
(dflabel['Supplier']=='KONSI-GARUDA GRAHA UTAMA PT') |
(dflabel['Supplier']=='KONSI-GEMILANG PERDANA CV') |
(dflabel['Supplier']=='KONSI-GERAL DELI') |
(dflabel['Supplier']=='KONSI-GLORY BLESING') |
(dflabel['Supplier']=='KONSI-GRAMEDIA ASRI MEDIA PT') |
(dflabel['Supplier']=='KONSI-GRECA JAYA GROUP (ROBBY KIE)') |
(dflabel['Supplier']=='KONSI-GUGUGAGA') |
(dflabel['Supplier']=='KONSI-HANAROO') |
(dflabel['Supplier']=='KONSI-HARUM JAYA') |
(dflabel['Supplier']=='KONSI-HDI FIX GLOW') |
(dflabel['Supplier']=='KONSI-HELLO MICI') |
(dflabel['Supplier']=='KONSI-HERO INTI PUTRA PT') |
(dflabel['Supplier']=='KONSI-HOI HOI') |
(dflabel['Supplier']=='KONSI-HOMPIMPA') |
(dflabel['Supplier']=='KONSI-HYPEFAST KARYA NUSANTARA PT') |
(dflabel['Supplier']=='KONSI-IEWILLY ACCECORIES') |
(dflabel['Supplier']=='KONSI-INDIPAR PT') |
(dflabel['Supplier']=='KONSI-INDOMED FANNY') |
(dflabel['Supplier']=='KONSI-INSPORT') |
(dflabel['Supplier']=='KONSI-JAMAIKA BARU') |
(dflabel['Supplier']=='KONSI-JIWOONE PT') |
(dflabel['Supplier']=='KONSI-JONATHAN GARMENT INDUSTRY') |
(dflabel['Supplier']=='KONSI-JUMBO NIAGA LESTARI PT') |
(dflabel['Supplier']=='KONSI-KAMA GARAGE') |
(dflabel['Supplier']=='KONSI-KANEBO') |
(dflabel['Supplier']=='KONSI-KAOS TINA') |
(dflabel['Supplier']=='KONSI-KAPOOK STORE') |
(dflabel['Supplier']=='KONSI-KAWAH MEDIA PUSTAKA PT') |
(dflabel['Supplier']=='KONSI-KEVIN ARIYANTO') |
(dflabel['Supplier']=='KONSI-KHR BERKAH ABADI') |
(dflabel['Supplier']=='KONSI-KIDZ PROJECT ANDRIYA') |
(dflabel['Supplier']=='KONSI-KOTTON MILL') |
(dflabel['Supplier']=='KONSI-KURNIAWAN') |
(dflabel['Supplier']=='KONSI-LITTLE BUBBA') |
(dflabel['Supplier']=='KONSI-LITTLE KECIL') |
(dflabel['Supplier']=='KONSI-LITTLE KIOKO') |
(dflabel['Supplier']=='KONSI-MAHIKA KIDS') |
(dflabel['Supplier']=='KONSI-MAICIH INTI SINERGI PT') |
(dflabel['Supplier']=='KONSI-MAISON DE PALMER') |
(dflabel['Supplier']=='KONSI-MAMIBELE NURSINGWEAR') |
(dflabel['Supplier']=='KONSI-MANDIRI MASLAHAT MASAGI PT') |
(dflabel['Supplier']=='KONSI-MANOKINE BABY') |
(dflabel['Supplier']=='KONSI-MARMEL') |
(dflabel['Supplier']=='KONSI-MARSHELLA JUN MARTN') |
(dflabel['Supplier']=='KONSI-MEGA JAYA ABADI') |
(dflabel['Supplier']=='KONSI-MEGAH JAYA SENTOSA') |
(dflabel['Supplier']=='KONSI-MENGHIAS ANGKASA PT') |
(dflabel['Supplier']=='KONSI-MERE ET MOI') |
(dflabel['Supplier']=='KONSI-MIEKE BABY CARE') |
(dflabel['Supplier']=='KONSI-MILIE KIDS') |
(dflabel['Supplier']=='KONSI-MILLION COLOURS') |
(dflabel['Supplier']=='KONSI-MOM BANTAL') |
(dflabel['Supplier']=='KONSI-MOM DRESS') |
(dflabel['Supplier']=='KONSI-MOMILO BABY') |
(dflabel['Supplier']=='KONSI-MONAMICHOCO') |
(dflabel['Supplier']=='KONSI-MOROCOCO') |
(dflabel['Supplier']=='KONSI-MULLER BAG') |
(dflabel['Supplier']=='KONSI-MURANGKALIH MUSLIM') |
(dflabel['Supplier']=='KONSI-MUSTOFA') |
(dflabel['Supplier']=='KONSI-NAEM COLLECTION') |
(dflabel['Supplier']=='KONSI-NAFASHA') |
(dflabel['Supplier']=='KONSI-NAKKU') |
(dflabel['Supplier']=='KONSI-NERTUR GOODS') |
(dflabel['Supplier']=='KONSI-NIAGA SWADAYA PT') |
(dflabel['Supplier']=='KONSI-NUTRIFIT INDONESIA CV') |
(dflabel['Supplier']=='KONSI-OSMA VIVI DEWASA') |
(dflabel['Supplier']=='KONSI-PANCA PILAR') |
(dflabel['Supplier']=='KONSI-PIXIEPERIE') |
(dflabel['Supplier']=='KONSI-PLIE INDONESIA') |
(dflabel['Supplier']=='KONSI-QUEENAZ COKLAT') |
(dflabel['Supplier']=='KONSI-QUILLAVERS') |
(dflabel['Supplier']=='KONSI-QWA ETHNIQ') |
(dflabel['Supplier']=='KONSI-RASA JUARA INDONESIA') |
(dflabel['Supplier']=='KONSI-RATU KIDS') |
(dflabel['Supplier']=='KONSI-REBEL CAKRAWALA BUSANA') |
(dflabel['Supplier']=='KONSI-RED BUTTON') |
(dflabel['Supplier']=='KONSI-REED SHARK') |
(dflabel['Supplier']=='KONSI-RISNA BAG') |
(dflabel['Supplier']=='KONSI-ROODHEN INDONESIA') |
(dflabel['Supplier']=='KONSI-ROWKIDS') |
(dflabel['Supplier']=='KONSI-ROYAL MITRA PRATAMA') |
(dflabel['Supplier']=='KONSI-RUMASYA') |
(dflabel['Supplier']=='KONSI-SANDY') |
(dflabel['Supplier']=='KONSI-SANGGAR ELEGANCE INDAH') |
(dflabel['Supplier']=='KONSI-SARAH LUNABAS') |
(dflabel['Supplier']=='KONSI-SAY HELLO') |
(dflabel['Supplier']=='KONSI-SAY HELLO JAKARTA') |
(dflabel['Supplier']=='KONSI-SEVTA NUSA ENERGI PT (HUGGY)') |
(dflabel['Supplier']=='KONSI-SHEILA') |
(dflabel['Supplier']=='KONSI-SHEMA RIBBON') |
(dflabel['Supplier']=='KONSI-SHIGOTO ACCESORIES') |
(dflabel['Supplier']=='KONSI-SHOES REPUBLIC') |
(dflabel['Supplier']=='KONSI-SPRING SUMMER') |
(dflabel['Supplier']=='KONSI-STARWAYS/CITRA BARU BUSANA') |
(dflabel['Supplier']=='KONSI-SUN STATIONARY') |
(dflabel['Supplier']=='KONSI-SYAHIRA HEADBAND') |
(dflabel['Supplier']=='KONSI-TEJA ARLOJI') |
(dflabel['Supplier']=='KONSI-TIANG SURAJI CV') |
(dflabel['Supplier']=='KONSI-TIGA RAJA PERKASA') |
(dflabel['Supplier']=='KONSI-TIGA SERANGKAI') |
(dflabel['Supplier']=='KONSI-TIRTA PRATAMA KIDY RIDE CV') |
(dflabel['Supplier']=='KONSI-TRI MEGAH MAKMUR PT') |
(dflabel['Supplier']=='KONSI-V STUDIO PRINT') |
(dflabel['Supplier']=='KONSI-VALENTINE') |
(dflabel['Supplier']=='KONSI-VAN&VIE') |
(dflabel['Supplier']=='KONSI-VANIA COLLECTION') |
(dflabel['Supplier']=='KONSI-VICTORIA CARE INDONESIA PT') |
(dflabel['Supplier']=='KONSI-VICTORY (WASKITO)') |
(dflabel['Supplier']=='KONSI-VINA SELIMUT') |
(dflabel['Supplier']=='KONSI-VISI VICTORY') |
(dflabel['Supplier']=='KONSI-VISTA MEGAH') |
(dflabel['Supplier']=='KONSI-WINFUN') |
(dflabel['Supplier']=='KONSI-YANTI') |
(dflabel['Supplier']=='KONSI-YENI CAROLINE') |
(dflabel['Supplier']=='KONSI-YOBEBEE') |
(dflabel['Supplier']=='KONSI-ZANANA INDONESIA CV') 


]


dfrank_luis = dflabel_luis[['Supplier','Penjualan','Jumlah Penjualan','stock bayangan']]
dfrank_luis = dfrank_luis.groupby(['Supplier']).sum()
dfrank_luis = dfrank_luis.reset_index()
dfrank_luis['rank penjualan'] = dfrank_luis['Penjualan'].rank(method='dense')
dfrank_luis['rank value'] = dfrank_luis['Jumlah Penjualan'].rank(method='dense')
dfrank_luis['value rank'] = dfrank_luis['rank penjualan']+dfrank_luis['rank value']
dfrank_luis['rank'] = dfrank_luis['value rank'].rank(method='dense', ascending=False)

with pd.ExcelWriter(r'C:\Users\afriz\Documents\Pekerjaan\YENS\Monthly Project\Monthly Project\ready data set\purchasing\22_4_6_luis.xlsx') as luis:
    dflabel_luis.to_excel(luis, sheet_name = 'label', index = False)
    dfrank_luis.to_excel(luis, sheet_name = 'rank', index = False)

In [144]:
#dflabel_april.to_excel(r'C:\Users\afriz\Documents\Pekerjaan\YENS\Monthly Project\Monthly Project\ready data set\purchasing\df_april_2_3_22.xlsx',index=False)
#dflabel_luis.to_excel(r'C:\Users\afriz\Documents\Pekerjaan\YENS\Monthly Project\Monthly Project\ready data set\purchasing\df_luis_2_3_22.xlsx',index=False)
#dflabel_vero.to_excel(r'C:\Users\afriz\Documents\Pekerjaan\YENS\Monthly Project\Monthly Project\ready data set\purchasing\df_vero_2_3_22.xlsx',index=False)
#dflabel_ratna.to_excel(r'C:\Users\afriz\Documents\Pekerjaan\YENS\Monthly Project\Monthly Project\ready data set\purchasing\df_ratna_2_3_22.xlsx',index=False)
#dflabel_ryan.to_excel(r'C:\Users\afriz\Documents\Pekerjaan\YENS\Monthly Project\Monthly Project\ready data set\purchasing\df_ryan_2_3_22.xlsx',index=False)
#dflabel_soimah.to_excel(r'C:\Users\afriz\Documents\Pekerjaan\YENS\Monthly Project\Monthly Project\ready data set\purchasing\df_soimah_2_3_22.xlsx',index=False)
#dflabel_eri.to_excel(r'C:\Users\afriz\Documents\Pekerjaan\YENS\Monthly Project\Monthly Project\ready data set\purchasing\df_eri_2_3_22.xlsx',index=False)
#dflabel_yuki.to_excel(r'C:\Users\afriz\Documents\Pekerjaan\YENS\Monthly Project\Monthly Project\ready data set\purchasing\df_yuki_2_3_22.xlsx',index=False)

In [145]:
dflabel_april['nama'] = 'april'
dflabel_eri['nama'] = 'eri'
dflabel_luis['nama'] = 'luis'
dflabel_ratna['nama'] = 'ratna'
dflabel_ryan['nama'] = 'ryan'
dflabel_soimah['nama'] = 'soimah'
dflabel_vero['nama'] = 'vero'
dflabel_yuki['nama'] = 'yuki'

all_purchasing = pd.concat([dflabel_april,dflabel_luis,dflabel_vero,dflabel_ratna,dflabel_ryan,dflabel_soimah,dflabel_eri,dflabel_yuki],ignore_index=True)

<ipython-input-145-f9f390bf2c22>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dflabel_april['nama'] = 'april'
<ipython-input-145-f9f390bf2c22>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dflabel_eri['nama'] = 'eri'
<ipython-input-145-f9f390bf2c22>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dflabel_luis['nama'] = 'luis'
<ipython-input-145-f9f390bf2c22>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dflabel_ratna['nama'] = 'ratna'
<ipython-input-145-f9f390bf2c22>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dflabel_ryan['nama'] = 'ryan'
<ipython-input-145-f9f390bf2c22>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dflabel_soimah['nama'] = 'soimah'
<ipython-input-145-f9f390bf2c22>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dflabel_vero['nama'] = 'vero'
<ipython-input-145-f9f390bf2c22>:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dflabel_yuki['nama'] = 'yuki'

In [146]:
all_purchasing.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 291125 entries, 0 to 291124
Data columns (total 27 columns):
 #   Column                           Non-Null Count   Dtype
---  ------                           --------------   -----
 0   Kode Barang                      291125 non-null  object
 1   Barcode                          291125 non-null  object
 2   Artikel                          291125 non-null  object
 3   Nama Barang                      291125 non-null  object
 4   Keterangan Barang                177991 non-null  object
 5   Input Barang                     291125 non-null  object
 6   Supplier                         291092 non-null  object
 7   Input Supplier                   291125 non-null  object
 8   Sub Dept                         291125 non-null  object
 9   Kelompok                         291092 non-null  object
 10  Stock Awal                       291125 non-null  object
 11  Stock In                         291125 non-null  object
 12  Stock Out                        291125 non-null  object
 13  Penjualan                        291125 non-null  object
 14  Stock Akhir                      291125 non-null  object
 15  Harga Beli                       287777 non-null  object
 16  Harga Jual                       287777 non-null  object
 17  Stock By Harga Beli              291125 non-null  object
 18  Stock By Harga Jual              291125 non-null  object
 19  Jumlah Penjualan                 291125 non-null  object
 20  Value Stock IN(HJ)               291125 non-null  object
 21  cabang                           291125 non-null  object
 22  bulan                            291125 non-null  object
 23  _merge                           291125 non-null  object
 24  stock bayangan                   291125 non-null  object
 25  hitungan stcok satu bulan akhir  291125 non-null  int64
 26  nama                             291125 non-null  object
dtypes: int64(1), object(26)
memory usage: 60.0+ MB

In [147]:
#all_purchasing.to_excel(r'C:\Users\afriz\Documents\Pekerjaan\YENS\Monthly Project\Monthly Project\ready data set\purchasing\22_4_6_all_purchasing.xlsx')